source: "https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.16.2.tar.xz"
hash: "e3f044246783fd685439647373fa13ba14f7ab0b346eadd06437092f8419e94e"
version: "1.16.2-6"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

cherry_pick: "make-4.3.patch"

# build dependencies:
dep: "perl"
dep: "bison"
dep: "flex"
dep: "python3"
dep: "glib"
