source: "http://download.savannah.nongnu.org/releases/libpipeline/libpipeline-1.5.2.tar.gz"
hash: "fd59c649c1ae9d67604d1644f116ad4d297eaa66f838e3dfab96b41e85b059fb"
version: "1.5.2-7"

cbuilder: {}

# build dependencies:
