source: "https://curl.haxx.se/download/curl-7.69.1.tar.bz2"
hash: "2ff5e5bd507adf6aa88ff4bbafd4c7af464867ffb688be93b9930717a56c4de8"
version: "7.69.1-8"

cbuilder: {
  extra_configure_flag: "--with-ca-path=/etc/ssl/certs"
}

# build dependencies:
dep: "openssl"

runtime_dep: "ca-certificates"
