source: "https://download.gnome.org/sources/libsigc++/2.10/libsigc++-2.10.3.tar.xz"
hash: "0b68dfc6313c6cc90ac989c6d722a1bf0585ad13846e79746aa87cb265904786"
version: "2.10.3-7"

cbuilder: {}

# build dependencies:
dep: "m4"
