source: "https://www.freedesktop.org/software/libinput/libinput-1.13.2.tar.xz"
hash: "1d9fa0698348dea46f75321d98788f8ac7181c069b70c4d10736910a12bb6a6d"
version: "1.13.2-9"

mesonbuilder: {
  extra_meson_flag: "-Dlibwacom=false"
  extra_meson_flag: "-Ddocumentation=false"  # needs doxygen
}

# build dependencies:
dep: "systemd"  # for udev
dep: "mtdev"
dep: "libevdev"
dep: "gtk+"
dep: "check"
