source: "https://xorg.freedesktop.org/releases/individual/app/xkbcomp-1.4.3.tar.bz2"
hash: "06242c169fc11caf601cac46d781d467748c6a330e15b36dce46520b8ac8d435"
version: "1.4.3-8"

cbuilder: {
  extra_configure_flag: "--with-xkb-config-root=/ro/${DISTRI_RESOLVE:xkeyboard-config}/out/share/X11/xkb"
}

# build dependencies:
dep: "xorgproto"
dep: "libx11"
dep: "libxkbfile"

runtime_dep: "xkeyboard-config"
