source: "https://xorg.freedesktop.org/releases/individual/app/xkbcomp-1.4.2.tar.bz2"
hash: "6dd8bcb9be7e85bd7294abe261b8c7b0539d2fc93e41b80fb8bd013767ce8424"
version: "1.4.2-4"

cbuilder: {
  extra_configure_flag: "--with-xkb-config-root=/ro/${DISTRI_RESOLVE:xkeyboard-config}/out/share/X11/xkb"
}

# build dependencies:
dep: "xorgproto"
dep: "libx11"
dep: "libxkbfile"

runtime_dep: "xkeyboard-config"
