source: "https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.5.tar.bz2"
hash: "3b4a2a94cb637eff5bdebbcaf46f4d95c4f25206f459809339cdada0eb577ac3"
version: "1.8.5-7"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# build dependencies:
dep: "libgpg-error"
