source: "https://ftp.pcre.org/pub/pcre/pcre-8.44.tar.bz2"
hash: "19108658b23b3ec5058edc9f66ac545ea19f9537234be1ec62b714c84399366d"
version: "8.44-7"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# build dependencies:
