source: "https://ftp.pcre.org/pub/pcre/pcre-8.42.tar.bz2"
hash: "2cd04b7c887808be030254e8d77de11d3fe9d4505c39d4b15d2664ffe8bf9301"
version: "8.42-5"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# build dependencies:
