source: "https://ftp.pcre.org/pub/pcre/pcre-8.42.tar.bz2"
hash: "2cd04b7c887808be030254e8d77de11d3fe9d4505c39d4b15d2664ffe8bf9301"
version: "8.42"

cbuilder: <>

# build dependencies:

# TODO: to work around g++ issue where #include_next <stdlib.h> from cstdlib.h won’t find the header
build_step: <
  argv: "ln"
  argv: "-s"
  argv: "/ro/glibc-2.27/buildoutput/include"
  argv: "/usr/include"
>

build_step: <
  argv: "${ZI_SOURCEDIR}/configure"
  argv: "--prefix=${ZI_PREFIX}"
>

build_step: <
  argv: "make"
  argv: "-j8"
  argv: "V=1"
>

build_step: <
  argv: "make"
  argv: "install"
  argv: "DESTDIR=${ZI_DESTDIR}"
  argv: "PREFIX=${ZI_PREFIX}"
>
