source: "https://xorg.freedesktop.org/releases/individual/lib/libXrandr-1.5.1.tar.bz2"
hash: "1ff9e7fa0e4adea912b16a5f0cfa7c1d35b0dcda0e216831f7715c8a3abcf51a"
version: "1.5.1-6"

cbuilder: {}

# build dependencies:
dep: "libx11"
dep: "libxext"
dep: "libxrender"
