source: "https://cpan.metacpan.org/authors/id/E/ET/ETHER/libwww-perl-6.36.tar.gz"
hash: "75c034ab4b37f4b9506dc644300697505582cf9545bcf2e2079e7263f675290a"
version: "6.36-7"

perlbuilder: {}

# build dependencies:
dep: "perl-Encode-Locale"
dep: "perl-File-Listing"
dep: "perl-HTML-Parser"
dep: "perl-HTTP-Cookies"
dep: "perl-HTTP-Message"
dep: "perl-URI"
dep: "perl-HTTP-Daemon"
dep: "perl-HTTP-Negotiate"
dep: "perl-Net-HTTP"
dep: "perl-Test-Fatal"
dep: "perl-Test-RequiresInternet"
dep: "perl-WWW-RobotRules"
