source: "https://cpan.metacpan.org/authors/id/E/ET/ETHER/libwww-perl-6.35.tar.gz"
hash: "dda2578d7b32152c4afce834761a61d117de286c705a9f7972c7ac6032ca5953"
version: "6.35-4"

perlbuilder: {}

# build dependencies:
dep: "perl-Encode-Locale"
dep: "perl-File-Listing"
dep: "perl-HTML-Parser"
dep: "perl-HTTP-Cookies"
dep: "perl-HTTP-Message"
dep: "perl-URI"
dep: "perl-HTTP-Daemon"
dep: "perl-HTTP-Negotiate"
dep: "perl-Net-HTTP"
dep: "perl-Test-Fatal"
dep: "perl-Test-RequiresInternet"
dep: "perl-WWW-RobotRules"
