source: "http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.6.tar.xz"
hash: "af00bb5a784e7c9e69f56823de4637c350643deedaf333d0fa86ecdba6fcb415"
version: "1.3.6-6"

cbuilder: {}

# build dependencies:
dep: "libogg"
