source: "https://ftp.gnome.org/pub/gnome/sources/gtk+/3.24/gtk+-3.24.18.tar.xz"
hash: "f5eaff7f4602e44a9ca7bfad5382d7a73e509a8f00b0bcab91c198d096172ad2"
version: "3.24.18-11"

cbuilder: {
  extra_configure_flag: "have_xinput2=yes"  # libxi detection seems broken
}

# build dependencies:
dep: "gdk-pixbuf"
dep: "shared-mime-info"  # TODO: bring in via gdk-pixbuf
dep: "pango"
dep: "cairo"
dep: "atk"
dep: "libxinerama"
dep: "libxi"
dep: "libepoxy"
dep: "mesa"
dep: "atk"
dep: "at-spi2-atk"
dep: "python3"
dep: "perl"
dep: "libxcomposite"
dep: "libxrandr"
