source: "https://ftp.gnome.org/pub/gnome/sources/gtk+/3.24/gtk+-3.24.0.tar.xz"
hash: "02e991389277206253d79884d10e5aa06fd78fdf7a5096799dbe3c97a05e32a8"
version: "3.24.0"

cbuilder: <
  extra_configure_flag: "have_xinput2=yes" # libxi detection seems broken
>

# build dependencies:
dep: "gdk-pixbuf-2.38.0"
dep: "shared-mime-info-1.10" # TODO: bring in via gdk-pixbuf
dep: "pango-1.42.4"
dep: "cairo-1.14.12"
dep: "atk-2.30.0"
dep: "libxinerama-1.1.4"
dep: "libxi-1.7.9"
dep: "libepoxy-1.5.2"
dep: "mesa-18.2.0"
dep: "atk-2.30.0"
dep: "at-spi2-atk-2.30.0"
dep: "python3-3.7.0"
dep: "perl-5.28.0"
