source: "https://github.com/jonas/tig/releases/download/tig-2.5.1/tig-2.5.1.tar.gz"
hash: "500d5d34524f6b856edd5cae01f1404d14f3b51a9a53fd7357f4cebb3d4c9e64"
version: "2.5.1-7"

writable_sourcedir: true
in_tree_build: true

cbuilder: {
}

# build dependencies:
dep: "ncurses"
