source: "https://github.com/erikd/libsndfile/archive/1.0.28.tar.gz"
hash: "89abe87316bc9afac9e5b34b137a399286cbcd6affad409b110596e3b749c897"
version: "1.0.28-1"

cbuilder: <>

# build dependencies:
dep: "autoconf"
dep: "autogen"
dep: "alsa-lib"
dep: "flac"
dep: "libogg"
dep: "libvorbis"

dep: "automake"
dep: "python3"

# sndio
# sqlite

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "cp -T -ar ${DISTRI_SOURCEDIR}/ ."
>

# TODO: make /share/aclocal an exchange dir
build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "cp /ro/pkg-config-amd64-0.29.2-1/out/share/aclocal/pkg.m4 M4/"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "./autogen.sh; autoreconf -fi"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "mkdir build"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "./configure --prefix=${DISTRI_PREFIX}"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "make -j8 V=1"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "make install DESTDIR=${DISTRI_DESTDIR} PREFIX=${DISTRI_PREFIX}"
>
