source: "https://ftp.gnome.org/pub/GNOME/sources/libsoup/2.65/libsoup-2.65.92.tar.xz"
hash: "7b11ea0ff543a3ac65f1db4d996922f45726401619093cba29690d68f687a916"
version: "2.65.92-8"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

mesonbuilder: {
  extra_meson_flag: "-Dgssapi=false"
}

# build dependencies:
dep: "libxml2"
dep: "sqlite3"
dep: "libpsl"
dep: "intltool"
dep: "glib-networking"
dep: "gobject-introspection"
dep: "vala"
dep: "glib"
