source: "https://ftp.gnome.org/pub/GNOME/sources/libsoup/2.65/libsoup-2.65.1.tar.xz"
hash: "3f3718623338f1bd7d7899dae2bdb613348212d59999a27432120afc1435ff04"
version: "2.65.1-1"

cbuilder: <>

# build dependencies:
dep: "libxml2"
dep: "sqlite3"
dep: "libpsl"
dep: "intltool"
# TODO: this check fails, maybe because glib-networking contains loadable gio* .so files?
dep: "glib-networking"
dep: "gobject-introspection"
dep: "vala"
