source: "https://cpan.metacpan.org/authors/id/E/ET/ETHER/URI-1.74.tar.gz"
hash: "a9c254f45f89cb1dd946b689dfe433095404532a4543bdaab0b71ce0fdcdd53d"
version: "1.74-6"

perlbuilder: {}

# build dependencies:
dep: "perl-Test-Needs"
