source: "https://github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz"
hash: "a79d19dcdf9139fa4b81206e318e33d245c4c9da1ffed21c87288ed4380426f9"
version: "3.11.4-7"

writable_sourcedir: true  # for autoreconf
in_tree_build: true

cbuilder: {
  autoreconf: true

  # The static versions of the library (.a files) take up hundreds of megabytes
  # of space, and distri does not generally support static linking.
  extra_configure_flag: "--disable-static"
}

# build dependencies:
