source: "https://t.zekjur.net/mplayer-export-2019-02-19%2Bffmpeg.tar.bz2"
hash: "ac054bad4754a2ee4e185ac94598906562aa4a30eaf63ff02b899e22f9756ac5"
version: "0.2019-02-19-11"

copy_to_builddir: true

cbuilder: {
  #  extra_configure_flag: "--without-bash-malloc"
}

dep: "yasm"
dep: "pulseaudio"
dep: "libx11"
dep: "mesa"
dep: "freetype"
dep: "fontconfig"

build_step: {
  argv: "./configure"
  argv: "--prefix=${DISTRI_PREFIX}"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  argv: "V=1"
}

# TODO: destdir
build_step: {
  argv: "make"
  argv: "install-mplayer"
  argv: "V=1"
  argv: "DESTDIR=${DISTRI_DESTDIR}"
}
