source: "https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2"
hash: "5275bb04f4863a13516b2f39392ac5e272f5e1bb8057b18aec1c9b79d73d8fb2"
version: "6.1.2-1"

# build dependencies:
dep: "m4"

cbuilder: <>

