source: "https://nmap.org/dist/nmap-7.80.tar.bz2"
hash: "fcfa5a0e42099e12e4bf7a68ebe6fde05553383a682e816a7ec9256ab4773faa"
version: "7.80-7"

writable_sourcedir: true
in_tree_build: true

cbuilder: {
  # Keep debug symbols in make install
  extra_make_flag: "STRIP=/bin/true"
}

# build dependencies:
dep: "openssl"
dep: "flex"
dep: "bison"
