source: "https://xorg.freedesktop.org/releases/individual/lib/libSM-1.2.3.tar.bz2"
hash: "2d264499dcb05f56438dee12a1b4b71d76736ce7ba7aa6efbf15ebb113769cbb"
version: "1.2.3"

cbuilder: <>

# build dependencies:
dep: "xorgproto-2018.4"
dep: "xtrans-1.3.5"
dep: "libice-1.0.9"
