source: "https://downloads.sourceforge.net/project/squashfs/squashfs/squashfs4.3/squashfs4.3.tar.gz"
hash: "0d605512437b1eb800b4736791559295ee5f60177e102e4d4ccd0ee241a5f3f6"
version: "4.3"

cbuilder: <>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "cp -T -ar ${ZI_SOURCEDIR}/ ."
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "CC=gcc make -C squashfs-tools -j8"
>
build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "make -C squashfs-tools install INSTALL_DIR=${ZI_DESTDIR}/${ZI_PREFIX}/bin"
>
