source: "https://github.com/plougher/squashfs-tools/archive/4.4.tar.gz"
hash: "a7fa4845e9908523c38d4acf92f8a41fdfcd19def41bd5090d7ad767a6dc75c3"
version: "4.4-7"

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "CC=gcc make -C squashfs-tools -j${DISTRI_JOBS}"
}
build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "make -C squashfs-tools install INSTALL_DIR=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/bin"
}
