source: "https://xorg.freedesktop.org/releases/individual/lib/libXinerama-1.1.4.tar.bz2"
hash: "0008dbd7ecf717e1e507eed1856ab0d9cf946d03201b85d5dcf61489bb02d720"
version: "1.1.4-3"

cbuilder: {}

# build dependencies:
dep: "libx11"
dep: "libxext"
