source: "https://ftp.gnu.org/gnu/glibc/glibc-2.31.tar.gz"
hash: "cb2d64fb808affff30d8a99a85de9d2aa67dc2cbac4ae99af4500d6cfea2bda7"
version: "2.31-4"

cherry_pick: "ldd.patch"  # TODO: figure out why RTLDLIST gets the wrong value

cbuilder: {
  # Contrary to what is stated in ld.so(8), glibc does not seem to search /lib
  # and /usr/lib (or /lib64 and /usr/lib64, respectively), resulting in the
  # nsswitch mechanism not finding e.g. libnss_myhostname.so. Hence, we tell
  # glibc explicitly to search /ro/lib:
  extra_make_flag: "user-defined-trusted-dirs=/ro/lib"

  # TODO: specifying localedata/install-locales here results in an error message:
  # aa_DJ.UTF-8aa_DJ.ISO-8859-1aa_ET.UTF-8aa_ER.UTF-8aa_ER.UTF-8agr_PE.UTF-8af_ZA.UTF-8...af_ZA.ISO-8859-1......@saaho............/bin/sh: line 13: /tmp/distri-build171828973/elf/ld-linux-x86-64.so.2: No such file or directory
  # Install all supported locales:
  #  extra_make_flag: "localedata/install-locales"
}

# build dependencies:
dep: "bison"
dep: "m4"  # TODO: remove once m4 is declared a runtime-dep of bison
dep: "gzip"
dep: "python3"

# TODO: specify cross-compile target like in buildc.go?
build_step: {
  argv: "${DISTRI_SOURCEDIR}/configure"
  argv: "--prefix=${DISTRI_PREFIX}"
  argv: "--sysconfdir=/etc"
  argv: "--disable-dependency-tracking"
  # TODO: remove again
  #  argv: "--enable-static-nss"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  argv: "V=1"
  argv: "user-defined-trusted-dirs=/ro/lib"
}

build_step: {
  argv: "make"
  argv: "install"
  argv: "DESTDIR=${DISTRI_DESTDIR}"
  argv: "PREFIX=${DISTRI_PREFIX}"
  argv: "user-defined-trusted-dirs=/ro/lib"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  argv: "localedata/install-locales"
  argv: "DESTDIR=${DISTRI_DESTDIR}"
  argv: "PREFIX=${DISTRI_PREFIX}"
  argv: "user-defined-trusted-dirs=/ro/lib"
}

build_step: {
  argv: "rm"
  argv: "${DISTRI_DESTDIR}/etc/ld.so.cache"
}
