source: "https://i3wm.org/i3status/i3status-2.12.tar.bz2"
hash: "6fc6881536043391ab4bed369d956f99d1088965d8bcebed18d1932de3ba791a"
version: "2.12"

cbuilder: <>

# build dependencies:
dep: "confuse"
dep: "yajl2"
dep: "alsa-lib"
dep: "libnl"
dep: "pulseaudio"
dep: "which"

build_step: <
  argv: "make"
  argv: "-C"
  argv: "${ZI_SOURCEDIR}"
  argv: "SYSCONFDIR=/etc"
>

build_step: <
  argv: "make"
  argv: "-C"
  argv: "${ZI_SOURCEDIR}"
  argv: "install"
  argv: "DESTDIR=${ZI_DESTDIR}"
  argv: "PREFIX=${ZI_PREFIX}"
  argv: "SYSCONFDIR=/etc"
  argv: "V=1"
>

