source: "https://i3wm.org/i3status/i3status-2.13.tar.bz2"
hash: "ce89c9ff8565f62e88299f1a611229afdfc356b4e97368a5f8c4f06ad2fa1466"
version: "2.13-8"

# sed -i 's,@PATH_XMLTO@,XML_CATALOG_FILES=/ro/docbook-xsl-amd64-1.79.2-1/out/docbook-xsl.xmlcatalog @PATH_XMLTO@ --skip-validation,g' Makefile.in
cherry_pick: "xmlto.patch"

cbuilder: {}

# build dependencies:
dep: "confuse"
dep: "yajl2"
dep: "alsa-lib"
dep: "libnl"
dep: "pulseaudio"
dep: "which"
dep: "asciidoc"
dep: "xmlto"
dep: "docbook-xsl"

install: {
  capability: {
    filename: "bin/i3status"
    capability: "cap_net_admin=ep"
  }
}
