source: "https://github.com/libexpat/libexpat/releases/download/R_2_2_6/expat-2.2.6.tar.bz2"
hash: "17b43c2716d521369f82fc2dc70f359860e90fa440bea65b3b85f0b246ea81f2"
version: "2.2.6-6"

cbuilder: {}

# build dependencies:
