source: "https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.bz2"
hash: "f1063084dc4302a427dabcca499c8312b3a32a29b7d2506653ecc8f950a9a237"
version: "2.2.9-7"

cbuilder: {}

# build dependencies:
