source: "https://github.com/mesonbuild/meson/archive/0.47.1.tar.gz"
hash: "c227ae37c1d4c8fc1531d536b38ff1fbf7afb08c59fc54a5321645164e5f92a8"
version: "0.47.1"

pythonbuilder: <>

runtime_dep: "ninja"

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "cp -T -ar ${ZI_SOURCEDIR}/ ."
>

# https://github.com/NixOS/nixpkgs/pull/28444#issuecomment-324033323
build_step: <
  argv: "sed"
  argv: "-i"
  argv: "s/if os.path.isfile(outname):/if False:/g"
  argv: "mesonbuild/minstall.py"
>

build_step: <
  argv: "python3"
  argv: "setup.py"
  argv: "install"
  argv: "--prefix=${ZI_PREFIX}"
  argv: "--root=${ZI_DESTDIR}"
>
