source: "https://github.com/GNOME/gcab/archive/v1.4.tar.gz"
hash: "ed76766e44db332d36fc53d50398482cfe3671bc3821d5b0f92e4a0788a6d226"
version: "1.4-8"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

mesonbuilder: {
  extra_meson_flag: "-Ddocs=false"
}

# build dependencies:
dep: "gobject-introspection"
dep: "gettext"
dep: "vala"
dep: "glib"
