source: "https://cdn.kernel.org/pub/linux/utils/kernel/kmod/kmod-27.tar.xz"
hash: "c1d3fbf16ca24b95f334c1de1b46f17bbe5a10b0e81e72668bdc922ebffbbc0c"
version: "27-6"

cbuilder: {
}

# build dependencies:
dep: "findutils"

install: {
  symlink: { oldname: "kmod" newname: "bin/modprobe" }
  symlink: { oldname: "kmod" newname: "bin/depmod" }
  symlink: { oldname: "kmod" newname: "bin/lsmod" }
  symlink: { oldname: "kmod" newname: "bin/rmmod" }
}
