source: "https://cdn.kernel.org/pub/linux/utils/kernel/kmod/kmod-25.tar.xz"
hash: "7165e6496656159dcb909a91ed708a0fe273a4b128b4b1dc997ccb5189eef1cd"
version: "25-5"

cbuilder: {
}

# build dependencies:
dep: "findutils"

install: {
  symlink: { oldname: "kmod" newname: "bin/modprobe" }
  symlink: { oldname: "kmod" newname: "bin/depmod" }
  symlink: { oldname: "kmod" newname: "bin/lsmod" }
  symlink: { oldname: "kmod" newname: "bin/rmmod" }
}
