source: "https://xcb.freedesktop.org/dist/xcb-util-0.4.0.tar.bz2"
hash: "46e49469cb3b594af1d33176cd7565def2be3fa8be4371d62271fabb5eae50e9"
version: "0.4.0-7"

cbuilder: {}

# build dependencies:
dep: "libxcb"
dep: "xorgproto"

