source: "https://ftp.gnu.org/gnu/bash/bash-4.4.18.tar.gz"
hash: "604d9eec5e4ed5fd2180ee44dd756ddca92e0b6aa4217bbab2b6227380317f23"
version: "4.4.18"

cbuilder: <
  extra_configure_flag: "--without-bash-malloc"
>
