source: "https://ftp.gnu.org/gnu/bash/bash-5.0.tar.gz"
hash: "b4a80f2ac66170b2913efbfb9f2594f1f76c7b1afd11f799e22035d63077fb4d"
version: "5.0-4"

cbuilder: {
  extra_configure_flag: "--without-bash-malloc"
}

dep: "ncurses"

install: {
  symlink: { oldname: "bash" newname: "bin/sh" }
}
