source: "https://cpan.metacpan.org/authors/id/C/CJ/CJM/IO-HTML-1.001.tar.gz"
hash: "ea78d2d743794adc028bc9589538eb867174b4e165d7d8b5f63486e6b828e7e0"
version: "1.001-3"

perlbuilder: {}

# build dependencies:
