source: "https://xorg.freedesktop.org/releases/individual/proto/xorgproto-2020.1.tar.bz2"
hash: "54a153f139035a376c075845dd058049177212da94d7a9707cf9468367b699d2"
version: "2020.1-7"

cbuilder: {}

# build dependencies:

# TODO: the contents do not seem to be picked up in the pkgconfig lib dir correctly
install: {
  symlink: { oldname: "../share/pkgconfig" newname: "lib/pkgconfig" }
}
