source: "https://www.musl-libc.org/releases/musl-1.1.22.tar.gz"
hash: "8b0941a48d2f980fd7036cfbd24aa1d414f03d9a0652ecbd5ec5c7ff1bee29e3"
version: "1.1.22-4"

cherry_pick: "static-linking.patch"

cbuilder: {
  # To prevent the musl configure from thinking we are cross-compiling:
  extra_configure_flag: "--build=x86_64-pc-linux-gnu"
  # musl’s prefix defaults to /usr/local/musl to not interfere with the
  # system unless musl-gcc is invoked.
  extra_configure_flag: "--prefix=${DISTRI_PREFIX}/musl"
  extra_configure_flag: "--bindir=${DISTRI_PREFIX}/bin"
}

# build dependencies:
dep: "binutils"
