source: "https://www.musl-libc.org/releases/musl-1.2.0.tar.gz"
hash: "c6de7b191139142d3f9a7b5b702c9cae1b5ee6e7f57e582da9328629408fd4e8"
version: "1.2.0-6"

cherry_pick: "static-linking.patch"

cbuilder: {
  # To prevent the musl configure from thinking we are cross-compiling:
  extra_configure_flag: "--build=x86_64-pc-linux-gnu"
  # musl’s prefix defaults to /usr/local/musl to not interfere with the
  # system unless musl-gcc is invoked.
  extra_configure_flag: "--prefix=${DISTRI_PREFIX}/musl"
  extra_configure_flag: "--bindir=${DISTRI_PREFIX}/bin"
}

# build dependencies:
dep: "binutils"
