source: "http://ftp.vim.org/pub/vim/unix/vim-8.2.tar.bz2"
hash: "f087f821831b4fece16a0461d574ccd55a8279f64d635510a1e10225966ced3b"
version: "8.2-5"

writable_sourcedir: true
in_tree_build: true

cbuilder: {
  # Keep debug symbols in make install
  extra_make_flag: "STRIP=/bin/true"
}

# build dependencies:
dep: "ncurses"
