source: "https://github.com/mobile-shell/mosh/releases/download/mosh-1.3.2/mosh-1.3.2.tar.gz"
hash: "da600573dfa827d88ce114e0fed30210689381bbdcff543c931e4d6a2e851216"
version: "1.3.2-5"

cbuilder: {}

# build dependencies:
dep: "protobuf"
dep: "ncurses"
dep: "openssl"
