source: "http://mirror.koddos.net/gcc/releases/gcc-8.2.0/gcc-8.2.0.tar.xz"
hash: "196c3c04ba2613f893283977e6011b2345d1cd1af9abeac58e916b1aab3e0080"
version: "8.2.0-1"

# cbuilder: <
#   extra_configure_flag: "--disable-multilib" # TODO: fix multilib (requires 32-bit libc+headers)
#   extra_configure_flag: "--enable-languages=c,c++" # skip fortran etc. for now
# >

dep: "bash"
dep: "coreutils"
dep: "sed"
dep: "grep"
dep: "gawk"
dep: "diffutils"
dep: "file"

# C build environment:
dep: "gcc"
dep: "binutils"
dep: "make"
dep: "glibc"
dep: "linux"
dep: "findutils" # find(1) is used by libtool, build of e.g. libidn2 will fail if not present
dep: "patchelf"

# build dependencies:
dep: "gmp"
dep: "mpfr"
dep: "mpc"
dep: "tar"

# TODO: remove once splitting files out of a package leaves a runtime dep behind
dep: "gcc-libs" # to pick up the latest version

# kludge: the C++ header cstdlib uses the #include_next pragma, which requires
# that /ro/glibc-amd64-2.27/out/include comes _after_ the g++ includes. This
# requires /ro/glibc-amd64-2.27/out/include to be a system include, which we
# achieve by symlinking /usr/include to it.
build_step: <
  argv: "rm"
  argv: "/usr/include"
>
build_step: <
  argv: "ln"
  argv: "-s"
  argv: "/ro/${DISTRI_RESOLVE:glibc}/out/include"
  argv: "/usr/include"
>
# TODO: the g++ search path needs to be changed.
# print the search path using “echo | cpp -xc++ -Wp,-v”
# the search path is persisted in gcc/cppdefault.c

build_step: <
  argv: "${DISTRI_SOURCEDIR}/configure"
  argv: "--prefix=${DISTRI_PREFIX}"
  argv: "--disable-multilib" # TODO: fix multilib (requires 32-bit libc+headers)
  # argv: "--with-stage1-ldflags=-static"
  # argv: "--with-boot-ldflags=-static"
  argv: "--enable-languages=c,c++"
  argv: "--enable-linker-build-id" # compiler will always pass --build-id to linker
>

build_step: <
  argv: "make"
  argv: "-j8"
  argv: "V=1"
>

build_step: <
  argv: "make"
  argv: "install"
  argv: "DESTDIR=${DISTRI_DESTDIR}"
>

install: <
  symlink: < oldname: "gcc" newname: "bin/cc" >
>

split_package: <
  name: "gcc-libs"
  claim: < glob: "out/lib64/libgcc_s.so*" >
  claim: < glob: "out/lib64/libstdc++.so*" >
  claim: < glob: "out/lib64/libgomp.so*" >
  claim: <
    glob: "out/lib/gcc/x86_64-pc-linux-gnu/8.2.0/crt*.o"
    dir: "out/lib64"
  >
>
