source: "https://github.com/dosfstools/dosfstools/releases/download/v4.1/dosfstools-4.1.tar.xz"
hash: "e6b2aca70ccc3fe3687365009dd94a2e18e82b688ed4e260e04b7412471cc173"
version: "4.1-5"

cbuilder: {}

# build dependencies:
