source: "https://github.com/systemd/systemd/archive/v245.tar.gz"
hash: "f34f1dc52b2dc60563c2deb6db86d78f6a97bceb29aa0511436844b2fc618040"
version: "245-11"

writable_sourcedir: true
in_tree_build: true

cherry_pick: "getty-paths.patch"
cherry_pick: "serial-getty-simple.patch"
cherry_pick: "udevdir.patch"
cherry_pick: "isatty.patch"

cbuilder: {}

# build dependencies:
dep: "m4"
dep: "gperf"
dep: "libcap"
dep: "util-linux"
dep: "gettext"
dep: "meson"
dep: "kmod"
dep: "cryptsetup"
dep: "systemd"  # to pick up the latest version

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "./configure --prefix=${DISTRI_PREFIX} -Drootprefix=${DISTRI_PREFIX} -Dsplit-usr=false -Dsplit-bin=false -Dloadkeys-path=/bin/loadkeys -Dsetfont-path=/bin/setfont -Ddefault-hierarchy=hybrid"
  #  argv: "LDFLAGS=-static"
}

# workaround for meson to pick up the sed change we are about to do:
build_step: {
  argv: "sleep"
  argv: "1"
}

build_step: {
  argv: "sed"
  argv: "-i"
  argv: "/shift-overflow/d"
  argv: "meson.build"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "ninja -j ${DISTRI_JOBS} -C build -v"
}

# TODO: glibc bug: https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/sys/mount.h;h=ce2838e3a79caf1f49c9aceacb143ff5e403e50e;hb=HEAD#l85 should read 1UL, not 1:
# /ro/glibc-2.27/out/include/sys/mount.h:85:17: error: result of '1 << 31' requires 33 bits to represent, but 'int' only has 32 bits [-Werror=shift-overflow=]
#   MS_NOUSER = 1 << 31
#                 ^~

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "DESTDIR=${DISTRI_DESTDIR} make install"
}

install: {
  # TODO: remove once both share/pkgconfig (arch-indep) and lib/pkgconfig (arch-dep) are union overlays
  symlink: { oldname: "../../share/pkgconfig/udev.pc" newname: "lib/pkgconfig/udev.pc" }
}

split_package: {
  name: "libudev"
  claim: { glob: "out/lib/libudev.so*" }
  claim: { glob: "out/include/libudev.h" }
  claim: { glob: "out/lib/pkgconfig/*udev.pc" }
  claim: { glob: "out/share/pkgconfig/*udev.pc" }
}
