source: "https://github.com/systemd/systemd/archive/v245.tar.gz"
hash: "f34f1dc52b2dc60563c2deb6db86d78f6a97bceb29aa0511436844b2fc618040"
version: "245-11"

writable_sourcedir: true

cherry_pick: "getty-paths.patch"

cherry_pick: "serial-getty-simple.patch"

cherry_pick: "udevdir.patch"

cherry_pick: "isatty.patch"

# Based on:
# * https://github.com/systemd/systemd/pull/13881
# * https://www.redhat.com/archives/linux-lvm/2020-April/msg00003.html
# * https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f36776fafbaa0094390dd4e7e3e29805e0b82730
cherry_pick: "udevadm-synth.patch"

# ProtectSystem=yes and ProtectSystem=full try to remount /usr read-only,
# but on distri, /usr is a symlink to /, which means it will mount / read-only
# (one element of ProtectSystem=strict), which unsurprisingly breaks programs.
cherry_pick: "protectsystem-usr.patch"

mesonbuilder: {
  # TODO: should this go into the mesonbuilder, or should systemd’s meson
  # files pick it up from --prefix?
  extra_meson_flag: "-Drootprefix=${DISTRI_PREFIX}"
  extra_meson_flag: "-Dsplit-usr=false"
  extra_meson_flag: "-Dsplit-bin=false"
  extra_meson_flag: "-Dloadkeys-path=/bin/loadkeys"
  extra_meson_flag: "-Dsetfont-path=/bin/setfont"
  extra_meson_flag: "-Dnologin-path=/bin/nologin"
  extra_meson_flag: "-Ddefault-hierarchy=hybrid"
  extra_meson_flag: "-Dman=true"
}

# build dependencies:
dep: "m4"
dep: "gperf"
dep: "libcap"
dep: "util-linux"
dep: "gettext"
dep: "meson"
dep: "kmod"
dep: "cryptsetup"
dep: "systemd"  # to pick up the latest version
dep: "libxslt"  # xsltproc for manpages
dep: "docbook-xsl"
dep: "docbook-xml"

install: {
  # TODO: remove once both share/pkgconfig (arch-indep) and lib/pkgconfig (arch-dep) are union overlays
  symlink: { oldname: "../../share/pkgconfig/udev.pc" newname: "lib/pkgconfig/udev.pc" }
}

split_package: {
  name: "libudev"
  claim: { glob: "out/lib/libudev.so*" }
  claim: { glob: "out/include/libudev.h" }
  claim: { glob: "out/lib/pkgconfig/*udev.pc" }
  claim: { glob: "out/share/pkgconfig/*udev.pc" }
}
