source: "https://github.com/ivmai/bdwgc/releases/download/v8.0.0/gc-8.0.0.tar.gz"
hash: "8f23f9a20883d00af2bff122249807e645bdf386de0de8cbd6cce3e0c6968f04"
version: "8.0.0-2"

cbuilder: <>

# build dependencies:
