source: "https://repo.distr1.org/distri/jackherer/orig/mpfr/mpfr-4.0.1.tar.xz"
hash: "67874a60826303ee2fb6affc6dc0ddd3e749e9bfcb4c8655e3953d0458a6e16e"
version: "4.0.1-3"

cbuilder: {}

# build dependencies:
dep: "gmp"
