source: "https://github.com/NVIDIA/libglvnd/releases/download/v1.2.0/libglvnd-1.2.0.tar.gz"
hash: "2dacbcfa47b7ffb722cbddc0a4f1bc3ecd71d2d7bb461bceb8e396dc6b81dc6d"
version: "1.2.0-7"

cbuilder: {}

# build dependencies:
dep: "libx11"
dep: "libxext"
