source: "https://github.com/thom311/libnl/releases/download/libnl3_5_0/libnl-3.5.0.tar.gz"
hash: "352133ec9545da76f77e70ccb48c9d7e5324d67f6474744647a7ed382b5e05fa"
version: "3.5.0-7"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# build dependencies:
dep: "bison"
dep: "flex"
