source: "https://github.com/apple/cups/releases/download/v2.2.8/cups-2.2.8-source.tar.gz"
hash: "3968fc1d26fc48727508db1c1380e36c6694ab90177fd6920aec5f6cc73af9e4"
version: "2.2.8-4"

copy_to_builddir: true
in_tree_build: true

cbuilder: {
}

# build dependencies:
dep: "gzip"

build_step: {
  argv: "./configure"
  argv: "--prefix=${DISTRI_PREFIX}"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  argv: "V=1"
}

build_step: {
  argv: "make"
  argv: "install"
  argv: "BUILDROOT=${DISTRI_DESTDIR}"  # TODO: send patch upstream to make DESTDIR an alias for BUILDROOT
}

