source: "https://github.com/apple/cups/releases/download/v2.3.1/cups-2.3.1-source.tar.gz"
hash: "1bca9d89507e3f68cbc84482fe46ae8d5333af5bc2b9061347b2007182ac77ce"
version: "2.3.1-6"

writable_sourcedir: true
in_tree_build: true

cbuilder: {
}

# build dependencies:
dep: "gzip"

build_step: {
  argv: "./configure"
  argv: "--prefix=${DISTRI_PREFIX}"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  argv: "V=1"
}

build_step: {
  argv: "make"
  argv: "install"
  argv: "BUILDROOT=${DISTRI_DESTDIR}"  # TODO: send patch upstream to make DESTDIR an alias for BUILDROOT
}

