source: "https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-13.0.tar.xz"
hash: "961b23ca1acfd28f2bc87414c27bb40e12436efcf2158d29721b1e89f3f28057"
version: "13.0-13"

pull: {
  releases_url: "https://www.freedesktop.org/wiki/Software/PulseAudio/"
  release_regexp: "PulseAudio ([^ ]+)</a> has been released"
}

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)
ack_missing_dwarf: "TODO"

cbuilder: {
  extra_configure_flag: "--with-udev-rules-dir=${DISTRI_PREFIX}/lib/udev/rules.d"
  extra_configure_flag: "--enable-bluez5"
}

# build dependencies:
dep: "m4"
dep: "intltool"
dep: "libtool"
dep: "libcap"
dep: "libsndfile"
dep: "systemd"  # for udev
dep: "dbus"
dep: "glib"
dep: "bluez"
dep: "sbc"
