source: "https://github.com/rockdaboot/libpsl/releases/download/libpsl-0.21.0/libpsl-0.21.0.tar.gz"
hash: "41bd1c75a375b85c337b59783f5deb93dbb443fb0a52d257f403df7bd653ee12"
version: "0.21.0-8"

cbuilder: {}

# build dependencies:
dep: "python3"
