source: "https://github.com/pygobject/pycairo/releases/download/v1.19.1/pycairo-1.19.1.tar.gz"
hash: "2c143183280feb67f5beb4e543fd49990c28e7df427301ede04fc550d3562e84"
version: "1.19.1-8"

pythonbuilder: {}

# build dependencies:
dep: "cairo"
