source: "https://releases.pagure.org/xmlto/xmlto-0.0.28.tar.bz2"
hash: "1130df3a7957eb9f6f0d29e4aa1c75732a7dfb6d639be013859b5c7ec5421276"
version: "0.0.28-1"

cbuilder: {}

# build dependencies:

runtime_dep: "libxslt"
