source: "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.gz"
hash: "d418483bdd0000576c1370571121a6eb24582116db0b7bb2005e90e250eae418"
version: "2.7.1-6"
pull: {
  releases_url: "https://www.ruby-lang.org/en/downloads/"
}

# https://bugs.ruby-lang.org/issues/16836
cherry_pick: "pc-ldflags.patch"

cbuilder: {}

# build dependencies:
dep: "openssl"
