source: "https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.44.4/e2fsprogs-1.44.4.tar.xz"
hash: "ee03b2f2180614c5ae5f6dd2666f8808de61c3d8b37d22ba86cc6daea25be55a"
version: "1.44.4-6"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}
