source: "http://ftp.gnome.org/pub/gnome/sources/libnotify/0.7/libnotify-0.7.7.tar.xz"
hash: "9cb4ce315b2655860c524d46b56010874214ec27e854086c1a1d0260137efc04"
version: "0.7.7-7"

copy_to_builddir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# build dependencies:
dep: "gdk-pixbuf"
dep: "shared-mime-info"  # TODO: should be pulled in via gdk-pixbuf
dep: "gtk+"
dep: "mesa"  # TODO: should be pulled in via epoxy via gtk+
dep: "python3"
