source: "http://ftp.gnome.org/pub/gnome/sources/libnotify/0.7/libnotify-0.7.9.tar.xz"
hash: "66c0517ed16df7af258e83208faaf5069727dfd66995c4bbc51c16954d674761"
version: "0.7.9-11"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

mesonbuilder: {
  # TODO: build with manpages
  extra_meson_flag: "-Dman=false"
  extra_meson_flag: "-Dgtk_doc=false"
}

# build dependencies:
dep: "gdk-pixbuf"
dep: "shared-mime-info"  # TODO: should be pulled in via gdk-pixbuf
dep: "gtk+"
dep: "mesa"  # TODO: should be pulled in via epoxy via gtk+
dep: "python3"
dep: "libxslt"
dep: "gobject-introspection"
