source: "distri+gomod://github.com/junegunn/fzf@v0.0.0-20200424135655-e6d33f77da8c"
hash: "5fb5139f43473deb5ed5c63936d27740b28b3f3912b9e56c55c77c56f8c31c68"
version: "v0.0.0-20200424135655-e6d33f77da8c-9"

gobuilder: {}

# build dependencies:
dep: "go-github.com-gdamore-encoding"
dep: "go-github.com-gdamore-tcell"
dep: "go-github.com-gopherjs-gopherjs"
dep: "go-github.com-jtolds-gls"
dep: "go-github.com-lucasb--eyer-go--colorful"
dep: "go-github.com-mattn-go--isatty"
dep: "go-github.com-mattn-go--runewidth"
dep: "go-github.com-mattn-go--shellwords"
dep: "go-github.com-smartystreets-assertions"
dep: "go-github.com-smartystreets-goconvey"
dep: "go-golang.org-x-crypto"
dep: "go-golang.org-x-net"
dep: "go-golang.org-x-sys"
dep: "go-golang.org-x-text"
dep: "go-golang.org-x-tools"
dep: "go-golang.org-x-sync"
dep: "go-golang.org-x-xerrors"
dep: "go-github.com-DATA--DOG-go--sqlmock"
dep: "go-github.com-saracen-walker"
