source: "distri+gomod://github.com/junegunn/fzf@v0.0.0-20190719042446-65773882505b"
hash: "f0f038bbaf3e9b1a907e15045cccd562e6c52777ffe7d3101dca030c987afc15"
version: "v0.0.0-20190719042446-65773882505b-5"

gobuilder: {}

# build dependencies:
dep: "go-github.com-gdamore-encoding"
dep: "go-github.com-gdamore-tcell"
dep: "go-github.com-gopherjs-gopherjs"
dep: "go-github.com-jtolds-gls"
dep: "go-github.com-lucasb--eyer-go--colorful"
dep: "go-github.com-mattn-go--isatty"
dep: "go-github.com-mattn-go--runewidth"
dep: "go-github.com-mattn-go--shellwords"
dep: "go-github.com-smartystreets-assertions"
dep: "go-github.com-smartystreets-goconvey"
dep: "go-golang.org-x-crypto"
dep: "go-golang.org-x-net"
dep: "go-golang.org-x-sys"
dep: "go-golang.org-x-text"
dep: "go-golang.org-x-tools"
dep: "go-golang.org-x-sync"
dep: "go-github.com-DATA--DOG-go--sqlmock"
