source: "https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-2.4.0.tar.bz2"
hash: "b470eff9dd5b596edf078596b46a1f83c179449f051a469430afc15869db336f"
version: "2.4.0-7"

cbuilder: {
  extra_configure_flag: "--with-icu"
}

# build dependencies:
dep: "freetype"
dep: "glib"
dep: "icu"
