source: "https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.9.0.tar.bz2"
hash: "11eca62bf0ac549b8d6be55f4e130946399939cdfe7a562fdaee711190248b00"
version: "1.9.0-5"

cbuilder: {
  extra_configure_flag: "--with-icu"
}

# build dependencies:
dep: "freetype"
dep: "glib"
dep: "icu"
