source: "https://ftp.gnu.org/gnu/automake/automake-1.16.2.tar.xz"
hash: "ccc459de3d710e066ab9e12d2f119bd164a08c9341ca24ba22c9adaa179eedd0"
version: "1.16.2-7"

cbuilder: {}

cherry_pick: "0001-dirlist.patch"

# build dependencies:
dep: "perl"
dep: "autoconf"
