source: "https://ftp.gnu.org/gnu/automake/automake-1.16.tar.xz"
hash: "f98f2d97b11851cbe7c2d4b4eaef498ae9d17a3c2ef1401609b7b4ca66655b8a"
version: "1.16-4"

cbuilder: {}

cherry_pick: "0001-dirlist.patch"

# build dependencies:
dep: "perl"
dep: "autoconf"
