source: "https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz"
hash: "0382996d1ee6aafe59763426cf0139ffebe36984474d0ec4126dd1c40a8b3549"
version: "3.7.0"

cbuilder: <>

# TODO: file upstream bug: pkg-config invocation does not ignore CPATH
cherry_pick: "http://t.zekjur.net/py.patch"

# build dependencies:
dep: "zlib-1.2.11"
dep: "openssl-1.0.2p"
dep: "libffi-3.2.1"

build_step: <
  argv: "${ZI_SOURCEDIR}/configure"
  argv: "--prefix=${ZI_PREFIX}"
  argv: "--with-openssl=/ro/openssl-1.0.2p/buildoutput"
>

# https://bugs.python.org/issue34823
build_step: <
  argv: "ln"
  argv: "-s"
  argv: "/ro/libffi-3.2.1/buildoutput/lib64"
  argv: "/usr/"
>

build_step: <
  argv: "sed"
  argv: "-i"
  argv: "s,^#zlib,zlib,g"
  argv: "Modules/Setup"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "make -j8"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "DESTDIR=${ZI_DESTDIR} make install DESTDIR=${ZI_DESTDIR}"
>

install: <
  symlink: < oldname: "python3" newname: "bin/python" >
>
