source: "https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz"
hash: "0382996d1ee6aafe59763426cf0139ffebe36984474d0ec4126dd1c40a8b3549"
version: "3.7.0-5"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# TODO: file upstream bug: pkg-config invocation does not ignore CPATH
cherry_pick: "py.patch"

cherry_pick: "python-build-interpreter.patch"

extra_file: "Modules/Setup.local"

# build dependencies:
dep: "zlib"
dep: "openssl"
dep: "libffi"
dep: "ncurses"

build_step: {
  argv: "mkdir"
  argv: "Modules"
}

build_step: {
  argv: "cp"
  argv: "${DISTRI_SOURCEDIR}/Modules/Setup.local"
  argv: "Modules/Setup.local"
}

build_step: {
  argv: "${DISTRI_SOURCEDIR}/configure"
  argv: "--host=${DISTRI_CONFIGURE_HOST}"
  argv: "--build=x86_64-pc-linux-gnu"
  argv: "--prefix=${DISTRI_PREFIX}"
  argv: "--with-openssl=/ro/${DISTRI_RESOLVE:openssl}/out"
  argv: "--enable-shared"  # for building e.g. libxml2’s Python bindings
  argv: "--enable-ipv6"  # required to be set when cross-compiling
  argv: "ac_cv_file__dev_ptmx=yes"  # for cross-compiling
  argv: "ac_cv_file__dev_ptc=no"  # for cross-compiling
}

# https://bugs.python.org/issue34823
build_step: {
  argv: "ln"
  argv: "-s"
  argv: "/ro/${DISTRI_RESOLVE:libffi}/out/lib64"
  argv: "/usr/"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  # LD_LIBRARY_PATH needs to contain the build directory so that
  # $PYTHON_FOR_BUILD (./python) can locate libpython3.7m.so.1.0.
  argv: "LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH make -j${DISTRI_JOBS}"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  # LD_LIBRARY_PATH needs to contain the build directory so that
  # $PYTHON_FOR_BUILD (./python) can locate libpython3.7m.so.1.0.
  argv: "LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH DESTDIR=${DISTRI_DESTDIR} make install DESTDIR=${DISTRI_DESTDIR}"
}

install: {
  symlink: { oldname: "python3" newname: "bin/python" }
  symlink: { oldname: "python3-config" newname: "bin/python-config" }
}
