source: "https://xcb.freedesktop.org/dist/xcb-util-image-0.4.0.tar.bz2"
hash: "2db96a37d78831d643538dd1b595d7d712e04bdccf8896a5e18ce0f398ea2ffc"
version: "0.4.0-7"

cbuilder: {}

# build dependencies:
dep: "libxcb"
dep: "xorgproto"
dep: "xcb-util"
