source: "https://www.freedesktop.org/software/polkit/releases/polkit-0.116.tar.gz"
hash: "88170c9e711e8db305a12fdb8234fac5706c61969b94e084d0f117d8ec5d34b1"
version: "0.116-11"

extra_file: "polkit.sysusers"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {
  extra_configure_flag: "--with-systemdsystemunitdir=${prefix}/lib/systemd/system"
  extra_configure_flag: "--datadir=/ro/share"
  extra_configure_flag: "--datarootdir=/ro/share"
}

# build dependencies:
dep: "mozjs"
dep: "expat"
dep: "systemd"
dep: "intltool"
dep: "python3"
dep: "glib"

build_step: {
  argv: "mkdir"
  argv: "-p"
  argv: "/sys/fs/cgroup/systemd/"
}

build_step: {
  argv: "${DISTRI_SOURCEDIR}/configure"
  argv: "--prefix=${DISTRI_PREFIX}"
  argv: "--sysconfdir=/etc"
  argv: "--disable-dependency-tracking"
  argv: "--with-systemdsystemunitdir=${prefix}/lib/systemd/system"
  argv: "--datadir=/ro/share"
  argv: "--datarootdir=/ro/share"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  argv: "V=1"
}

build_step: {
  argv: "make"
  argv: "install"
  argv: "V=1"
  argv: "DESTDIR=${DISTRI_DESTDIR}"
}

install: {
  file: {
    srcpath: "polkit.sysusers"
    destpath: "lib/sysusers.d/polkit.conf"
  }
}
