source: "https://xorg.freedesktop.org/releases/individual/lib/libXdmcp-1.1.3.tar.bz2"
hash: "20523b44aaa513e17c009e873ad7bbc301507a3224c232610ce2e099011c6529"
version: "1.1.3-7"

cbuilder: {}

# build dependencies:
dep: "xorgproto"
