source: "http://deb.debian.org/debian/pool/main/x/xclip/xclip_0.13.orig.tar.gz"
hash: "ca5b8804e3c910a66423a882d79bf3c9450b875ac8528791fb60ec9de667f758"
version: "0.13-5"

writable_sourcedir: true  # for autoreconf
in_tree_build: true

cbuilder: {
  autoreconf: true
}

# build dependencies:
dep: "libx11"
dep: "libxmu"
