source: "distri+gomod://cloud.google.com/go@v0.34.0"
hash: "3f352837b121ec26371f8d816dc69f92b4bbcb56ef7be07fd785f6fde1446354"
version: "v0.34.0-5"

gomodbuilder: {}

# build dependencies:
dep: "binutils"  # for objcopy, this package contains ELF files
