source: "https://download.savannah.gnu.org/releases/freetype/freetype-2.9.1.tar.bz2"
hash: "db8d87ea720ea9d5edc5388fc7a0497bb11ba9fe972245e0f7f4c7e8b1e1e84d"
version: "2.9.1-4"

cbuilder: {
  extra_configure_flag: "--enable-freetype-config"  # grub2 uses this to locate freetype
}

# build dependencies:
