source: "https://ftp.gnu.org/gnu/grep/grep-3.4.tar.xz"
hash: "58e6751c41a7c25bfc6e9363a41786cff3ba5709cf11d5ad903cf7cce31cc3fb"
version: "3.4-4"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {
  # TODO: libpcre static linking fails due to undeclared pthread dependency
  extra_configure_flag: "--disable-perl-regexp"
}
