# https://xorg.freedesktop.org/releases/individual/app/xauth-1.0.10.tar.bz2 is slow
source: "http://t.zekjur.net/xauth-1.0.10.tar.bz2"
hash: "5afe42ce3cdf4f60520d1658d2b17face45c74050f39af45dccdc95e73fafc4d"
version: "1.0.10-6"

cbuilder: {}

# build dependencies:
dep: "libx11"
dep: "libxext"
dep: "libxmu"
