source: "https://cpan.metacpan.org/authors/id/G/GA/GAAS/File-Listing-6.04.tar.gz"
hash: "1e0050fcd6789a2179ec0db282bf1e90fb92be35d1171588bd9c47d52d959cf5"
version: "6.04"

perlbuilder: <>

# build dependencies:
dep: "perl-HTTP-Date-6.02"
