source: "https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz"
hash: "67c74d94196b153b774ab9f89b2fa6c6ba79352407037c8c14d5aeb334e959cd"
version: "0.51.0-2"

cbuilder: <>

# build dependencies:
dep: "perl"
dep: "perl-XML-Parser"

runtime_dep: "perl"
runtime_dep: "gettext"
runtime_dep: "perl-XML-Parser"
