source: "https://xorg.freedesktop.org/releases/individual/lib/libX11-1.6.9.tar.bz2"
hash: "9cc7e8d000d6193fa5af580d50d689380b8287052270f5bb26a5fb6b58b2bed1"
version: "1.6.9-8"

cbuilder: {
  # malloc(0) returns a non-NULL pointer. Specify explicitly so that configure
  # does not need to run a test program, which is not possible when
  # cross-compiling.
  extra_configure_flag: "--disable-malloc0returnsnull"
}

# build dependencies:
dep: "xorgproto-amd64"
dep: "xtrans-amd64"
dep: "libxcb"

runtime_dep: "xorgproto-amd64"  # TODO: remove once pkgconfig detection works
