source: "https://xorg.freedesktop.org/releases/individual/lib/libX11-1.6.6.tar.bz2"
hash: "65fe181d40ec77f45417710c6a67431814ab252d21c2e85c75dd1ed568af414f"
version: "1.6.6"

cbuilder: <>

# build dependencies:
dep: "xorgproto"
dep: "xtrans"
dep: "libxcb"

runtime_dep: "xorgproto-2018.4" # TODO: remove once pkgconfig detection works
