source: "https://xorg.freedesktop.org/releases/individual/app/xset-1.2.4.tar.bz2"
hash: "e4fd95280df52a88e9b0abc1fee11dcf0f34fc24041b9f45a247e52df941c957"
version: "1.2.4-2"

cbuilder: <>

# build dependencies:
dep: "libx11"
dep: "libxmu"
