source: "https://github.com/martinh/libconfuse/releases/download/v3.2.2/confuse-3.2.2.tar.xz"
hash: "a9240b653d02e8cfc52db48e8c4224426e528e1faa09b65e8ca08a197fad210b"
version: "3.2.2"

cbuilder: <>

# build dependencies:
