source: "https://cpan.metacpan.org/authors/id/O/OA/OALDERS/Net-HTTP-6.19.tar.gz"
hash: "52b76ec13959522cae64d965f15da3d99dcb445eddd85d2ce4e4f4df385b2fc4"
version: "6.19-7"

perlbuilder: {}

# build dependencies:
dep: "perl-URI"
