source: "https://github.com/jirka-h/haveged/archive/v1.9.8.tar.gz"
hash: "99aa1996c6e39ea2459cfc37addfb8b1eecc63f3a2b6da9db17b22e76b6851ae"
version: "v1.9.8-7"

cbuilder: {
  extra_configure_flag: "--enable-init=service.forking"
  extra_configure_flag: "--enable-initdir=${DISTRI_PREFIX}/lib/systemd/system"
}

# build dependencies:
