source: "https://mirrors.edge.kernel.org/pub/linux/utils/boot/dracut/dracut-048.tar.xz"
hash: "0750d6b71b7f95d8dfa338404372bfeb0e5c30e7fe2a21ba55c6dbf3dbcf6a79"
version: "048-7"

cherry_pick: "exec.patch"
cherry_pick: "emergency.patch"
cherry_pick: "dm-uuid.patch"
cherry_pick: "gcc_s.patch"
cherry_pick: "elf-interp.patch"

cbuilder: <
  copy_to_builddir: true
>

# build dependencies:
dep: "kmod"
dep: "elfutils"

runtime_dep: "pkg-config"
runtime_dep: "findutils"
runtime_dep: "cpio"
runtime_dep: "tar"
runtime_dep: "gzip"
runtime_dep: "sed"
runtime_dep: "grep"
runtime_dep: "binutils"  # for strip(1) at generate-time
runtime_dep: "coreutils" # for sleep(1) at init-time
