source: "https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.2.10.tar.bz2"
hash: "799dd37a86a1448732e339bd20440f4f5ee6e69755f6fd7a73ee8af30840c915"
version: "2.2.10"

cbuilder: <>

# build dependencies:
dep: "libgpg-error-1.32"
dep: "libgcrypt-1.8.3"
dep: "libassuan-2.5.1"
dep: "libksba-1.3.5"
dep: "npth-1.6"
