source: "https://gnupg.org/ftp/gcrypt/gnupg/gnupg-2.2.20.tar.bz2"
hash: "04a7c9d48b74c399168ee8270e548588ddbe52218c337703d7f06373d326ca30"
version: "2.2.20-7"

cbuilder: {}

# build dependencies:
dep: "libgpg-error"
dep: "libgcrypt"
dep: "libassuan"
dep: "libksba"
dep: "npth"
