source: "distriroot://distri1-1.tar.gz"
hash: ""
version: "native-16"

gobuilder: <
  install: "./cmd/distri"
  import_path: "distri1"
  # Used as /init before the dynamic linker is available:
  go_env: "CGO_ENABLED=0"
>

# build dependencies:
dep: "go-cloud.google.com-go"
dep: "go-github.com-client9-misspell"
dep: "go-github.com-golang-gddo"
dep: "go-github.com-golang-glog"
dep: "go-github.com-golang-lint"
dep: "go-github.com-golang-mock"
dep: "go-github.com-golang-protobuf"
dep: "go-github.com-google-go--cmp"
dep: "go-github.com-google-renameio"
# dep: "go-github.com-jacobsa-fuse" # replaced with ./fuse
dep: "go-github.com-kisielk-gotool"
dep: "go-github.com-kylelemons-godebug"
dep: "go-github.com-lpar-gzipped"
dep: "go-golang.org-x-exp"
dep: "go-golang.org-x-crypto"
dep: "go-golang.org-x-lint"
dep: "go-golang.org-x-net"
dep: "go-golang.org-x-oauth2"
dep: "go-golang.org-x-sync"
dep: "go-golang.org-x-sys"
dep: "go-golang.org-x-text"
dep: "go-golang.org-x-tools"
dep: "go-gonum.org-v1-gonum"
dep: "go-gonum.org-v1-netlib"
dep: "go-google.golang.org-appengine"
dep: "go-google.golang.org-genproto"
dep: "go-google.golang.org-grpc"
dep: "go-honnef.co-go-tools"
dep: "go-golang.org-x-xerrors"
dep: "go-github.com-orcaman-writerseeker"
dep: "go-github.com-BurntSushi-toml"
dep: "go-github.com-google-go--github-v27"
dep: "go-github.com-google-go--querystring"
