source: "distriroot://distri1-1.tar.gz"
hash: ""
version: "native-44"

gobuilder: {
  install: "./cmd/distri ./cmd/minitrd ./cmd/distri-installer"
  import_path: "distri1"
  # Used as /init before the dynamic linker is available:
  go_env: "CGO_ENABLED=0"
}

# build dependencies:
dep: "go-cloud.google.com-go"
dep: "go-github.com-client9-misspell"
dep: "go-github.com-golang-gddo"
dep: "go-github.com-golang-glog"
dep: "go-github.com-golang-lint"
dep: "go-github.com-golang-mock"
dep: "go-github.com-golang-protobuf"
dep: "go-github.com-google-go--cmp"
dep: "go-github.com-google-renameio"
dep: "go-github.com-jacobsa-fuse"
dep: "go-github.com-kisielk-gotool"
dep: "go-github.com-kylelemons-godebug"
dep: "go-github.com-lpar-gzipped"
dep: "go-golang.org-x-exp"
dep: "go-golang.org-x-crypto"
dep: "go-golang.org-x-lint"
dep: "go-golang.org-x-net"
dep: "go-golang.org-x-oauth2"
dep: "go-golang.org-x-sync"
dep: "go-golang.org-x-sys"
dep: "go-golang.org-x-text"
dep: "go-golang.org-x-tools"
dep: "go-gonum.org-v1-gonum"
dep: "go-gonum.org-v1-netlib"
dep: "go-google.golang.org-appengine"
dep: "go-google.golang.org-genproto"
dep: "go-google.golang.org-grpc"
dep: "go-honnef.co-go-tools"
dep: "go-golang.org-x-xerrors"
dep: "go-github.com-orcaman-writerseeker"
dep: "go-github.com-protocolbuffers-txtpbfmt"
dep: "go-github.com-BurntSushi-toml"
dep: "go-github.com-google-go--github-v27"
dep: "go-github.com-google-go--querystring"
dep: "go-github.com-cavaliercoder-go--cpio"
dep: "go-github.com-klauspost-compress"
dep: "go-github.com-klauspost-pgzip"
dep: "go-github.com-s--urbaniak-uevent"
dep: "go-github.com-lib-pq"
dep: "go-golang.org-x-mod"
dep: "go-github.com-census--instrumentation-opencensus--proto"
dep: "go-github.com-cncf-udpa-go"
dep: "go-github.com-envoyproxy-go--control--plane"
dep: "go-github.com-envoyproxy-protoc--gen--validate"
dep: "go-github.com-prometheus-client_model"
dep: "go-google.golang.org-protobuf"

runtime_dep: "kbd"
runtime_dep: "dosfstools"  # for mkfs.fat

install: {
  file: {
    srcpath: "pkg/mod/distri1@v0/zsh/site-functions/_distri"
    destpath: "share/zsh/site-functions/_distri"
  }

  file: {
    srcpath: "pkg/mod/distri1@v0/zsh/zshrc"
    destpath: "../etc/zshrc"
  }
}
