source: "https://cpan.metacpan.org/authors/id/M/MA/MATTN/Devel-CheckLib-1.13.tar.gz"
hash: "24adfd908705dfac4bb320711763f37126b75cf54b3566c2c27c7cdef9c429a8"
version: "1.13"

cbuilder: <>

# build dependencies:
dep: "perl-5.28.0"

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "cp -T -ar ${ZI_SOURCEDIR}/ ."
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "perl Makefile.PL INSTALL_BASE=${ZI_PREFIX}"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "make -j8"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "make install DESTDIR=${ZI_DESTDIR}"
>
