source: "https://xorg.freedesktop.org/releases/individual/lib/libfontenc-1.1.4.tar.bz2"
hash: "2cfcce810ddd48f2e5dc658d28c1808e86dcf303eaff16728b9aa3dbc0092079"
version: "1.1.4-7"

cbuilder: {}

# build dependencies:
dep: "zlib"
dep: "xorgproto"
