source: "https://xorg.freedesktop.org/releases/individual/lib/libXfont2-2.0.4.tar.bz2"
hash: "6d151b3368e5035efede4b6264c0fdc6662c1c99dbc2de425e3480cababc69e6"
version: "2.0.4-7"

cbuilder: {}

# build dependencies:
dep: "freetype"
dep: "zlib"
dep: "xorgproto"
dep: "xtrans"
dep: "libfontenc"
