source: "https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/File-Next-1.18.tar.gz"
hash: "f900cb39505eb6e168a9ca51a10b73f1bbde1914b923a09ecd72d9c02e6ec2ef"
version: "1.18-7"

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

# build dependencies:
dep: "perl"

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "perl Makefile.PL INSTALL_BASE=${DISTRI_PREFIX} EXPATLIBPATH=/ro/${DISTRI_RESOLVE:expat}/out/lib PREREQ_FATAL=true"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "make -j${DISTRI_JOBS}"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "make install DESTDIR=${DISTRI_DESTDIR}"
}
