source: "https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-7.8p1.tar.gz"
hash: "1a484bb15152c183bb2514e112aa30dd34138c3cfb032eee5490a66c507144ca"
version: "7.8p1"

cherry_pick: "config.patch"
cherry_pick: "service.patch"

# build dependencies:
dep: "zlib-1.2.11"
dep: "openssl-1.0.2p"
dep: "pam-1.3.1"

dep: "strace-4.24"

cbuilder: <
  extra_configure_flag: "OPENSSL_SEEDS_ITSELF=yes"
  extra_configure_flag: "--sysconfdir=/etc/ssh"
  extra_configure_flag: "--with-privsep-path=${ZI_PREFIX}/var/empty"
  extra_configure_flag: "--with-pam"
>

install: <
  systemd_unit: "${ZI_SOURCEDIR}/ssh.service"
>
