source: "http://freedesktop.org/software/pulseaudio/pavucontrol/pavucontrol-3.0.tar.xz"
hash: "b3d2ea5a25fc88dcee80c396014f72df1b4742f8cfbbc5349c39d64a0d338890"
version: "3.0-2"

cbuilder: <>

# build dependencies:
dep: "mesa" # TODO: should be pulled in via epoxy via gtk+
dep: "gtkmm"
dep: "libsigc++"
dep: "libcanberra"
dep: "pulseaudio"
dep: "intltool"
