source: "distri+gomod://github.com/google/go-github/v27@v27.0.6"
hash: "d52c30dfc0fc028710082452567e30b8191c0dd0dacc2aba1691af9c96dc6a5c"
version: "v27.0.6-4"

gomodbuilder: {}

# build dependencies:
