source: "https://xorg.freedesktop.org/releases/individual/lib/libXi-1.7.9.tar.bz2"
hash: "c2e6b8ff84f9448386c1b5510a5cf5a16d788f76db018194dacdc200180faf45"
version: "1.7.9-2"

cbuilder: <>

# build dependencies:
dep: "libx11"
dep: "libxext"
dep: "libxfixes"
