source: "https://curl.haxx.se/download/curl-7.61.1.tar.bz2"
hash: "a308377dbc9a16b2e994abd55455e5f9edca4e31666f8f8fcfe7a1a4aea419b9"
version: "7.61.1-2"

cbuilder: <
  extra_configure_flag: "--with-ca-path=/etc/ssl/certs"
  extra_configure_flag: "--with-gnutls"
>

# build dependencies:
dep: "gnutls"

runtime_dep: "ca-certificates"

install: <
  # This package is provided for compatibility with closed-source
  # software that links against libcurl-gnutls.so, so there will
  # not be any static linking.
  delete: "lib/libcurl.a"
  delete: "lib/libcurl.la"
  delete: "lib/pkgconfig/libcurl.pc"
  delete: "share/aclocal/libcurl.m4"
  delete: "lib/libcurl.so"
  delete: "lib/libcurl.so.4"

  symlink: <
    oldname: "libcurl-gnutls.so.4.5.0"
    newname: "lib/libcurl-gnutls.so"
  >

  symlink: <
    oldname: "libcurl-gnutls.so.4.5.0"
    newname: "lib/libcurl-gnutls.so.4"
  >

  rename: <
    oldname: "lib/libcurl.so.4.5.0"
    newname: "lib/libcurl-gnutls.so.4.5.0"
  >
>
