source: "https://xorg.freedesktop.org/releases/individual/lib/libXcursor-1.2.0.tar.bz2"
hash: "3ad3e9f8251094af6fe8cb4afcf63e28df504d46bfa5a5529db74a505d628782"
version: "1.2.0-10"

cbuilder: {
  extra_configure_flag: "--with-icondir=/usr/share/icons"
}

# build dependencies:
dep: "libx11"
dep: "libxfixes"
dep: "libxrender"
