source: "https://sourceware.org/elfutils/ftp/0.179/elfutils-0.179.tar.bz2"
hash: "25a545566cbacaa37ae6222e58f1c48ea4570f53ba991886e2f5ce96e22a23a2"
version: "0.179-4"

cbuilder: {
  extra_configure_flag: "--disable-debuginfod"
}

# build dependencies:
dep: "zlib"
dep: "m4"
