source: "http://ftp.gnome.org/pub/GNOME/sources/pango/1.42/pango-1.42.4.tar.xz"
hash: "1d2b74cd63e8bd41961f2f8d952355aa0f9be6002b52c8aa7699d9f5da597c9d"
version: "1.42.4-3"

cbuilder: {}

# build dependencies:
dep: "cairo"
dep: "harfbuzz"
dep: "fontconfig"
dep: "glib"
dep: "fribidi"
dep: "python3"
dep: "gobject-introspection"
