source: "https://mirrors.edge.kernel.org/pub/linux/utils/kbd/kbd-2.0.4.tar.xz"
hash: "5fd90af6beb225a9bb9b9fb414c090fba53c9a55793e172f508cd43652e59a88"
version: "2.0.4-7"

cbuilder: {
  extra_configure_flag: "--datadir=/ro/share"
}

# build dependencies:
dep: "gzip"
