source: "https://mirrors.edge.kernel.org/pub/linux/utils/kbd/kbd-2.2.0.tar.xz"
hash: "21a1bc5f6fb3b18ce9fdd717e4533368060a3182a39c7155eaf7ec0f5f83e9f7"
version: "2.2.0-8"

cbuilder: {
  extra_configure_flag: "--datadir=/ro/share"
}

# build dependencies:
dep: "gzip"
