source: "https://download.gnome.org/sources/NetworkManager/1.12/NetworkManager-1.12.2.tar.xz"
hash: "6be06ff93a05f3ee4da9e58e4a0d974eef245c08b6f02b00a9e44154c9801a26"
version: "1.12.2"

cbuilder: <
  extra_configure_flag: "--disable-ppp"
  extra_configure_flag: "--disable-ovs"
  extra_configure_flag: "--localstatedir=/var" # TODO: make default
>

# https://salsa.debian.org/utopia-team/network-manager/commit/c0f037a4c260bd455d13f755d068b4d9e3f9a551
cherry_pick: "available.patch"

# TODO: patch ProtectSystem=false, as otherwise sub-directories under /run cannot be created

# build dependencies:
dep: "systemd-239" # for udev
dep: "intltool-0.51.0"
dep: "nss-3.39"
dep: "iptables-1.6.2"
dep: "curl-7.61.1"
dep: "libndp-1.7"
dep: "readline-7.0"
dep: "ncurses-6.1"
dep: "python3-3.7.0"
