source: "https://download.gnome.org/sources/NetworkManager/1.22/NetworkManager-1.22.6.tar.xz"
hash: "bc9923fc9bc41148ebadc786b62208247590f3cd3c246826c192106ecf84c564"
version: "1.22.6-9"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {
  extra_configure_flag: "--disable-ppp"
  extra_configure_flag: "--disable-ovs"
  extra_configure_flag: "--localstatedir=/var"  # TODO: make default
}

# TODO: patch ProtectSystem=false, as otherwise sub-directories under /run cannot be created

# build dependencies:
dep: "systemd"  # for udev
dep: "intltool"
dep: "nss"
dep: "iptables"
dep: "curl"
dep: "libndp"
dep: "readline"
dep: "ncurses"
dep: "python3"

# Without wpa_supplicant, WiFi devices cannot be managed without a clear error message
runtime_dep: "wpa_supplicant"
