source: "https://ftp.gnome.org/pub/gnome/sources/gtk+/2.24/gtk+-2.24.32.tar.xz"
hash: "b6c8a93ddda5eabe3bfee1eb39636c9a03d2a56c7b62828b359bf197943c582e"
version: "2.24.32-4"

cbuilder: {}

# build dependencies:
dep: "gdk-pixbuf"
dep: "shared-mime-info"  # TODO: bring in via gdk-pixbuf
dep: "pango"
dep: "cairo"
dep: "atk"
dep: "libxinerama"
dep: "libxi"
dep: "libepoxy"
dep: "mesa"
dep: "atk"
dep: "at-spi2-atk"
dep: "python3"
dep: "perl"
dep: "libx11"
dep: "libxrender"
