source: "https://i3wm.org/downloads/i3-4.18.tar.bz2"
hash: "1fbb58d580e8f8afb7e807fe71164d6003e454d71f22eea5eb3256c73c7a6537"
version: "4.18-10"

cbuilder: {
  # adds -g to the compilation flags
  extra_configure_flag: "--enable-debug=info"
}

# build dependencies:
dep: "perl"
dep: "libev"
dep: "startup-notification"
dep: "libxcb"
dep: "xcb-util"
dep: "xcb-util-cursor"
dep: "xcb-util-keysyms"
dep: "xcb-util-wm"
dep: "xcb-util-xrm"
dep: "libxkbcommon"
dep: "yajl2"
dep: "pcre"
dep: "pango"
dep: "fribidi"
dep: "harfbuzz"
dep: "libx11"
dep: "fontconfig"
