source: "https://i3wm.org/downloads/i3-4.17.tar.bz2"
hash: "4ebe13e47d6b88fb31d0cb1492e9d968d96aafcd834b8d3cae18b684e7ac18fd"
version: "4.17-3"

cbuilder: <>

# build dependencies:
dep: "perl"
dep: "libev"
dep: "startup-notification"
dep: "libxcb"
dep: "xcb-util"
dep: "xcb-util-cursor"
dep: "xcb-util-keysyms"
dep: "xcb-util-wm"
dep: "xcb-util-xrm"
dep: "libxkbcommon"
dep: "yajl2"
dep: "pcre"
dep: "pango"
dep: "fribidi"
dep: "harfbuzz"
dep: "libx11"
dep: "fontconfig"
