source: "https://i3wm.org/downloads/i3-4.15.tar.bz2"
hash: "217d524d1fbc85ae346b25f6848d1b7bcd2c23184ec88d29114bf5a621385326"
version: "4.15"

cbuilder: <>

# build dependencies:
dep: "perl"
dep: "libev"
dep: "startup-notification"
dep: "libxcb"
dep: "xcb-util"
dep: "xcb-util-cursor"
dep: "xcb-util-keysyms"
dep: "xcb-util-wm"
dep: "xcb-util-xrm"
dep: "libxkbcommon"
dep: "yajl2"
dep: "pcre"
dep: "pango"
dep: "fribidi"
dep: "harfbuzz"
dep: "libx11"
dep: "fontconfig"
