source: "distri+source://python-setuptools"
hash: "125855e597d95dd0711078eaaa615523d39791a57c2de3f96805e5d0c64fa9b9"
version: "41.0.1-6"

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

dep: "python2.7"

# build dependencies:
build_step: {
  argv: "python2.7"
  argv: "setup.py"
  argv: "install"
  argv: "--prefix=${DISTRI_PREFIX}"
  argv: "--root=${DISTRI_DESTDIR}"
}
