source: "https://xorg.freedesktop.org/releases/individual/lib/libXxf86vm-1.1.4.tar.bz2"
hash: "afee27f93c5f31c0ad582852c0fb36d50e4de7cd585fcf655e278a633d85cd57"
version: "1.1.4-8"

cbuilder: {}

# build dependencies:
dep: "xorgproto"
dep: "libx11"
dep: "libxext"
