source: "https://downloads.sourceforge.net/project/dejavu/dejavu/2.37/dejavu-fonts-ttf-2.37.tar.bz2"
hash: "fa9ca4d13871dd122f61258a80d01751d603b4d3ee14095d65453b4e846e17d7"
version: "2.37-5"

cbuilder: {}

# build dependencies:

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/share/fonts/truetype/dejavu; mkdir -p $d; cp ${DISTRI_SOURCEDIR}/ttf/* $d/"
}
