source: "https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Cookies-6.08.tar.gz"
hash: "49ebb73576eb41063c04bc079477df094496deec805ae033f3be338c23c3af59"
version: "6.08-7"

perlbuilder: {}

# build dependencies:
dep: "perl-HTTP-Date"
dep: "perl-HTTP-Message"
dep: "perl-URI"

