source: "http://files.itstool.org/itstool/itstool-2.0.6.tar.bz2"
hash: "6233cc22726a9a5a83664bf67d1af79549a298c23185d926c3677afa917b92a9"
version: "2.0.6-8"

cbuilder: {}

# build dependencies:
dep: "python3"
dep: "libxml2"

# TODO: should this package use the pythonbuilder? it uses autotools, but is
# implemented in python.
runtime_dep: "python3"
runtime_dep: "libxml2"
