source: "https://ftp.gnu.org/gnu/gawk/gawk-5.1.0.tar.xz"
hash: "cf5fea4ac5665fd5171af4716baab2effc76306a9572988d5ba1078f196382bd"
version: "5.1.0-5"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}
