source: "https://download.gnome.org/sources/cairomm/1.12/cairomm-1.12.0.tar.xz"
hash: "a54ada8394a86182525c0762e6f50db6b9212a2109280d13ec6a0b29bfd1afe6"
version: "1.12.0-3"

cbuilder: <>

# build dependencies:
dep: "libsigc++"
dep: "cairo"
