source: "https://ftp.gnu.org/gnu/binutils/binutils-2.34.tar.xz"
hash: "f00b0e8803dc9bab1e2165bd568528135be734df3fabf8d0161828cd56028952"
version: "2.34-4"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

dep: "perl"
dep: "texinfo"

build_step: {
  argv: "${DISTRI_SOURCEDIR}/configure"
  argv: "--prefix=${DISTRI_PREFIX}"
  #  argv: "LDFLAGS=-static"
}

build_step: {
  argv: "make"
  argv: "configure-host"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  #  argv: "LDFLAGS=-all-static"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "DESTDIR=${DISTRI_DESTDIR} make install"
}
