source: "https://ftp.gnu.org/gnu/binutils/binutils-2.31.tar.xz"
hash: "231036df7ef02049cdbff0681f4575e571f26ea8086cf70c2dcd3b6c0f4216bf"
version: "2.31-3"

copy_to_builddir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

build_step: {
  argv: "${DISTRI_SOURCEDIR}/configure"
  argv: "--prefix=${DISTRI_PREFIX}"
  #  argv: "LDFLAGS=-static"
}

build_step: {
  argv: "make"
  argv: "configure-host"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  #  argv: "LDFLAGS=-all-static"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "DESTDIR=${DISTRI_DESTDIR} make install"
}
