source: "https://sourceware.org/pub/lvm2/LVM2.2.03.09.tgz"
hash: "c03a8b8d5c03ba8ac54ebddf670ae0d086edac54a6577e8c50721a8e174eb975"
version: "2.03.09-8"

writable_sourcedir: true
in_tree_build: true

cbuilder: {
  extra_configure_flag: "--enable-udev_rules"
  extra_configure_flag: "--enable-udev_sync"
}

# build dependencies:
dep: "libaio"
dep: "which"
dep: "systemd"  # to pick up new version
dep: "libudev"
