source: "https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Message-6.22.tar.gz"
hash: "970efd151b81c95831d2a5f9e117f8032b63a1768cd2cd3f092ad634c85175c3"
version: "6.22-7"

perlbuilder: {}

# build dependencies:
dep: "perl-Encode-Locale"
dep: "perl-HTTP-Date"
dep: "perl-IO-HTML"
dep: "perl-LWP-MediaTypes"
dep: "perl-Try-Tiny"
dep: "perl-URI"
