source: "https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Message-6.18.tar.gz"
hash: "d060d170d388b694c58c14f4d13ed908a2807f0e581146cef45726641d809112"
version: "6.18"

perlbuilder: <>

# build dependencies:
dep: "perl-Encode-Locale-1.05"
dep: "perl-HTTP-Date-6.02"
dep: "perl-IO-HTML-1.001"
dep: "perl-LWP-MediaTypes-6.02"
dep: "perl-Try-Tiny-0.30"
dep: "perl-URI-1.74"
