source: "https://xorg.freedesktop.org/releases/individual/lib/libXau-1.0.9.tar.bz2"
hash: "ccf8cbf0dbf676faa2ea0a6d64bcc3b6746064722b606c8c52917ed00dcb73ec"
version: "1.0.9-7"

cbuilder: {}

# build dependencies:
dep: "xorgproto"
runtime_dep: "xorgproto"  # TODO: remove once pkgconfig detection works
