source: "https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.9.5.tar.xz"
hash: "a4bea37ecb9a3fb5c0c8ef18c2f7eeaf8ccbcfec91f72f3bccfc6bf72a3e3902"
version: "2.9.5"

cbuilder: <
  copy_to_builddir: true
  extra_configure_flag: "--without-tcltk"
  extra_make_flag: "NO_INSTALL_HARDLINKS=1" # TODO: remove once our SquashFS writer supports hard links
>

# build dependencies:
dep: "perl"
dep: "gettext"
dep: "tar"
