source: "https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-20200316.tar.gz"
hash: "b442ad49e0002c6ff8443f4745810fe10d4cd6df43a7ce5e37ac40057c75ac13"
version: "20200316-7"
pull: {
  releases_url: "https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git"
  # TODO: remove release_regexp once we switched from a snapshot to a release
  release_regexp: "linux-firmware-([0-9]+).tar.gz"
}

cbuilder: {}

# build dependencies:

build_step: {
  argv: "make"
  argv: "-C"
  argv: "${DISTRI_SOURCEDIR}"
  argv: "install"
  argv: "V=1"
  argv: "DESTDIR=${DISTRI_DESTDIR}/${DISTRI_PREFIX}"
}

# TODO: split this out into a separate package once distri can do that
build_step: {
  argv: "rm"
  argv: "-rf"
  argv: "${DISTRI_DESTDIR}/${DISTRI_PREFIX}/lib/firmware/netronome"
}
