source: "https://cdn.kernel.org/pub/linux/kernel/firmware/linux-firmware-20200421.tar.xz"
hash: "6dd7cba25d694c031f65529b9027cc8faaffaddfae70a4e3b58c2e4a0af3bfa8"
version: "20200421-8"
pull: {
  releases_url: "https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git"
  # TODO: remove release_regexp once we switched from a snapshot to a release
  release_regexp: "linux-firmware-([0-9]+).tar.gz"
}

cbuilder: {}

# build dependencies:

build_step: {
  argv: "make"
  argv: "-C"
  argv: "${DISTRI_SOURCEDIR}"
  argv: "install"
  argv: "V=1"
  argv: "DESTDIR=${DISTRI_DESTDIR}/${DISTRI_PREFIX}"
}

# TODO: split this out into a separate package once distri can do that
build_step: {
  argv: "rm"
  argv: "-rf"
  argv: "${DISTRI_DESTDIR}/${DISTRI_PREFIX}/lib/firmware/netronome"
}
