source: "https://ftp.isc.org/isc/bind9/9.14.1/bind-9.14.1.tar.gz"
hash: "c3c7485d900a03271a9918a071c123e8951871a219f4c1c4383e37717f11db48"
version: "9.14.1"

cbuilder: <
  extra_configure_flag: "--without-python"  # fails even with dep: "python3" _and_ dep: "python2.7"
>

# build dependencies:
dep: "openssl"
dep: "perl"
