source: "https://download.gnome.org/sources/network-manager-applet/1.8/network-manager-applet-1.8.24.tar.xz"
hash: "118bbb8a5027634b62e8b45b16ceafce74441529c99bf230654e3bec38f9fbbf"
version: "1.8.24-14"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

mesonbuilder: {
  extra_meson_flag: "-Dwwan=false"
  extra_meson_flag: "-Dselinux=false"
  extra_meson_flag: "-Dteam=false"
  extra_meson_flag: "-Dmobile_broadband_provider_info=false"
  extra_meson_flag: "-Dgcr=false"
  extra_meson_flag: "-Dintrospection=false"
  extra_meson_flag: "-Dgtk_doc=false"
}

# build dependencies:
dep: "intltool"
dep: "iso-codes"
dep: "networkmanager"
dep: "libsecret"
dep: "libnotify"
dep: "shared-mime-info"  # TODO: should be pulled in via gdk-pixbuf
dep: "gtk+"
dep: "mesa"  # TODO: should be pulled in via epoxy via gtk+
dep: "libgudev"
