source: "https://xorg.freedesktop.org/releases/individual/lib/xtrans-1.4.0.tar.bz2"
hash: "377c4491593c417946efcd2c7600d1e62639f7a8bbca391887e2c4679807d773"
version: "1.4.0-7"

cbuilder: {}

# build dependencies:

install: {
  # TODO: remove once both share/pkgconfig (arch-indep) and lib/pkgconfig (arch-dep) are union overlays
  symlink: { oldname: "../share/pkgconfig" newname: "lib/pkgconfig" }
}
