source: "https://releases.pagure.org/libaio/libaio-0.3.112.tar.gz"
hash: "ab0462f2c9d546683e5147b1ce9c195fe95d07fac5bf362f6c01637955c3b492"
version: "0.3.112-7"

writable_sourcedir: true
in_tree_build: true

cbuilder: {
}

# build dependencies:

build_step: {
  argv: "make"
  argv: "prefix=${DISTRI_DESTDIR}/${DISTRI_PREFIX}"
  argv: "install"
}
