source: "https://downloads.sourceforge.net/project/psmisc/psmisc/psmisc-23.2.tar.xz"
hash: "4b7cbffdc9373474da49b85dc3457ae511c43dc7fa7d94513fe06f89dcb87880"
version: "23.2-9"

cherry_pick: "dirstamp.patch"  # https://gitlab.com/psmisc/psmisc/merge_requests/17

# build dependencies:
dep: "ncurses"

cbuilder: {}
