source: "https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-SAX-Base-1.09.tar.gz"
hash: "66cb355ba4ef47c10ca738bd35999723644386ac853abbeb5132841f5e8a2ad0"
version: "1.09-2"

perlbuilder: <>

# build dependencies:
