source: "https://downloads.sourceforge.net/project/enlightenment/imlib2-src/1.5.1/imlib2-1.5.1.tar.bz2"
hash: "fa4e57452b8843f4a70f70fd435c746ae2ace813250f8c65f977db5d7914baae"
version: "1.5.1"

cbuilder: <>

# build dependencies:
dep: "freetype"
dep: "libx11"
dep: "libxext"
dep: "libpng"
dep: "tiff"
#dep: "bzip2"
dep: "giflib"
dep: "libjpeg-turbo"
