source: "https://xorg.freedesktop.org/releases/individual/lib/libXdamage-1.1.4.tar.bz2"
hash: "7c3fe7c657e83547f4822bfde30a90d84524efb56365448768409b77f05355ad"
version: "1.1.4"

cbuilder: <>

# build dependencies:
#dep: "damageproto-1.2.1"
#dep: "xextproto-7.3.0"
dep: "libx11-1.6.6"
dep: "libxfixes-5.0.3"
