source: "https://data.iana.org/time-zones/releases/tzdb-2019c.tar.lz"
hash: "0f9ebf1d04c21d95f8ca2371f342133503388d215e5e2599ae6213b4aeeb3118"
version: "2019c-9"
pull: {
  release_regexp: "tzdb-([0-9a-z]+)\\.tar\\.lz"
}

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

# build dependencies:

build_step: {
  argv: "make"
  argv: "install"
  argv: "USRDIR="
  argv: "TOPDIR=${DISTRI_PREFIX}"
  argv: "DESTDIR=${DISTRI_DESTDIR}"
}
