source: "https://data.iana.org/time-zones/releases/tzdb-2020a.tar.lz"
hash: "99a6e52363fdb9a386671f0dbcd76e38403aab8c5a7b35e4c8d66c60ec6c70af"
version: "2020a-10"
pull: {
  release_regexp: "tzdb-([0-9a-z]+)\\.tar\\.lz"
}

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

# build dependencies:

build_step: {
  argv: "make"
  argv: "install"
  argv: "USRDIR="
  argv: "TOPDIR=${DISTRI_PREFIX}"
  argv: "DESTDIR=${DISTRI_DESTDIR}"
}
