source: "https://downloads.sourceforge.net/project/libpng/libpng16/1.6.37/libpng-1.6.37.tar.xz"
hash: "505e70834d35383537b6491e7ae8641f1a4bed1876dbfe361201fc80868d88ca"
version: "1.6.37-7"

cbuilder: {}

# build dependencies:
dep: "zlib"
