source: "https://sourceforge.net/projects/libpng/files/libpng-1.6.37.tar.xz"
hash: "fd04e57e0d91d4d61a0440c0ee926facfea552a39ed37817fcbd35dbc9708662"
version: "1.6.37-7"

cbuilder: {}

# build dependencies:
dep: "zlib"
