source: "http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.22.tar.bz2"
hash: "e94628e9bcfa0adb1115d83649f898d6edb4baced44f5d5b769c2eeb8b95addd"
version: "9.22"

cbuilder: <>

# build dependencies:
dep: "perl-5.28.0"
dep: "libx11-1.6.6"

# TODO: to work around g++ issue where #include_next <stdlib.h> from cstdlib.h won’t find the header
build_step: <
  argv: "ln"
  argv: "-s"
  argv: "/ro/glibc-2.27/buildoutput/include"
  argv: "/usr/include"
>

build_step: <
  argv: "${ZI_SOURCEDIR}/configure"
  argv: "--prefix=${ZI_PREFIX}"
>

build_step: <
  argv: "make"
  argv: "-j8"
  argv: "V=1"
>

build_step: <
  argv: "make"
  argv: "install"
  argv: "DESTDIR=${ZI_DESTDIR}"
  argv: "PREFIX=${ZI_PREFIX}"
>
