source: "https://ftp.gnu.org/gnu/tar/tar-1.32.tar.xz"
hash: "d0d3ae07f103323be809bc3eac0dcc386d52c5262499fe05511ac4788af1fdd8"
version: "1.32-4"

cbuilder: {
  extra_configure_flag: "FORCE_UNSAFE_CONFIGURE=1"  # TODO: remove once we run as temporary uid/gid
}
