source: "https://mirrors.edge.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.33.tar.xz"
hash: "08edeaba2757021aeec45c4eeec52566675e0e0f5d4f057284d729e04f2643d6"
version: "2.33-4"

writable_sourcedir: true  # modifies source
in_tree_build: true

cbuilder: {
}

# build dependencies:
dep: "perl"
dep: "gperf"  # NOTE that libcap fails silently without gperf :(

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  argv: "prefix=${DISTRI_PREFIX}"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "DESTDIR=${DISTRI_DESTDIR} make install prefix=${DISTRI_PREFIX} lib=lib RAISE_SETFCAP=no"
}
