source: "https://mirrors.edge.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.25.tar.xz"
hash: "693c8ac51e983ee678205571ef272439d83afe62dd8e424ea14ad9790bc35162"
version: "2.25"

cbuilder: <>

# build dependencies:
dep: "perl"
dep: "gperf" # NOTE that libcap fails silently without gperf :(

build_step: <
  argv: "make"
  argv: "-C"
  argv: "${ZI_SOURCEDIR}"
  argv: "-j8"
  argv: "prefix=${ZI_PREFIX}"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "DESTDIR=${ZI_DESTDIR} make -C ${ZI_SOURCEDIR} install prefix=${ZI_PREFIX} lib=lib RAISE_SETFCAP=no"
>
