source: "https://download.gnome.org/sources/vala/0.48/vala-0.48.5.tar.xz"
hash: "a3d4c0e0dadd4c64962205d2f448af72d6bd8c67919d984012b8a41b843ec757"
version: "0.48.5-7"

cbuilder: {}

# build dependencies:
dep: "flex"
dep: "bison"
dep: "graphviz"
dep: "glib"
