source: "empty://"
version: "native-6"

dep: "bash"
dep: "sed"
dep: "coreutils"
# dep: "glibc-2.27"
# dep: "hello-1"
# dep: "libmnl-1.0.4"
# dep: "systemd-239"
# dep: "util-linux-2.32"
# dep: "libcap-2.25"
# dep: "meson-0.47.1"
# dep: "python3-3.7.0"
# dep: "gcc-libs-8.2.0"
dep: "gcc"
dep: "binutils"
dep: "linux"
dep: "glibc"
dep: "strace"
dep: "libcap"
# dep: "binutils-2.31"
# dep: "grep-3.1"
# dep: "ninja-1.8.2"
# dep: "zlib-1.2.11" # TODO: for python. remove once runtime-deps are installed
# dep: "openssl-1.0.2p" # TODO: for python. remove once runtime-deps are installed
# dep: "libffi-3.2.1" # TODO: for python. remove once runtime-deps are installed

dep: "patchelf"
dep: "systemd"

build_step: {
  argv: "/ro/bin/sh"
  argv: "-i"
}

