source: "https://github.com/iputils/iputils/archive/s20190709.tar.gz"
hash: "a15720dd741d7538dd2645f9f516d193636ae4300ff7dbc8bfca757bf166490a"
version: "20190709-7"

cherry_pick: "setuid.patch"

mesonbuilder: {
  extra_meson_flag: "-DBUILD_MANS=false"
}

# build dependencies:
dep: "libcap"
dep: "libidn2"
dep: "iconv"  # TODO: remove this libidn2 dep
dep: "libunistring"  # TODO: remove this libidn2 dep
dep: "nettle"
dep: "libxslt"
