source: "https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.4/wxWidgets-3.0.4.tar.bz2"
hash: "96157f988d261b7368e5340afa1a0cad943768f35929c22841f62c25b17bf7f0"
version: "3.0.4-9"

cbuilder: {
  # TODO: build without this
  extra_configure_flag: "--with-gtk=3"
}

# build dependencies:
dep: "gtk+"
dep: "mesa"
dep: "glu"
dep: "webkitgtk"
dep: "tiff"

install: {
  # XXX: kicad’s cmake locates libraries by looking for lib%s.so:
  symlink: { oldname: "libwx_baseu-3.0.so.0" newname: "lib/libwx_baseu-3.0.so" }
  symlink: { oldname: "libwx_baseu_net-3.0.so.0" newname: "lib/libwx_baseu_net-3.0.so" }
  symlink: { oldname: "libwx_baseu_xml-3.0.so.0" newname: "lib/libwx_baseu_xml-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_adv-3.0.so.0" newname: "lib/libwx_gtk3u_adv-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_aui-3.0.so.0" newname: "lib/libwx_gtk3u_aui-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_core-3.0.so.0" newname: "lib/libwx_gtk3u_core-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_gl-3.0.so.0" newname: "lib/libwx_gtk3u_gl-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_html-3.0.so.0" newname: "lib/libwx_gtk3u_html-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_propgrid-3.0.so.0" newname: "lib/libwx_gtk3u_propgrid-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_qa-3.0.so.0" newname: "lib/libwx_gtk3u_qa-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_ribbon-3.0.so.0" newname: "lib/libwx_gtk3u_ribbon-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_richtext-3.0.so.0" newname: "lib/libwx_gtk3u_richtext-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_stc-3.0.so.0" newname: "lib/libwx_gtk3u_stc-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_xrc-3.0.so.0" newname: "lib/libwx_gtk3u_xrc-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_webview-3.0.so.0" newname: "lib/libwx_gtk3u_webview-3.0.so" }
  symlink: { oldname: "libwx_gtk3u_media-3.0.so.0" newname: "lib/libwx_gtk3u_media-3.0.so" }
}

