source: "https://github.com/rhboot/efivar/releases/download/37/efivar-37.tar.bz2"
hash: "3c67feb93f901b98fbb897d5ca82931a6698b5bcd6ac34f0815f670d77747b9f"
version: "37-6"

writable_sourcedir: true
in_tree_build: true
ack_missing_dwarf: "TODO"

cbuilder: {}

cherry_pick: "0001-disable-Werror.patch"

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "export DESTDIR=${DISTRI_DESTDIR} PREFIX=${DISTRI_PREFIX} LIBDIR=${DISTRI_PREFIX}/lib; make -j${DISTRI_JOBS} && make install"
}
