source: "https://download.gnome.org/sources/glibmm/2.58/glibmm-2.58.0.tar.xz"
hash: "d34189237b99e88228e6f557f7d6e62f767fe356f395a244f5ad0e486254b645"
version: "2.58.0-5"

copy_to_builddir: true
in_tree_build: true

cbuilder: {
}

# build dependencies:
dep: "libsigc++"
dep: "glib"
