source: "https://download.gnome.org/sources/glibmm/2.58/glibmm-2.58.1.tar.xz"
hash: "6e5fe03bdf1e220eeffd543e017fd2fb15bcec9235f0ffd50674aff9362a85f0"
version: "2.58.1-7"

writable_sourcedir: true
in_tree_build: true

cbuilder: {
}

# build dependencies:
dep: "libsigc++"
dep: "glib"
