source: "https://www.gnupg.org/ftp/gcrypt/gnutls/v3.5/gnutls-3.5.19.tar.xz"
hash: "1936eb64f03aaefd6eb16cef0567457777618573826b94d03376bb6a4afadc44"
version: "3.5.19-7"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {
  extra_configure_flag: "--without-p11-kit"
}

# build dependencies:
dep: "nettle"
dep: "libtasn1"
dep: "libunistring"
dep: "zlib"
