source: "https://github.com/libfuse/sshfs/releases/download/sshfs-3.7.0/sshfs-3.7.0.tar.xz"
hash: "6e7e86831f3066b356e7f16e22f1b8a8f177fda05146f6a5eb821c2fd0541c34"
version: "3.7.0-8"

mesonbuilder: {}

# build dependencies:
dep: "fuse"
dep: "glib"
