source: "https://xorg.freedesktop.org/releases/individual/app/xhost-1.0.8.tar.bz2"
hash: "a2dc3c579e13674947395ef8ccc1b3763f89012a216c2cc6277096489aadc396"
version: "1.0.8-6"

cbuilder: {}

# build dependencies:
dep: "xorgproto"
dep: "libx11"
dep: "libxmu"
