source: "https://ftp.gnu.org/gnu/nettle/nettle-3.5.1.tar.gz"
hash: "75cca1998761b02e16f2db56da52992aef622bf55a3b45ec538bc2eedadc9419"
version: "3.5.1-7"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

# build dependencies:
dep: "m4"
dep: "gmp"

cbuilder: {}
