source: "https://www.tcpdump.org/release/libpcap-1.9.1.tar.gz"
hash: "635237637c5b619bcceba91900666b64d56ecb7be63f298f601ec786ce087094"
version: "1.9.1-7"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# build dependencies:
dep: "flex"
dep: "m4"  # TODO: make this a runtime_dep of flex
dep: "bison"
