source: "https://www.tcpdump.org/release/tcpdump-4.9.3.tar.gz"
hash: "2cd47cb3d460b6ff75f4a9940f594317ad456cfbf2bd2c8e5151e16559db6410"
version: "4.9.3-7"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# build dependencies:
dep: "libpcap"
