source: "https://download.gnome.org/sources/gtkmm/3.24/gtkmm-3.24.2.tar.xz"
hash: "6d71091bcd1863133460d4188d04102810e9123de19706fb656b7bb915b4adc3"
version: "3.24.2-11"

cbuilder: {}

# build dependencies:
dep: "gtk+"
dep: "mesa"  # TODO: should be pulled in via epoxy via gtk+
dep: "pangomm"
dep: "cairomm"
dep: "atkmm"
