source: "https://www.openssl.org/source/openssl-1.1.1e.tar.gz"
hash: "694f61ac11cb51c9bf73f54e771ff6022b0327a43bbdfa1b2f19de1662a6dcbe"
version: "1.1.1e-4"
pull: {
  release_regexp: "openssl-([0-9.a-z]+).tar.gz"
}

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

# build dep:
dep: "perl"

build_step: {
  argv: "./config"
  argv: "--prefix=${DISTRI_PREFIX}"
  argv: "shared"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  # TODO: -j${DISTRI_JOBS}
  argv: "make install DESTDIR=${DISTRI_DESTDIR} INSTALLTOP=${DISTRI_PREFIX}"
}
