source: "https://www.openssl.org/source/openssl-1.0.2p.tar.gz"
hash: "50a98e07b1a89eb8f6a99477f262df71c6fa7bef77df4dc83025a2845c827d00"
version: "1.0.2p-3"
pull: {
  release_regexp: "openssl-([0-9.a-z]+).tar.gz"
}

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

# build dep:
dep: "perl"

build_step: {
  argv: "./config"
  argv: "--prefix=${DISTRI_PREFIX}"
  argv: "shared"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "make install INSTALL_PREFIX=${DISTRI_DESTDIR} INSTALLTOP=${DISTRI_PREFIX}"
}
