source: "https://www.openssl.org/source/openssl-1.1.1g.tar.gz"
hash: "ddb04774f1e32f0c49751e21b67216ac87852ceb056b75209af2443400636d46"
version: "1.1.1g-5"
pull: {
  release_regexp: "openssl-([0-9.a-z]+).tar.gz"
}

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

# build dep:
dep: "perl"

build_step: {
  argv: "./config"
  argv: "--prefix=${DISTRI_PREFIX}"
  argv: "shared"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  # TODO: -j${DISTRI_JOBS}
  argv: "make install DESTDIR=${DISTRI_DESTDIR} INSTALLTOP=${DISTRI_PREFIX}"
}
