source: "https://downloads.sourceforge.net/project/libjpeg-turbo/2.0.4/libjpeg-turbo-2.0.4.tar.gz"
hash: "33dd8547efd5543639e890efbf2ef52d5a21df81faf41bb940657af916a23406"
version: "2.0.4-8"
pull: {
  releases_url: "https://sourceforge.net/p/libjpeg-turbo/activity/?page=0&limit=100"
}

cmakebuilder: {}

# build dependencies:
dep: "nasm"
