source: "https://download.savannah.gnu.org/releases/lzip/lzip-1.21.tar.gz"
hash: "e48b5039d3164d670791f9c5dbaa832bf2df080cb1fbb4f33aa7b3300b670d8b"
version: "1.21-5"

cbuilder: {}

# build dependencies:
