source: "distri+gomod://github.com/lucasb-eyer/go-colorful@v1.0.3"
hash: "d8f566a355059099fccfc9455bf4952585ba866bf841e4c69673c839a41aff75"
version: "v1.0.3-5"

gomodbuilder: {}

# build dependencies:
