source: "distri+source://binutils"
hash: "f00b0e8803dc9bab1e2165bd568528135be734df3fabf8d0161828cd56028952"
version: "2.34-6"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

build_step: {
  argv: "${DISTRI_SOURCEDIR}/configure"
  argv: "--prefix=${DISTRI_PREFIX}"
  argv: "--target=i686-pc-linux-gnu"
  # https://bugs.launchpad.net/ubuntu/+source/binutils/+bug/1508564
  argv: "--with-sysroot=/"
  #  argv: "LDFLAGS=-static"
}

build_step: {
  argv: "make"
  argv: "configure-host"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  #  argv: "LDFLAGS=-all-static"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "DESTDIR=${DISTRI_DESTDIR} make install"
}

# install: <
#   symlink: < oldname: "as" newname: "bin/i686-elf-as" >
# >
