source: "http://www.freedesktop.org/software/startup-notification/releases/startup-notification-0.12.tar.gz"
hash: "3c391f7e930c583095045cd2d10eb73a64f085c7fde9d260f2652c7cb3cfbe4a"
version: "0.12"

cbuilder: <>

# build dependencies:
dep: "pkg-config-0.29.2"
dep: "libx11-1.6.6"
dep: "xcb-util-0.4.0"
