source: "https://xorg.freedesktop.org/releases/individual/lib/libICE-1.0.10.tar.bz2"
hash: "6f86dce12cf4bcaf5c37dddd8b1b64ed2ddf1ef7b218f22b9942595fb747c348"
version: "1.0.10-7"

cbuilder: {}

# build dependencies:
dep: "xorgproto"
dep: "xtrans"
