source: "https://xorg.freedesktop.org/releases/individual/lib/libXt-1.2.0.tar.bz2"
hash: "b31df531dabed9f4611fc8980bc51d7782967e2aff44c4105251a1acb5a77831"
version: "1.2.0-8"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# build dependencies:
dep: "xorgproto"
dep: "libx11"
dep: "libice"
dep: "libsm"
