source: "https://github.com/shadow-maint/shadow/releases/download/4.6/shadow-4.6.tar.xz"
hash: "0998c8d84242a231ab0acb7f8613927ff5bcff095f8aa6b79478893a03f05583"
version: "4.6"

cbuilder: <>

# build dependencies:

# TODO: patch out selinux line from /etc/pam.d/login until pam package builds selinux
