source: "https://github.com/shadow-maint/shadow/releases/download/4.8.1/shadow-4.8.1.tar.xz"
hash: "a3ad4630bdc41372f02a647278a8c3514844295d36eefe68ece6c3a641c1ae62"
version: "4.8.1-9"

cbuilder: {}

cherry_pick: "0001-remove-selinux.patch"
