source: "https://xorg.freedesktop.org/releases/individual/lib/libXScrnSaver-1.2.3.tar.bz2"
hash: "f917075a1b7b5a38d67a8b0238eaab14acd2557679835b154cf2bca576e89bf8"
version: "1.2.3-2"

cbuilder: {}

# build dependencies:
dep: "libx11"
dep: "libxext"
