source: "https://ftp.gnu.org/gnu/autogen/autogen-5.18.7.tar.xz"
hash: "a7a580a5e18931cb341b255cec2fee2dfd81bea5ddbf0d8ad722703e19aaa405"
version: "5.18.7"

cbuilder: <>

# build dependencies:
dep: "guile-2.0.14"
dep: "which-2.21"
dep: "perl-5.28.0"
