source: "http://ftp.gnome.org/pub/gnome/sources/libsecret/0.18/libsecret-0.18.8.tar.xz"
hash: "3bfa889d260e0dbabcf5b9967f2aae12edcd2ddc9adc365de7a5cc840c311d15"
version: "0.18.8-8"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {
  # I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
  extra_configure_flag: "--disable-manpages"
}

# build dependencies:
dep: "intltool"
dep: "libxslt"
dep: "libgcrypt"
dep: "python3"
dep: "glib"
