source: "empty://"
version: "8.2.0-2" # must match gcc

cbuilder: <>

dep: "gcc-i686"

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/lib; mkdir -p $d; cp -d /ro/gcc-i686-amd64-8.2.0/out/i686-pc-linux-gnu/lib/{libgcc_s.so,libstdc++,libgomp}* /ro/gcc-i686-amd64-8.2.0/out/lib/gcc/i686-pc-linux-gnu/8.2.0/crt* $d"
>

# Delete the .la files as they contain full paths. If we don’t do this, packages
# such as pcre will end up with a gcc dependency instead of a gcc-libs
# dependency.
build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/lib; rm $d/*.la"
>
