source: "https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.32/util-linux-2.32.1.tar.xz"
hash: "86e6707a379c7ff5489c218cfaf1e3464b0b95acf7817db0bc5f179e356a67b2"
version: "2.32.1-7"

cbuilder: {
  extra_configure_flag: "--disable-wall"  # TODO: requires “chgrp tty <bin>”, which does not work in a user namespace
  extra_configure_flag: "--enable-login"  # e.g. for getty
}

# build dependencies:
dep: "pam"
