source: "https://kent.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.bz2"
hash: "df27ec3ff24671f80b29e6ab1c4971059c14ac3db95406884fc26574631ba8d5"
version: "5.1.4-1"

cbuilder: <>

# build dependencies:
