source: "https://netfilter.org/projects/libnftnl/files/libnftnl-1.1.1.tar.bz2"
hash: "5d6a65413f27ec635eedf6aba033f7cf671d462a2afeacc562ba96b19893aff2"
version: "1.1.1-3"

# build dependencies:
dep: "libmnl"

cbuilder: {}
