source: "https://xorg.freedesktop.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.25.tar.bz2"
hash: "fec6c25a8d3931bd9afca49a1653b0fa222c85610502d7b77699bb61262934b2"
version: "2.25-1"

cbuilder: <>

# build dependencies:
dep: "xorgproto"
dep: "libx11"
dep: "intltool"
