source: "https://xorg.freedesktop.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.29.tar.bz2"
hash: "1d4175278bf06000683656763a8b1d3282c61a314b6db41260c8efe92d621802"
version: "2.29-8"

cbuilder: {}

# build dependencies:
dep: "xorgproto"
dep: "libx11"
dep: "intltool"
dep: "python3"
