source: "https://ftp.acc.umu.se/pub/GNOME/sources/pygobject/3.31/pygobject-3.31.4.tar.xz"
hash: "d17a3ee2fc71fb51b512fdf81520bfc0a85cd5811214b4ae917f20151df78e45"
version: "3.31.4-8"

mesonbuilder: {}

# build dependencies:
dep: "gobject-introspection"
dep: "gettext"
dep: "cairo"
dep: "pycairo"
