source: "http://www.greenwoodsoftware.com/less/less-551.tar.gz"
hash: "e8544662b3373bf1467489f2338f65c419f6c3b996cb29befc0c424bacd56751"
version: "551-11"
pull: {
  release_regexp: "released version is less-(\\d+)"
}

cbuilder: {
  extra_configure_flag: "--with-regex=pcre"
}

# build dependencies:
dep: "ncurses"
dep: "pcre"
