source: "http://www.greenwoodsoftware.com/less/less-530.tar.gz"
hash: "503f91ab0af4846f34f0444ab71c4b286123f0044a4964f1ae781486c617f2e2"
version: "530-5"

cbuilder: <
  extra_configure_flag: "--with-regex=pcre"
>

# build dependencies:
dep: "ncurses"
dep: "pcre"
