source: "http://www.greenwoodsoftware.com/less/less-551.tar.gz"
hash: "ff165275859381a63f19135a8f1f6c5a194d53ec3187f94121ecd8ef0795fe3d"
version: "551-12"
pull: {
  release_regexp: "released version is less-(\\d+)"
}

cbuilder: {
  extra_configure_flag: "--with-regex=pcre"
}

# build dependencies:
dep: "ncurses"
dep: "pcre"
