source: "https://github.com/hughsie/libxmlb/archive/0.1.5.tar.gz"
hash: "d42ed89600b6ce42b4aeac4a9293339ee8d7c00fe80d2699f3af2771a846b99d"
version: "0.1.5"

mesonbuilder: <
  extra_meson_flag: "-Dgtkdoc=false"
>

# build dependencies:
dep: "gobject-introspection"
dep: "gettext"
