source: "https://github.com/hughsie/libxmlb/archive/0.1.15.tar.gz"
hash: "fa29b6bbf7b91107da6f157e8f7903d176b0cf04bcb0ba1ab64cb38b19d09a19"
version: "0.1.15-8"

mesonbuilder: {
  extra_meson_flag: "-Dgtkdoc=false"
}

# build dependencies:
dep: "gobject-introspection"
dep: "gettext"
