source: "https://xorg.freedesktop.org/releases/individual/lib/libXpm-3.5.9.tar.bz2"
hash: "8add01029cab0598ca86e01a2f7781a636f74b757abe6b50ba61b2a6e2fd621e"
version: "3.5.9-8"

cbuilder: {}

# build dependencies:
dep: "libx11"
dep: "gettext"
