source: "http://freedesktop.org/~hadess/shared-mime-info-1.10.tar.xz"
hash: "c625a83b4838befc8cafcd54e3619946515d9e44d63d61c4adf7f5513ddfbebf"
version: "1.10"

cbuilder: <>

# build dependencies:
dep: "intltool-0.51.0"
dep: "perl-5.28.0" # TODO: bring in via intltool
dep: "perl-XML-Parser-2.44" # TODO: bring in via intltool
dep: "gettext-0.19.8.1"
dep: "libxml2-2.9.8"

build_step: <
  argv: "${ZI_SOURCEDIR}/configure"
  argv: "--prefix=${ZI_PREFIX}"
>

build_step: <
  argv: "make"
  argv: "-j1" # TODO: build fails with -j8
  argv: "V=1"
>

build_step: <
  argv: "make"
  argv: "install"
  argv: "DESTDIR=${ZI_DESTDIR}"
  argv: "PREFIX=${ZI_PREFIX}"
>

install: <
  symlink: < oldname: "../share/pkgconfig" newname: "lib/pkgconfig" >
>
