source: "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.5.2.tar.xz"
hash: "24f5f383b0337374f160723bcf3bf679c75cb5bd3fd0824a56998e47c04ef99e"
version: "5.5.2-12"

copy_to_builddir: true

cbuilder: {
}

cherry_pick: "config.patch"
cherry_pick: "suspend-amistry.patch"

# build dependencies:
dep: "bison"
dep: "flex"
dep: "m4"  # TODO: make m4 a runtime dep of flex
dep: "elfutils"
dep: "bc"
dep: "openssl"
dep: "perl"
dep: "gzip"
dep: "kmod"
dep: "rsync"

build_step: {
  argv: "make"
  argv: "olddefconfig"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  argv: "V=1"
  argv: "WERROR=0"
  argv: "KBUILD_BUILD_HOST=distri0"
}

# The linux makefile does not seem to create the install destination directory:
build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "mkdir -p ${DISTRI_DESTDIR}${DISTRI_PREFIX}"
}

build_step: {
  argv: "make"
  argv: "install"
  argv: "INSTALL_PATH=${DISTRI_DESTDIR}${DISTRI_PREFIX}"
}

build_step: {
  argv: "make"
  argv: "modules_install"
  argv: "INSTALL_MOD_PATH=${DISTRI_DESTDIR}${DISTRI_PREFIX}"
}

build_step: {
  argv: "make"
  argv: "headers_install"
  argv: "INSTALL_HDR_PATH=${DISTRI_DESTDIR}${DISTRI_PREFIX}"
}
