source: "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.1.9.tar.xz"
hash: "58c9eca99c3dd2fff5b559302996c985c3f3f2aad0b99b2172a61c4df7122a79"
version: "5.1.9-5"

cbuilder: <
  copy_to_builddir: true
>

cherry_pick: "config.patch"

# build dependencies:
dep: "bison"
dep: "flex"
dep: "m4" # TODO: make m4 a runtime dep of flex
dep: "elfutils"
dep: "bc"
dep: "openssl"
dep: "perl"
dep: "gzip"
dep: "kmod"

build_step: <
  argv: "make"
  argv: "-C"
  argv: "${DISTRI_SOURCEDIR}"
  argv: "olddefconfig"
>

build_step: <
  argv: "make"
  argv: "-C"
  argv: "${DISTRI_SOURCEDIR}"
  argv: "-j8"
  argv: "V=1"
  argv: "WERROR=0"
  argv: "KBUILD_BUILD_HOST=distri0"
>

# The linux makefile does not seem to create the install destination directory:
build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "mkdir -p ${DISTRI_DESTDIR}${DISTRI_PREFIX}"
>

build_step: <
  argv: "make"
  argv: "-C"
  argv: "${DISTRI_SOURCEDIR}"
  argv: "install"
  argv: "INSTALL_PATH=${DISTRI_DESTDIR}${DISTRI_PREFIX}"
>

build_step: <
  argv: "make"
  argv: "-C"
  argv: "${DISTRI_SOURCEDIR}"
  argv: "modules_install"
  argv: "INSTALL_MOD_PATH=${DISTRI_DESTDIR}${DISTRI_PREFIX}"
>

build_step: <
  argv: "make"
  argv: "-C"
  argv: "${DISTRI_SOURCEDIR}"
  argv: "headers_install"
  argv: "INSTALL_HDR_PATH=${DISTRI_DESTDIR}${DISTRI_PREFIX}"
>
