source: "distri+source://glibc"
hash: "cb2d64fb808affff30d8a99a85de9d2aa67dc2cbac4ae99af4500d6cfea2bda7"
version: "2.31-7"

#cherry_pick: "ldd.patch" # TODO: figure out why RTLDLIST gets the wrong value

cbuilder: {
  extra_configure_flag: "--build=x86_64-unknown-linux-gnu"
  extra_configure_flag: "--host=i686-pc-linux-gnu"
  extra_configure_flag: "--with-headers=/ro/linux-i686-amd64-4.18.7/out/include"
  # Contrary to what is stated in ld.so(8), glibc does not seem to search /lib
  # and /usr/lib (or /lib64 and /usr/lib64, respectively), resulting in the
  # nsswitch mechanism not finding e.g. libnss_myhostname.so. Hence, we tell
  # glibc explicitly to search /ro/lib:
  extra_make_flag: "user-defined-trusted-dirs=/ro/lib"
}

# build dependencies:
dep: "bison"
dep: "m4"  # TODO: remove once m4 is declared a runtime-dep of bison
dep: "gzip"
dep: "gcc-i686-c"
dep: "binutils-i686-amd64"
dep: "linux-i686-amd64"
dep: "python3"
