# stick with 2.27 for the time being:
# https://bugzilla.redhat.com/show_bug.cgi?id=1573342
source: "https://ftp.gnu.org/gnu/glibc/glibc-2.27.tar.gz"
hash: "881ca905e6b5eec724de7948f14d66a07d97bdee8013e1b2a7d021ff5d540522"
version: "2.27"

# source: "https://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.bz2"
# hash: "da9e45260c0cd3dbf6a585082a602521092ae7b3ecb17092cd7347603ef1e2cb"
# version: "2.28"

#cherry_pick: "ldd.patch" # TODO: figure out why RTLDLIST gets the wrong value

cbuilder: <
  extra_configure_flag: "--build=x86_64-unknown-linux-gnu"
  extra_configure_flag: "--host=i686-pc-linux-gnu"
  extra_configure_flag: "--with-headers=/ro/linux-i686-amd64-4.18.7/out/include"
  # Contrary to what is stated in ld.so(8), glibc does not seem to search /lib
  # and /usr/lib (or /lib64 and /usr/lib64, respectively), resulting in the
  # nsswitch mechanism not finding e.g. libnss_myhostname.so. Hence, we tell
  # glibc explicitly to search /ro/lib:
  extra_make_flag: "user-defined-trusted-dirs=/ro/lib"
>

# build dependencies:
dep: "bison"
dep: "m4" # TODO: remove once m4 is declared a runtime-dep of bison
dep: "gzip"
dep: "gcc-i686-c"
dep: "binutils-i686-amd64"
dep: "linux-i686-amd64"
