source: "https://ftp.gnome.org/pub/gnome/sources/gdk-pixbuf/2.38/gdk-pixbuf-2.38.0.tar.xz"
hash: "dd50973c7757bcde15de6bcd3a6d462a445efd552604ae6435a0532fbbadae47"
version: "2.38.0-7"

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

# build dependencies:
dep: "meson"
dep: "shared-mime-info"
dep: "libpng"
dep: "libjpeg-turbo"
# TODO: mlib?
# TODO: tiff?
dep: "gobject-introspection"
dep: "libx11"
dep: "gettext"
dep: "libxslt"
dep: "glib"

# e.g. gdk-pixbuf-csource requires MIME data to load PNG files
runtime_dep: "shared-mime-info"

build_step: {
  argv: "mkdir"
  argv: "-p"
  argv: "/usr/share"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "mkdir build"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "meson --prefix=${DISTRI_PREFIX} build . -Dinstalled_tests=false -Dman=false"
}

# kludge: the LD_LIBRARY_PATH change is required because we patched rpath handling out of meson.
build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "(cd build && LD_LIBRARY_PATH=$PWD/gdk-pixbuf:$PWD/gobject:$PWD/glib:$LD_LIBRARY_PATH ninja -j ${DISTRI_JOBS} -v)"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "(cd build && DESTDIR=${DISTRI_DESTDIR} ninja -j ${DISTRI_JOBS} -v install)"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "ln -s /ro/${DISTRI_FULLNAME}/ro/${DISTRI_FULLNAME}/out/* /ro/${DISTRI_FULLNAME}/out/ && ${DISTRI_PREFIX}/bin/gdk-pixbuf-query-loaders > ${DISTRI_DESTDIR}/${DISTRI_PREFIX}/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
}
