source: "https://ftp.gnome.org/pub/gnome/sources/gdk-pixbuf/2.38/gdk-pixbuf-2.38.0.tar.xz"
hash: "dd50973c7757bcde15de6bcd3a6d462a445efd552604ae6435a0532fbbadae47"
version: "2.38.0"

cbuilder: <>

# build dependencies:
dep: "meson"
dep: "shared-mime-info"
dep: "libpng"
dep: "libjpeg-turbo"
# TODO: mlib?
# TODO: tiff?
dep: "gobject-introspection"
dep: "libx11"
dep: "gettext"
dep: "libxslt"

dep: "strace"

# e.g. gdk-pixbuf-csource requires MIME data to load PNG files
runtime_dep: "shared-mime-info"

build_step: <
  argv: "mkdir"
  argv: "-p"
  argv: "/usr/share"
>

build_step: <
  argv: "ln"
  argv: "-s"
  argv: "/ro/shared-mime-info-amd64-1.10/out/share/mime"
  argv: "/usr/share/mime"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "meson --prefix=${ZI_PREFIX} . ${ZI_SOURCEDIR} -Dinstalled_tests=false -Dman=false"
>

# kludge: the LD_LIBRARY_PATH change is required because we patched rpath handling out of meson.
build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "LD_LIBRARY_PATH=$PWD/gdk-pixbuf:$PWD/gobject:$PWD/glib:$LD_LIBRARY_PATH ninja -v"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "DESTDIR=${ZI_DESTDIR} ninja -v install"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "ln -s /ro/gdk-pixbuf-amd64-2.38.0/ro/gdk-pixbuf-amd64-2.38.0/out/* /ro/gdk-pixbuf-amd64-2.38.0/out/ && ${ZI_PREFIX}/bin/gdk-pixbuf-query-loaders > ${ZI_DESTDIR}/${ZI_PREFIX}/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
>
