source: "https://github.com/tmux/tmux/releases/download/3.1/tmux-3.1.tar.gz"
hash: "979bf38db2c36193de49149aaea5c540d18e01ccc27cf76e2aff5606bd186722"
version: "3.1-6"

writable_sourcedir: true
in_tree_build: true

cbuilder: {
}

dep: "libevent"
dep: "ncurses"
