source: "https://xcb.freedesktop.org/dist/libxcb-1.13.1.tar.bz2"
hash: "a89fb7af7a11f43d2ce84a844a4b38df688c092bf4b67683aef179cdf2a647c4"
version: "1.13.1-8"

pull: {
  # libxcb-1.1.90.1.tar.bz2 is not valid semver, but newer releases are
  # TODO: ask upstream for a commitment to semver
  force_semver: true
}

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# build dependencies:
dep: "python3-amd64"
dep: "xcb-proto-amd64"
dep: "libpthread-stubs"
dep: "libxau"
dep: "xorgproto-amd64"

runtime_dep: "libpthread-stubs"  # TODO: remove once pkgconfig detection works
