source: "https://invisible-mirror.net/archives/ncurses/ncurses-6.1.tar.gz"
hash: "aa057eeeb4a14d470101eff4597d5833dcef5965331be3528c08d99cebaa0d17"
version: "6.1-8"

cbuilder: {
  # TODO: enable C++ support?
  extra_configure_flag: "--without-cxx-binding"
  extra_configure_flag: "--disable-stripping"

  # TODO: does not result in any .pc files?
  extra_configure_flag: "--enable-pc-files"

  # install headers to /usr/include/curses.h instead of /usr/include/ncurses (the latter is not picked up by psmisc)
  extra_configure_flag: "--enable-overwrite"

  extra_configure_flag: "--with-shared"

  extra_configure_flag: "--with-terminfo-dirs=/ro/share/terminfo"
}
