source: "https://invisible-mirror.net/archives/ncurses/ncurses-6.2.tar.gz"
hash: "30306e0c76e0f9f1f0de987cf1c82a5c21e1ce6568b9227f7da5b71cbea86c9d"
version: "6.2-9"

# contains INPUT(-lncursesw) redirect
extra_file: "ncursesw.so.ld"
extra_file: "panelw.so.ld"
extra_file: "formw.so.ld"
extra_file: "menuw.so.ld"

# Prevent our LDFLAGS from ending up in the pkg-config .pc file:
# Should eventually show up in the archives at:
# https://lists.gnu.org/archive/html/bug-ncurses/2020-05/threads.html
cherry_pick: "pc-ldflags.patch"

cbuilder: {
  # TODO: enable C++ support?
  extra_configure_flag: "--without-cxx-binding"
  extra_configure_flag: "--disable-stripping"

  # TODO: does not result in any .pc files?
  extra_configure_flag: "--enable-pc-files"

  extra_configure_flag: "--with-shared"

  extra_configure_flag: "--with-terminfo-dirs=/ro/share/terminfo"

  extra_configure_flag: "--enable-widec"

  # install headers to /usr/include/curses.h instead of /usr/include/ncurses
  # (the latter is not found by e.g. python3)
  extra_configure_flag: "--enable-overwrite"
}

install: {
  # required e.g. for bash:
  symlink: { oldname: "libncurses.so" newname: "lib/libcurses.so" }

  file: {
    srcpath: "ncursesw.so.ld"
    destpath: "lib/libncurses.so"
  }
  file: {
    srcpath: "panelw.so.ld"
    destpath: "lib/libpanel.so"
  }
  file: {
    srcpath: "menuw.so.ld"
    destpath: "lib/libmenu.so"
  }
  file: {
    srcpath: "formw.so.ld"
    destpath: "lib/libform.so"
  }
}
