source: "https://download.qemu.org/qemu-4.2.0.tar.xz"
hash: "d3481d4108ce211a053ef15be69af1bdd9dde1510fda80d92be0f6c3e98768f0"
version: "4.2.0-9"

cbuilder: {}

# build dependencies:
dep: "python3"
dep: "pixman"
dep: "bzip2"
