source: "https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tar.xz"
hash: "22d9b1ac5b26135ad2b8c2901a9413537e08749a753356ee913c84dbd2df5574"
version: "2.7.15-5"

copy_to_builddir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# TODO: file upstream bug: pkg-config invocation does not ignore CPATH
cherry_pick: "py.patch"
cherry_pick: "modules.patch"

# build dependencies:
dep: "zlib"
dep: "openssl"
dep: "libffi"

build_step: {
  argv: "${DISTRI_SOURCEDIR}/configure"
  argv: "--prefix=${DISTRI_PREFIX}"
  argv: "--with-openssl=/ro/${DISTRI_RESOLVE:openssl}/out"
  argv: "--enable-shared"  # for building e.g. libxml2’s Python bindings
  argv: "ac_cv_posix_semaphores_enabled=yes"  # for multiprocessing
}

# https://bugs.python.org/issue34823
build_step: {
  argv: "ln"
  argv: "-s"
  argv: "/ro/${DISTRI_RESOLVE:libffi}/out/lib64"
  argv: "/usr/"
}

build_step: {
  argv: "sed"
  argv: "-i"
  argv: "s,^#zlib,zlib,g"
  argv: "Modules/Setup"
}

build_step: {
  argv: "sed"
  argv: "-i"
  argv: "s,^#_sha,_sha,g"
  argv: "Modules/Setup"
}

# # doesn’t help for sha224 :/
# build_step: <
#   argv: "sed"
#   argv: "-i"
#   argv: "s,^#SSL=/usr/local/ssl,SSL=/ro/${DISTRI_RESOLVE:openssl},g"
#   argv: "Modules/Setup"
# >

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "make -j${DISTRI_JOBS}"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "DESTDIR=${DISTRI_DESTDIR} make install DESTDIR=${DISTRI_DESTDIR}"
}

# python3 is the default python on distri
build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "rm ${DISTRI_DESTDIR}/${DISTRI_PREFIX}/bin/python"
}
