source: "https://ftp.gnu.org/gnu/groff/groff-1.22.4.tar.gz"
hash: "e78e7b4cb7dec310849004fa88847c44701e8d133b5d4c13057d876c1bad0293"
version: "1.22.4-7"

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

# build dependencies:
dep: "perl"
dep: "texinfo"

build_step: {
  argv: "./configure"
  argv: "--prefix=${DISTRI_PREFIX}"
}

build_step: {
  argv: "make"
  argv: "-j1"  # TODO: build fails with -j${DISTRI_JOBS}
  argv: "V=1"
}

build_step: {
  argv: "make"
  argv: "install"
  argv: "DESTDIR=${DISTRI_DESTDIR}"
  argv: "PREFIX=${DISTRI_PREFIX}"
}

