source: "https://ftp.gnu.org/gnu/grub/grub-2.04.tar.xz"
hash: "e5292496995ad42dabe843a0192cf2a2c502e7ffcc7479398232b10a472df77d"
version: "2.04-4"

cherry_pick: "werror.patch"

cbuilder: <
  extra_configure_flag: "--disable-werror"
>

# build dependencies:
dep: "bison"
dep: "flex"
dep: "m4" # TODO: remove (runtime-dep of flex)
dep: "python3"

# grub-mkconfig needs:
runtime_dep: "sed"
runtime_dep: "gawk"
