source: "https://ftp.gnu.org/gnu/grub/grub-2.02.tar.xz"
hash: "810b3798d316394f94096ec2797909dbf23c858e48f7b3830826b8daa06b7b0f"
version: "2.02-2"

cherry_pick: "werror.patch"

cbuilder: <
  extra_configure_flag: "--disable-werror"
>

# build dependencies:
dep: "bison"
dep: "flex"
dep: "m4" # TODO: remove (runtime-dep of flex)

# grub-mkconfig needs:
runtime_dep: "sed"
runtime_dep: "gawk"
