source: "https://gitlab.com/iucode-tool/releases/raw/latest/iucode-tool_2.3.1.tar.xz"
hash: "12b88efa4d0d95af08db05a50b3dcb217c0eb2bfc67b483779e33d498ddb2f95"
version: "2.3.1-3"
pull: {
  # The content of https://gitlab.com/iucode-tool/releases/-/tree/latest is
  # dynamically loaded from:
  releases_url: "https://gitlab.com/iucode-tool/releases/-/refs/latest/logs_tree/?format=json&offset=0"
}

cbuilder: {}

# build dependencies:
