source: "https://gitlab.com/iucode-tool/releases/raw/latest/iucode-tool_2.3.1.tar.xz"
hash: "12b88efa4d0d95af08db05a50b3dcb217c0eb2bfc67b483779e33d498ddb2f95"
version: "2.3.1-1"

cbuilder: <>

# build dependencies:
