source: "http://xmlsoft.org/sources/libxml2-2.9.10.tar.gz"
hash: "aafee193ffb8fe0c82d4afef6ef91972cbaf5feea100edc2f262750611b4be1f"
version: "2.9.10-7"

cbuilder: {
  extra_configure_flag: "--with-python-install-dir=${DISTRI_PREFIX}/lib/python3.7/site-packages"
}

# build dependencies:
dep: "python3"
