source: "https://salsa.debian.org/iso-codes-team/iso-codes/uploads/049ce6aac94d842be809f4063950646c/iso-codes-4.1.tar.xz"
hash: "67117fb76f32c8fb5e37d2d60bce238f1f8e865cc7b569a57cbc3017ca15488a"
version: "4.1-7"
pull: {
  # The content of https://salsa.debian.org/iso-codes-team/iso-codes/-/releases is
  # dynamically loaded from:
  releases_url: "https://salsa.debian.org/api/v4/projects/2957/releases?per_page=20"
}

cbuilder: {}

# build dependencies:
dep: "python3"
