source: "https://github.com/irssi/irssi/releases/download/1.1.1/irssi-1.1.1.tar.xz"
hash: "784807e7a1ba25212347f03e4287cff9d0659f076edfb2c6b20928021d75a1bf"
version: "1.1.1-1"

cbuilder: <>

# build dependencies:
dep: "openssl"
dep: "ncurses"

runtime_dep: "ncurses"

install: <
  empty_dir: "lib/irssi/modules"
>
