source: "https://github.com/irssi/irssi/releases/download/1.2.2/irssi-1.2.2.tar.xz"
hash: "6727060c918568ba2ff4295ad736128dba0b995d7b20491bca11f593bd857578"
version: "1.2.2-7"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# build dependencies:
dep: "openssl"
dep: "ncurses"
dep: "glib"

runtime_dep: "ncurses"

install: {
  empty_dir: "lib/irssi/modules"
}
