source: "https://ftp.gnu.org/gnu/coreutils/coreutils-8.32.tar.xz"
hash: "4458d8de7849df44ccab15e16b1548b285224dbba5f08fac070c1c0e0bcc4cfa"
version: "8.32-4"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {
  extra_configure_flag: "--without-selinux"  # results in link errors when building with host deps
  # TODO: get rid of this once uid/gid are not 0 in the namespace
  extra_configure_flag: "FORCE_UNSAFE_CONFIGURE=1"
  extra_configure_flag: "--enable-install-program=arch"
}

dep: "attr"
dep: "libcap"
