source: "empty://"
version: "2-12"

# This is the shortest and fastest way to build an empty package:
dep: "bash"
build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: ""
>

# The following packages will be installed on ALL distri machines:
runtime_dep: "base-full"
runtime_dep: "xorg-server"
runtime_dep: "xf86-video-vesa"
runtime_dep: "xf86-input-evdev"
runtime_dep: "xf86-input-synaptics"
runtime_dep: "xkeyboard-config"
runtime_dep: "rxvt-unicode"
runtime_dep: "i3"
runtime_dep: "setxkbmap"
runtime_dep: "xrdb"
runtime_dep: "dejavu-fonts-ttf"
runtime_dep: "google-chrome"
runtime_dep: "xdm"
runtime_dep: "kbd"
runtime_dep: "kbd-neo"
