source: "https://netfilter.org/projects/iptables/files/iptables-1.8.4.tar.bz2"
hash: "993a3a5490a544c2cbf2ef15cf7e7ed21af1845baf228318d5c36ef8827e157c"
version: "1.8.4-7"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

# 1.8.0 doesn’t build due to some header-related issue
# source: "https://netfilter.org/projects/iptables/files/iptables-1.8.0.tar.bz2"
# hash: "c4cbfa187c4296e4bc2e347ebbc21e309def7274773f20f0df0b8feaf7e8de50"
# version: "1.8.0"

cbuilder: {
  extra_configure_flag: "--disable-silent-rules"
}

# build dependencies:
dep: "libmnl"
dep: "libnftnl"
dep: "bison"
dep: "flex"
dep: "m4"
