source: "https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.16.2.tar.xz"
hash: "b13e73e2fe74a4166552f9577c3dcb24bed077021b9c7fa600d910ec6987816a"
version: "1.16.2-7"

writable_sourcedir: true  # for autoreconf
in_tree_build: true

cbuilder: {
  autoreconf: true
}

cherry_pick: "make-4.3.patch"

# build dependencies:
dep: "python3"
dep: "gstreamer"
