source: "https://mesa.freedesktop.org/archive/mesa-20.0.5.tar.xz"
hash: "2c56a82a28cc924e40ea49752abdf1d701c9952481f53cbc7a080271597f572e"
version: "20.0.5-8"

mesonbuilder: {
  extra_meson_flag: "-Dllvm=false"  # TODO: package llvm
  extra_meson_flag: "-Dgallium-drivers="  # TODO: package llvm
  extra_meson_flag: "-Dvulkan-drivers=intel"  # TODO: package llvm
  extra_meson_flag: "-Dplatforms=x11"  # TODO: package wayland
}

# build dependencies:
dep: "zlib"
dep: "libdrm"
dep: "libx11"
dep: "libxext"
dep: "libxfixes"
dep: "libxdamage"
dep: "libxshmfence"
dep: "libxrandr"
dep: "expat"
dep: "python3"
dep: "python3-mako"
dep: "bison"
dep: "flex"
dep: "libxxf86vm"
