source: "https://netfilter.org/projects/nftables/files/nftables-0.9.0.tar.bz2"
hash: "ad8181b5fcb9ca572f444bed54018749588522ee97e4c21922648bb78d7e7e91"
version: "0.9.0"

# build dependencies:
dep: "bison-3.0.5"
dep: "flex-2.6.4"
dep: "pkg-config-0.29.2"
dep: "libmnl-1.0.4"
dep: "libnftnl-1.1.1"
dep: "gmp-6.1.2"

cbuilder: <
  extra_configure_flag: "--disable-man-doc"
  extra_configure_flag: "--without-cli" # TODO: figure out why readline isn’t picked up
>
