source: "https://netfilter.org/projects/nftables/files/nftables-0.9.0.tar.bz2"
hash: "ad8181b5fcb9ca572f444bed54018749588522ee97e4c21922648bb78d7e7e91"
version: "0.9.0-2"

# build dependencies:
dep: "bison"
dep: "flex"
dep: "libmnl"
dep: "libnftnl"
dep: "gmp"

cbuilder: <
  extra_configure_flag: "--disable-man-doc"
  extra_configure_flag: "--without-cli" # TODO: figure out why readline isn’t picked up
>
