source: "https://www.mirrorservice.org/sites/ftp.alsa-project.org/pub/lib/alsa-lib-1.1.8.tar.bz2"
hash: "3cdc3a93a6427a26d8efab4ada2152e64dd89140d981f6ffa003e85be707aedf"
version: "1.1.8-7"

cbuilder: {}

# build dependencies:
