source: "https://github.com/fwupd/fwupd/archive/1.4.0.tar.gz"
hash: "fda5d1170c93aa376ba4f5a6072e58e556a6454f6e7c116de85c9766639db1fa"
version: "1.4.0-16"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}

# build dependencies:
dep: "meson"
dep: "gobject-introspection"
dep: "gettext"
dep: "libgudev"
dep: "libxmlb"
dep: "libgusb"
dep: "sqlite3"
dep: "libarchive"
dep: "json-glib"
dep: "libsoup"
dep: "gnutls"
dep: "gcab"
dep: "efivar"
dep: "elfutils"
dep: "cairo"
dep: "pygobject"
dep: "pango"
dep: "pycairo"
dep: "pillow"
dep: "libsmbios"
dep: "vala"
dep: "gnu-efi"
dep: "dejavu-fonts-ttf"
dep: "polkit"
dep: "tpm2-tss"
dep: "gpgme"
dep: "libjcat"

runtime_dep: "shared-mime-info"
runtime_dep: "glib-networking"  # for downloading metadata via TLS via libsoup

# po/make-images requires a working fontconfig:
build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "cp -r /ro/${DISTRI_RESOLVE:fontconfig}/etc/fonts /etc/"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "sed -i 's,/usr/share/fonts,/ro/${DISTRI_RESOLVE:dejavu-fonts-ttf}/out/share/fonts/,g' /etc/fonts/fonts.conf"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "meson --prefix=${DISTRI_PREFIX} --sysconfdir=/etc --localstatedir=/var . ${DISTRI_SOURCEDIR} -Dgtkdoc=false -Dtests=false -Dman=false -Defi-libdir=/ro/${DISTRI_RESOLVE:gnu-efi}/out/lib -Dsystemdunitdir=${DISTRI_PREFIX}/lib/systemd/system"
}

# kludge: the LD_LIBRARY_PATH change is required because we patched rpath handling out of meson.
build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "ninja -j ${DISTRI_JOBS} -v"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "DESTDIR=${DISTRI_DESTDIR} ninja -j ${DISTRI_JOBS} -v install"
}
