source: "https://github.com/dell/libsmbios/archive/v2.4.3.tar.gz"
hash: "36c36a0f6b59190d6b4fef11696886e4511091929a5eb7ae7cf5fea0c32d3f58"
version: "2.4.3-8"

writable_sourcedir: true
in_tree_build: true

cbuilder: {
  autoreconf: true
}

# build dependencies:
dep: "libxml2"
