source: "https://www.libsdl.org/release/SDL2-2.0.9.tar.gz"
hash: "255186dc676ecd0c1dbf10ec8a2cc5d6869b5079d8a38194c2aecdff54b324b1"
version: "2.0.9-1"

cbuilder: <>

# build dependencies:
dep: "mesa"
