source: "http://www.thekelleys.org.uk/dnsmasq/dnsmasq-2.81.tar.xz"
hash: "749ca903537c5197c26444ac24b0dce242cf42595fdfe6b9a5b9e4c7ad32f8fb"
version: "2.81-6"

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

# sed -i 's,#include,#include <linux/sockios.h>\n#include,' src/dhcp.c
cherry_pick: "siocgstamp.patch"

# build dependencies:
dep: "gettext"
dep: "dbus"
dep: "libidn2"

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  argv: "COPTS=\"-DHAVE_DBUS -DHAVE_LIBIDN2\""
  argv: "PREFIX=${DISTRI_PREFIX}"
  argv: "BINDIR=${DISTRI_PREFIX}/bin"
  argv: "all-i18n"
}

build_step: {
  argv: "make"
  argv: "install"
  argv: "install-i18n"
  argv: "COPTS=\"-DHAVE_DBUS -DHAVE_LIBIDN2\""
  argv: "DESTDIR=${DISTRI_DESTDIR}"
  argv: "PREFIX=${DISTRI_PREFIX}"
  argv: "BINDIR=${DISTRI_PREFIX}/bin"
}
