source: "https://download.gnome.org/sources/pangomm/2.42/pangomm-2.42.1.tar.xz"
hash: "14bf04939930870d5cfa96860ed953ad2ce07c3fd8713add4a1bfe585589f40f"
version: "2.42.1-8"

cbuilder: {}

# build dependencies:
dep: "glibmm"
dep: "cairomm"
dep: "pango"
