source: "https://archive.mozilla.org/pub/security/nss/releases/NSS_3_39_RTM/src/nss-3.39.tar.gz"
hash: "6be64dd76f212415cc8bc34343ac1e7389048db4db9a023a84873c411dc5864b"
version: "3.39"

cherry_pick: "nss-3.39-standalone-1.patch"

cbuilder: <>

# build dependencies:
dep: "perl"
dep: "nspr"

dep: "strace"

# TODO: to work around g++ issue where #include_next <stdlib.h> from cstdlib.h won’t find the header
build_step: <
  argv: "rm"
  argv: "/usr/include"
>
build_step: <
  argv: "ln"
  argv: "-s"
  argv: "/ro/glibc-amd64-2.27/out/include"
  argv: "/usr/include"
>

build_step: <
  argv: "make"
  argv: "-C"
  argv: "${ZI_SOURCEDIR}/nss"
  argv: "USE_64=1"
  argv: "NSPR_INCLUDE_DIR=/ro/nspr-amd64-4.20/out/include/nspr/"
  argv: "CROSS_COMPILE=1" # otherwise cmd/shlibsign tries to call sign.sh, which requires /dev/urandom
  # TODO: USE_SYSTEM_ZLIB=1
  # TODO: NSS_USE_SYSTEM_SQLITE=1
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${ZI_DESTDIR}/${ZI_PREFIX}/lib; mkdir -p $d; install -m755 ${ZI_SOURCEDIR}/dist/Linux*/lib/*.{so,a} $d"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${ZI_DESTDIR}/${ZI_PREFIX}/include; mkdir -p $d; cp -RL ${ZI_SOURCEDIR}/dist/{public,private}/nss/* $d"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  # TODO: why not install all binaries? LFS only choses these 3
  argv: "d=${ZI_DESTDIR}/${ZI_PREFIX}/bin; mkdir -p $d; install -m755 ${ZI_SOURCEDIR}/dist/Linux*/bin/{certutil,nss-config,pk12util} $d"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${ZI_DESTDIR}/${ZI_PREFIX}/lib/pkgconfig; mkdir -p $d; install -m644 ${ZI_SOURCEDIR}/dist/Linux*/lib/pkgconfig/nss.pc $d"
>
