source: "https://archive.mozilla.org/pub/security/nss/releases/NSS_3_39_RTM/src/nss-3.39.tar.gz"
hash: "6be64dd76f212415cc8bc34343ac1e7389048db4db9a023a84873c411dc5864b"
version: "3.39-5"

cherry_pick: "nss-3.39-standalone-1.patch"

cbuilder: {}

# build dependencies:
dep: "perl"
dep: "nspr"
dep: "sqlite3"

dep: "strace"

build_step: {
  argv: "cp"
  argv: "-T"
  argv: "-ar"
  argv: "${DISTRI_SOURCEDIR}/"
  argv: "."
}

# TODO: to work around g++ issue where #include_next <stdlib.h> from cstdlib.h won’t find the header
build_step: {
  argv: "rm"
  argv: "/usr/include"
}
build_step: {
  argv: "ln"
  argv: "-s"
  argv: "/ro/${DISTRI_RESOLVE:glibc}/out/include"
  argv: "/usr/include"
}

build_step: {
  argv: "make"
  argv: "-C"
  argv: "nss"
  argv: "USE_64=1"
  argv: "NSPR_INCLUDE_DIR=/ro/${DISTRI_RESOLVE:nspr}/out/include/nspr/"
  argv: "CROSS_COMPILE=1"  # otherwise cmd/shlibsign tries to call sign.sh, which requires /dev/urandom
  argv: "NSS_USE_SYSTEM_SQLITE=1"  # prevent linking errors in e.g. networkmanager
  # TODO: USE_SYSTEM_ZLIB=1
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/lib; mkdir -p $d; install -m755 dist/Linux*/lib/*.{so,a} $d"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/include; mkdir -p $d; cp -RL dist/{public,private}/nss/* $d"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  # TODO: why not install all binaries? LFS only choses these 3
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/bin; mkdir -p $d; install -m755 dist/Linux*/bin/{certutil,nss-config,pk12util} $d"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/lib/pkgconfig; mkdir -p $d; install -m644 dist/Linux*/lib/pkgconfig/nss.pc $d"
}
