source: "https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_51_1_RTM/src/nss-3.51.1.tar.gz"
hash: "085c5eaceef040eddea639e2e068e70f0e368f840327a678ef74ae3d6c15ca78"
version: "3.51.1-7"
pull: {
  releases_url: "https://ftp.mozilla.org/pub/security/nss/releases/"
  release_regexp: "NSS_([0-9]+_[0-9]+(?:_[0-9]+)?)_RTM"
  release_replace_all: {
    expr: "_"
    repl: "."
  }
}

cherry_pick: "nss-3.51.1-standalone-1.patch"

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

# build dependencies:
dep: "perl"
dep: "nspr"
dep: "sqlite3"

dep: "strace"

# TODO: to work around g++ issue where #include_next <stdlib.h> from cstdlib.h won’t find the header
build_step: {
  argv: "rm"
  argv: "/usr/include"
}
build_step: {
  argv: "ln"
  argv: "-s"
  argv: "/ro/${DISTRI_RESOLVE:glibc}/out/include"
  argv: "/usr/include"
}

build_step: {
  argv: "make"
  argv: "-C"
  argv: "nss"
  argv: "USE_64=1"
  argv: "NSPR_INCLUDE_DIR=/ro/${DISTRI_RESOLVE:nspr}/out/include/nspr/"
  argv: "CROSS_COMPILE=1"  # otherwise cmd/shlibsign tries to call sign.sh, which requires /dev/urandom
  argv: "NSS_USE_SYSTEM_SQLITE=1"  # prevent linking errors in e.g. networkmanager
  argv: "PREFIX=${DISTRI_PREFIX}"
  # TODO: USE_SYSTEM_ZLIB=1
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/lib; mkdir -p $d; install -m755 dist/Linux*/lib/*.{so,a} $d"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/include/nss/; mkdir -p $d; cp -RL dist/{public,private}/nss/* $d"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  # TODO: why not install all binaries? LFS only choses these 3
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/bin; mkdir -p $d; install -m755 dist/Linux*/bin/{certutil,nss-config,pk12util} $d"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/lib/pkgconfig; mkdir -p $d; install -m644 dist/Linux*/lib/pkgconfig/nss.pc $d"
}
