source: "https://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.8.1.tar.xz"
hash: "105556dbc5c3fbbc2aa0edb46d22d055748b6f5c7cd7a8d99f8e7eb84e938be4"
version: "0.19.8.1"

cbuilder: <>

# build dependencies:
dep: "gzip"
