source: "https://ftp.gnu.org/gnu/gdb/gdb-9.1.tar.xz"
hash: "699e0ec832fdd2f21c8266171ea5bf44024bd05164fdf064e4d10cc4cf0d1737"
version: "9.1-8"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {
  extra_configure_flag: "--with-separate-debug-dir=/ro-dbg/debug"
}

cherry_pick: "0001-gdb-read-distrifilename-ELF-section-and-follow-redir.patch"

# build dependencies:
dep: "texinfo"
dep: "perl"
dep: "elfutils"
