# latest google-chrome-stable .deb from
# http://dl.google.com/linux/chrome/deb/dists/stable/main/binary-amd64/Packages:
source: "http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_80.0.3987.87-1_amd64.deb"
hash: "85e07dee624d3c7eec6a6194efcb070b353ee52c0e5980517760230128a3ba61"
version: "80.0.3987.87-1-11"

cbuilder: {}

dep: "tar"  # for unpacking the data.tar.xz part of the .deb
dep: "xzutils"

dep: "expat"
dep: "pango"
dep: "cairo"
dep: "libxext"
dep: "libxdamage"
dep: "libxfixes"
dep: "libxrender"
dep: "libxrandr"
dep: "gdk-pixbuf"
dep: "gtk+"
dep: "libxcomposite"
dep: "libxcursor"
dep: "libxtst"
dep: "nss"
dep: "cups"
dep: "libxscrnsaver"
dep: "alsa-lib"
dep: "patchelf"

build_step: {
  argv: "tar"
  argv: "xf"
  argv: "${DISTRI_SOURCEDIR}/data.tar.xz"
}

build_step: {
  argv: "ldd"
  argv: "opt/google/chrome/chrome"
}

# We need to use patchelf --set-rpath with chrome-sandbox, because its setuid
# bit triggers secure-execution mode in ld.so(8), resulting in the
# LD_LIBRARY_PATH environment variable being ignored.
build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/bin; mkdir -p $d; cp -ar opt/google/chrome/* $d; patchelf --set-rpath $LD_LIBRARY_PATH $d/chrome-sandbox; chmod u+s $d/chrome-sandbox"
}
