source: "http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_81.0.4044.138-1_amd64.deb"
hash: "9d13d41d79ce1f04d1f150b5d22fffd31779224cc7d8274f8479b06bcfe6846a"
version: "81.0.4044.138-1-17"
pull: {
  debian_packages: "https://dl.google.com/linux/chrome/deb/dists/stable/main/binary-amd64/Packages"
}

cbuilder: {}

dep: "tar"  # for unpacking the data.tar.xz part of the .deb
dep: "xzutils"

dep: "expat"
dep: "pango"
dep: "cairo"
dep: "libxext"
dep: "libxdamage"
dep: "libxfixes"
dep: "libxrender"
dep: "libxrandr"
dep: "gdk-pixbuf"
dep: "gtk+"
dep: "libxcomposite"
dep: "libxcursor"
dep: "libxtst"
dep: "nss"
dep: "cups"
dep: "libxscrnsaver"
dep: "alsa-lib"
dep: "patchelf"

build_step: {
  argv: "tar"
  argv: "xf"
  argv: "${DISTRI_SOURCEDIR}/data.tar.xz"
}

build_step: {
  argv: "ldd"
  argv: "opt/google/chrome/chrome"
}

# We need to use patchelf --set-rpath with chrome-sandbox, because its setuid
# bit triggers secure-execution mode in ld.so(8), resulting in the
# LD_LIBRARY_PATH environment variable being ignored.
build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/bin; mkdir -p $d; cp -ar opt/google/chrome/* $d; patchelf --set-rpath $LD_LIBRARY_PATH $d/chrome-sandbox; chmod u+s $d/chrome-sandbox"
}
