source: "https://ftp.gnu.org/gnu/bison/bison-3.0.5.tar.xz"
hash: "075cef2e814642e30e10e8155e93022e4a91ca38a65aa1d5467d4e969f97f338"
version: "3.0.5-2"

cbuilder: <
  copy_to_builddir: true
>

# build dependencies:
dep: "m4"
dep: "perl"
dep: "help2man"

runtime_dep: "m4"
