source: "https://ftp.gnu.org/gnu/bison/bison-3.5.3.tar.xz"
hash: "2bf85b5f88a5f2fa8069aed2a2dfc3a9f8d15a97e59c713e3906e5fdd982a7c4"
version: "3.5.3-4"

writable_sourcedir: true
in_tree_build: true

cbuilder: {
}

# build dependencies:
dep: "m4"
dep: "perl"
dep: "help2man"

runtime_dep: "m4"
