source: "https://mirror.kumi.systems/gnu/emacs/emacs-26.3.tar.xz"
hash: "4d90e6751ad8967822c6e092db07466b9d383ef1653feb2f95c93e7de66d3485"
version: "26.3-15"

writable_sourcedir: true  # modifies source

cbuilder: {
  extra_configure_flag: "--with-gnutls=no"  # TODO: why doesn’t configure locate gnutls?
  extra_configure_flag: "--with-x-toolkit=gtk3"
}

# build dependencies:
dep: "gnutls"
dep: "ncurses"
dep: "tar"
dep: "gnupg"  # only so that it ends up in PATH
dep: "git"  # only so that it ends up in PATH
dep: "gzip"
dep: "libx11"
dep: "gtk+"
dep: "mesa"  # TODO: should be pulled in via epoxy via gtk+
dep: "shared-mime-info"
dep: "systemd"
dep: "libxpm"
dep: "tiff"
dep: "giflib"
dep: "cairo"
dep: "libxft"
dep: "freetype"

runtime_dep: "bash"  # for M-x shell
runtime_dep: "coreutils"  # for M-x dired
runtime_dep: "ncurses"
runtime_dep: "gnutls"  # for gnutls-cli
runtime_dep: "gnupg"  # used by package.el
runtime_dep: "git"  # used by package.el
