source: "http://ftp.gnome.org/pub/gnome/sources/libgudev/231233/libgudev-233.tar.xz"
hash: "587c4970eb23f4e2deee2cb1fb7838c94a78c578f41ce12cac0a3f4a80dabb03"
version: "233-9"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {
  extra_configure_flag: "--disable-umockdev"
}

# build dependencies:
dep: "systemd"  # for udev
dep: "python3"
dep: "glib"
