source: "https://cmake.org/files/v3.12/cmake-3.12.2.tar.gz"
hash: "0f97485799e51a7070cc11494f3e02349b0fc3a24cc12b082e737bf67a0581a4"
version: "3.12.2"

cbuilder: <>

# build dependencies:
dep: "pkg-config-0.29.2"

# TODO: to work around g++ issue where #include_next <stdlib.h> from cstdlib.h won’t find the header
build_step: <
  argv: "ln"
  argv: "-s"
  argv: "/ro/glibc-2.27/buildoutput/include"
  argv: "/usr/include"
>

build_step: <
  argv: "${ZI_SOURCEDIR}/configure"
  argv: "--prefix=${ZI_PREFIX}"
>

build_step: <
  argv: "make"
  argv: "-j8"
  argv: "V=1"
>

build_step: <
  argv: "make"
  argv: "install"
  argv: "DESTDIR=${ZI_DESTDIR}"
  argv: "PREFIX=${ZI_PREFIX}"
>
