source: "https://cmake.org/files/v3.12/cmake-3.12.4.tar.gz"
hash: "5255584bfd043eb717562cff8942d472f1c0e4679c4941d84baadaa9b28e3194"
version: "3.12.4-8"

cbuilder: {}

# build dependencies:
dep: "ncurses"

build_step: {
  argv: "${DISTRI_SOURCEDIR}/configure"
  argv: "--prefix=${DISTRI_PREFIX}"
  argv: "--parallel=8"
  argv: "--"
  argv: "-DBUILD_CursesDialog=ON"
  argv: "-DCURSES_LIBRARY=/ro/lib/libncurses.so"
  argv: "-DCMAKE_VERBOSE_MAKEFILE=ON"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  argv: "V=1"
}

build_step: {
  argv: "make"
  argv: "install"
  argv: "DESTDIR=${DISTRI_DESTDIR}"
  argv: "PREFIX=${DISTRI_PREFIX}"
}
