source: "https://github.com/hughsie/libgusb/archive/0.3.4.tar.gz"
hash: "07049389eb20847eedb664e2a2d954412a28bee125647ea6a445c59bebbd9944"
version: "0.3.4-9"

pull: {
  # gusb_0_2_9.tar.gz is not valid semver, but newer releases are
  # TODO: ask upstream for a commitment to semver
  force_semver: true
}

mesonbuilder: {
  extra_meson_flag: "-Dgtkdoc=false"
}

cherry_pick: "0001-remove-unconditional-gtkdoc-call.patch"

# build dependencies:
dep: "gobject-introspection"
dep: "gettext"
dep: "libusb"
dep: "vala"
