source: "https://github.com/CanonicalLtd/lightdm/releases/download/1.28.0/lightdm-1.28.0.tar.xz"
hash: "f20f599d8d7cf90b77a2df33c6e9e615abc443123b1b228de1c20a636aecfa07"
version: "1.28.0-1"
extra_file: "lightdm.service"
extra_file: "lightdm.sysusers"
extra_file: "lightdm.tmpfiles"

# sed -i 's,^#xserver-command=X,xserver-command=Xorg,g' data/lightdm.conf
# sed -i 's,^#greeter-session=.*,greeter-session=lightdm-gtk-greeter,g' data/lightdm.conf
cherry_pick: "defaultconfig.patch"

cbuilder: <
  extra_configure_flag: "--localstatedir=/var"
  extra_configure_flag: "--enable-vala"
>

# build dependencies:
dep: "libgcrypt"
dep: "libxcb"
dep: "libxdmcp"
dep: "libx11"
dep: "libxklavier"
dep: "itstool"
dep: "intltool"
dep: "gobject-introspection"
dep: "vala"

runtime_dep: "accountsservice"

install: <
  systemd_unit: "${DISTRI_SOURCEDIR}/lightdm.service"

  file: <
    srcpath: "lightdm.sysusers"
    destpath: "lib/sysusers.d/lightdm.sysusers"
  >
  file: <
    srcpath: "lightdm.tmpfiles"
    destpath: "lib/tmpfiles.d/lightdm.tmpfiles"
  >
>
