// Code generated by protoc-gen-go. DO NOT EDIT.
// source: build.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BuildStep struct {
	Argv                 []string `protobuf:"bytes,1,rep,name=argv" json:"argv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildStep) Reset()         { *m = BuildStep{} }
func (m *BuildStep) String() string { return proto.CompactTextString(m) }
func (*BuildStep) ProtoMessage()    {}
func (*BuildStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_88433add5081ad71, []int{0}
}
func (m *BuildStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildStep.Unmarshal(m, b)
}
func (m *BuildStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildStep.Marshal(b, m, deterministic)
}
func (dst *BuildStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildStep.Merge(dst, src)
}
func (m *BuildStep) XXX_Size() int {
	return xxx_messageInfo_BuildStep.Size(m)
}
func (m *BuildStep) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildStep.DiscardUnknown(m)
}

var xxx_messageInfo_BuildStep proto.InternalMessageInfo

func (m *BuildStep) GetArgv() []string {
	if m != nil {
		return m.Argv
	}
	return nil
}

type CBuilder struct {
	ExtraConfigureFlag []string `protobuf:"bytes,1,rep,name=extra_configure_flag,json=extraConfigureFlag" json:"extra_configure_flag,omitempty"`
	// Packages which don’t support separate builddirs need to use this
	// kludge. Bugs should be reported with the respective upstream authors.
	CopyToBuilddir       *bool    `protobuf:"varint,2,opt,name=copy_to_builddir,json=copyToBuilddir" json:"copy_to_builddir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CBuilder) Reset()         { *m = CBuilder{} }
func (m *CBuilder) String() string { return proto.CompactTextString(m) }
func (*CBuilder) ProtoMessage()    {}
func (*CBuilder) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_88433add5081ad71, []int{1}
}
func (m *CBuilder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CBuilder.Unmarshal(m, b)
}
func (m *CBuilder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CBuilder.Marshal(b, m, deterministic)
}
func (dst *CBuilder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CBuilder.Merge(dst, src)
}
func (m *CBuilder) XXX_Size() int {
	return xxx_messageInfo_CBuilder.Size(m)
}
func (m *CBuilder) XXX_DiscardUnknown() {
	xxx_messageInfo_CBuilder.DiscardUnknown(m)
}

var xxx_messageInfo_CBuilder proto.InternalMessageInfo

func (m *CBuilder) GetExtraConfigureFlag() []string {
	if m != nil {
		return m.ExtraConfigureFlag
	}
	return nil
}

func (m *CBuilder) GetCopyToBuilddir() bool {
	if m != nil && m.CopyToBuilddir != nil {
		return *m.CopyToBuilddir
	}
	return false
}

type Install struct {
	SystemdUnit          []string           `protobuf:"bytes,1,rep,name=systemd_unit,json=systemdUnit" json:"systemd_unit,omitempty"`
	Symlink              []*Install_Symlink `protobuf:"bytes,2,rep,name=symlink" json:"symlink,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Install) Reset()         { *m = Install{} }
func (m *Install) String() string { return proto.CompactTextString(m) }
func (*Install) ProtoMessage()    {}
func (*Install) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_88433add5081ad71, []int{2}
}
func (m *Install) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Install.Unmarshal(m, b)
}
func (m *Install) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Install.Marshal(b, m, deterministic)
}
func (dst *Install) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Install.Merge(dst, src)
}
func (m *Install) XXX_Size() int {
	return xxx_messageInfo_Install.Size(m)
}
func (m *Install) XXX_DiscardUnknown() {
	xxx_messageInfo_Install.DiscardUnknown(m)
}

var xxx_messageInfo_Install proto.InternalMessageInfo

func (m *Install) GetSystemdUnit() []string {
	if m != nil {
		return m.SystemdUnit
	}
	return nil
}

func (m *Install) GetSymlink() []*Install_Symlink {
	if m != nil {
		return m.Symlink
	}
	return nil
}

type Install_Symlink struct {
	Oldname              *string  `protobuf:"bytes,1,opt,name=oldname" json:"oldname,omitempty"`
	Newname              *string  `protobuf:"bytes,2,opt,name=newname" json:"newname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Install_Symlink) Reset()         { *m = Install_Symlink{} }
func (m *Install_Symlink) String() string { return proto.CompactTextString(m) }
func (*Install_Symlink) ProtoMessage()    {}
func (*Install_Symlink) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_88433add5081ad71, []int{2, 0}
}
func (m *Install_Symlink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Install_Symlink.Unmarshal(m, b)
}
func (m *Install_Symlink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Install_Symlink.Marshal(b, m, deterministic)
}
func (dst *Install_Symlink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Install_Symlink.Merge(dst, src)
}
func (m *Install_Symlink) XXX_Size() int {
	return xxx_messageInfo_Install_Symlink.Size(m)
}
func (m *Install_Symlink) XXX_DiscardUnknown() {
	xxx_messageInfo_Install_Symlink.DiscardUnknown(m)
}

var xxx_messageInfo_Install_Symlink proto.InternalMessageInfo

func (m *Install_Symlink) GetOldname() string {
	if m != nil && m.Oldname != nil {
		return *m.Oldname
	}
	return ""
}

func (m *Install_Symlink) GetNewname() string {
	if m != nil && m.Newname != nil {
		return *m.Newname
	}
	return ""
}

type Build struct {
	// URL to upstream source archive. Currently, only tar.gz archives are supported.
	Source *string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	// Hash (TODO: describe length, introduce prefixes?) of the upstream source archive.
	Hash *string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	// Version number, to be concatenated to the package name.
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Types that are valid to be assigned to Builder:
	//	*Build_Cbuilder
	Builder isBuild_Builder `protobuf_oneof:"builder"`
	// TODO: move this field into a custom builder
	BuildStep []*BuildStep `protobuf:"bytes,4,rep,name=build_step,json=buildStep" json:"build_step,omitempty"`
	// TODO: rename to build_dep
	Dep        []string `protobuf:"bytes,5,rep,name=dep" json:"dep,omitempty"`
	RuntimeDep []string `protobuf:"bytes,9,rep,name=runtime_dep,json=runtimeDep" json:"runtime_dep,omitempty"`
	// URLs to patches to cherry-pick after extracting the source, e.g.:
	// https://git.savannah.gnu.org/cgit/make.git/patch/?id=48c8a116a914a325a0497721f5d8b58d5bba34d4
	CherryPick           []string `protobuf:"bytes,6,rep,name=cherry_pick,json=cherryPick" json:"cherry_pick,omitempty"`
	Install              *Install `protobuf:"bytes,8,opt,name=install" json:"install,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_88433add5081ad71, []int{3}
}
func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (dst *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(dst, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

type isBuild_Builder interface {
	isBuild_Builder()
}

type Build_Cbuilder struct {
	Cbuilder *CBuilder `protobuf:"bytes,7,opt,name=cbuilder,oneof"`
}

func (*Build_Cbuilder) isBuild_Builder() {}

func (m *Build) GetBuilder() isBuild_Builder {
	if m != nil {
		return m.Builder
	}
	return nil
}

func (m *Build) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *Build) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *Build) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *Build) GetCbuilder() *CBuilder {
	if x, ok := m.GetBuilder().(*Build_Cbuilder); ok {
		return x.Cbuilder
	}
	return nil
}

func (m *Build) GetBuildStep() []*BuildStep {
	if m != nil {
		return m.BuildStep
	}
	return nil
}

func (m *Build) GetDep() []string {
	if m != nil {
		return m.Dep
	}
	return nil
}

func (m *Build) GetRuntimeDep() []string {
	if m != nil {
		return m.RuntimeDep
	}
	return nil
}

func (m *Build) GetCherryPick() []string {
	if m != nil {
		return m.CherryPick
	}
	return nil
}

func (m *Build) GetInstall() *Install {
	if m != nil {
		return m.Install
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Build) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Build_OneofMarshaler, _Build_OneofUnmarshaler, _Build_OneofSizer, []interface{}{
		(*Build_Cbuilder)(nil),
	}
}

func _Build_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Build)
	// builder
	switch x := m.Builder.(type) {
	case *Build_Cbuilder:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Cbuilder); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Build.Builder has unexpected type %T", x)
	}
	return nil
}

func _Build_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Build)
	switch tag {
	case 7: // builder.cbuilder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CBuilder)
		err := b.DecodeMessage(msg)
		m.Builder = &Build_Cbuilder{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Build_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Build)
	// builder
	switch x := m.Builder.(type) {
	case *Build_Cbuilder:
		s := proto.Size(x.Cbuilder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*BuildStep)(nil), "pb.BuildStep")
	proto.RegisterType((*CBuilder)(nil), "pb.CBuilder")
	proto.RegisterType((*Install)(nil), "pb.Install")
	proto.RegisterType((*Install_Symlink)(nil), "pb.Install.Symlink")
	proto.RegisterType((*Build)(nil), "pb.Build")
}

func init() { proto.RegisterFile("build.proto", fileDescriptor_build_88433add5081ad71) }

var fileDescriptor_build_88433add5081ad71 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x49, 0xb6, 0x6d, 0x92, 0x49, 0x41, 0x95, 0x41, 0xc8, 0xe2, 0xd2, 0x10, 0x09, 0x29,
	0x42, 0x10, 0xa1, 0xde, 0xb9, 0x6c, 0x11, 0x82, 0x1b, 0x4a, 0xe1, 0x6c, 0xe5, 0x8f, 0x37, 0x6b,
	0x6d, 0x62, 0x5b, 0xb6, 0x53, 0xc8, 0xab, 0xf0, 0x0e, 0xbc, 0x23, 0xf2, 0x9f, 0xac, 0x7a, 0x9b,
	0xf9, 0x7e, 0x9f, 0x27, 0x93, 0x6f, 0x20, 0xef, 0x16, 0x36, 0x0d, 0xb5, 0x54, 0xc2, 0x08, 0x14,
	0xcb, 0xae, 0xbc, 0x85, 0x6c, 0x6f, 0xa5, 0x07, 0x43, 0x25, 0x42, 0x70, 0xd1, 0xaa, 0xf1, 0x11,
	0x47, 0xc5, 0xae, 0xca, 0x1a, 0x57, 0x97, 0x07, 0x48, 0xef, 0x9d, 0x83, 0x2a, 0xf4, 0x09, 0x5e,
	0xd1, 0x3f, 0x46, 0xb5, 0xa4, 0x17, 0xfc, 0xc0, 0xc6, 0x45, 0x51, 0x72, 0x98, 0xda, 0x31, 0xf8,
	0x91, 0x63, 0xf7, 0x1b, 0xfa, 0x3a, 0xb5, 0x23, 0xaa, 0xe0, 0xa6, 0x17, 0x72, 0x25, 0x46, 0x10,
	0xf7, 0xe5, 0x81, 0x29, 0x1c, 0x17, 0x51, 0x95, 0x36, 0x2f, 0xac, 0xfe, 0x53, 0xec, 0x83, 0x5a,
	0xfe, 0x8d, 0x20, 0xf9, 0xce, 0xb5, 0x69, 0xa7, 0x09, 0xbd, 0x85, 0x6b, 0xbd, 0x6a, 0x43, 0xe7,
	0x81, 0x2c, 0x9c, 0x99, 0x30, 0x3f, 0x0f, 0xda, 0x2f, 0xce, 0x0c, 0xfa, 0x08, 0x89, 0x5e, 0xe7,
	0x89, 0xf1, 0x13, 0x8e, 0x8b, 0x5d, 0x95, 0xdf, 0xbd, 0xac, 0x65, 0x57, 0x87, 0x01, 0xf5, 0x83,
	0x47, 0xcd, 0xe6, 0x79, 0xf3, 0x19, 0x92, 0xa0, 0x21, 0x0c, 0x89, 0x98, 0x06, 0xde, 0xce, 0x14,
	0x47, 0x45, 0x54, 0x65, 0xcd, 0xd6, 0x5a, 0xc2, 0xe9, 0x6f, 0x47, 0x62, 0x4f, 0x42, 0x5b, 0xfe,
	0x8b, 0xe1, 0xd2, 0x6d, 0x8a, 0x5e, 0xc3, 0x95, 0x16, 0x8b, 0xea, 0xb7, 0xc7, 0xa1, 0xb3, 0xd1,
	0x1d, 0x5b, 0x7d, 0x0c, 0x0f, 0x5d, 0x6d, 0xe7, 0x3d, 0x52, 0xa5, 0x99, 0xe0, 0x78, 0xe7, 0xe7,
	0x85, 0x16, 0xbd, 0x87, 0xb4, 0xef, 0x7c, 0xa8, 0x38, 0x29, 0xa2, 0x2a, 0xbf, 0xbb, 0xb6, 0xeb,
	0x6f, 0x41, 0x7f, 0x7b, 0xd6, 0x9c, 0x39, 0xfa, 0x00, 0xe0, 0x4a, 0xa2, 0x0d, 0x95, 0xf8, 0xc2,
	0xfd, 0xec, 0x73, 0xeb, 0x3e, 0xdf, 0xad, 0xc9, 0xba, 0xf3, 0x09, 0x6f, 0x60, 0x37, 0x50, 0x89,
	0x2f, 0x5d, 0x62, 0xb6, 0x44, 0xb7, 0x90, 0xab, 0x85, 0x1b, 0x36, 0x53, 0x62, 0x49, 0xe6, 0x08,
	0x04, 0xe9, 0x8b, 0x37, 0xf4, 0x47, 0xaa, 0xd4, 0x4a, 0x24, 0xeb, 0x4f, 0xf8, 0xca, 0x1b, 0xbc,
	0xf4, 0x83, 0xf5, 0x27, 0xf4, 0x0e, 0x12, 0xe6, 0x83, 0xc5, 0xa9, 0x5b, 0x36, 0x7f, 0x92, 0x75,
	0xb3, 0xb1, 0x7d, 0x06, 0x49, 0xd8, 0xf9, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xd6, 0x9b,
	0x6b, 0x67, 0x02, 0x00, 0x00,
}
