// Code generated by protoc-gen-go. DO NOT EDIT.
// source: build.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BuildStep struct {
	Argv                 []string `protobuf:"bytes,1,rep,name=argv" json:"argv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildStep) Reset()         { *m = BuildStep{} }
func (m *BuildStep) String() string { return proto.CompactTextString(m) }
func (*BuildStep) ProtoMessage()    {}
func (*BuildStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{0}
}

func (m *BuildStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildStep.Unmarshal(m, b)
}
func (m *BuildStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildStep.Marshal(b, m, deterministic)
}
func (m *BuildStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildStep.Merge(m, src)
}
func (m *BuildStep) XXX_Size() int {
	return xxx_messageInfo_BuildStep.Size(m)
}
func (m *BuildStep) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildStep.DiscardUnknown(m)
}

var xxx_messageInfo_BuildStep proto.InternalMessageInfo

func (m *BuildStep) GetArgv() []string {
	if m != nil {
		return m.Argv
	}
	return nil
}

type CBuilder struct {
	ExtraConfigureFlag []string `protobuf:"bytes,1,rep,name=extra_configure_flag,json=extraConfigureFlag" json:"extra_configure_flag,omitempty"`
	ExtraLdflag        []string `protobuf:"bytes,3,rep,name=extra_ldflag,json=extraLdflag" json:"extra_ldflag,omitempty"`
	// Packages which don’t support separate builddirs need to use this
	// kludge. Bugs should be reported with the respective upstream authors.
	CopyToBuilddir       *bool    `protobuf:"varint,2,opt,name=copy_to_builddir,json=copyToBuilddir" json:"copy_to_builddir,omitempty"`
	ExtraMakeFlag        []string `protobuf:"bytes,4,rep,name=extra_make_flag,json=extraMakeFlag" json:"extra_make_flag,omitempty"`
	Autoreconf           *bool    `protobuf:"varint,5,opt,name=autoreconf" json:"autoreconf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CBuilder) Reset()         { *m = CBuilder{} }
func (m *CBuilder) String() string { return proto.CompactTextString(m) }
func (*CBuilder) ProtoMessage()    {}
func (*CBuilder) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{1}
}

func (m *CBuilder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CBuilder.Unmarshal(m, b)
}
func (m *CBuilder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CBuilder.Marshal(b, m, deterministic)
}
func (m *CBuilder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CBuilder.Merge(m, src)
}
func (m *CBuilder) XXX_Size() int {
	return xxx_messageInfo_CBuilder.Size(m)
}
func (m *CBuilder) XXX_DiscardUnknown() {
	xxx_messageInfo_CBuilder.DiscardUnknown(m)
}

var xxx_messageInfo_CBuilder proto.InternalMessageInfo

func (m *CBuilder) GetExtraConfigureFlag() []string {
	if m != nil {
		return m.ExtraConfigureFlag
	}
	return nil
}

func (m *CBuilder) GetExtraLdflag() []string {
	if m != nil {
		return m.ExtraLdflag
	}
	return nil
}

func (m *CBuilder) GetCopyToBuilddir() bool {
	if m != nil && m.CopyToBuilddir != nil {
		return *m.CopyToBuilddir
	}
	return false
}

func (m *CBuilder) GetExtraMakeFlag() []string {
	if m != nil {
		return m.ExtraMakeFlag
	}
	return nil
}

func (m *CBuilder) GetAutoreconf() bool {
	if m != nil && m.Autoreconf != nil {
		return *m.Autoreconf
	}
	return false
}

type CMakeBuilder struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMakeBuilder) Reset()         { *m = CMakeBuilder{} }
func (m *CMakeBuilder) String() string { return proto.CompactTextString(m) }
func (*CMakeBuilder) ProtoMessage()    {}
func (*CMakeBuilder) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{2}
}

func (m *CMakeBuilder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMakeBuilder.Unmarshal(m, b)
}
func (m *CMakeBuilder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMakeBuilder.Marshal(b, m, deterministic)
}
func (m *CMakeBuilder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMakeBuilder.Merge(m, src)
}
func (m *CMakeBuilder) XXX_Size() int {
	return xxx_messageInfo_CMakeBuilder.Size(m)
}
func (m *CMakeBuilder) XXX_DiscardUnknown() {
	xxx_messageInfo_CMakeBuilder.DiscardUnknown(m)
}

var xxx_messageInfo_CMakeBuilder proto.InternalMessageInfo

type MesonBuilder struct {
	ExtraMesonFlag       []string `protobuf:"bytes,1,rep,name=extra_meson_flag,json=extraMesonFlag" json:"extra_meson_flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MesonBuilder) Reset()         { *m = MesonBuilder{} }
func (m *MesonBuilder) String() string { return proto.CompactTextString(m) }
func (*MesonBuilder) ProtoMessage()    {}
func (*MesonBuilder) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{3}
}

func (m *MesonBuilder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MesonBuilder.Unmarshal(m, b)
}
func (m *MesonBuilder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MesonBuilder.Marshal(b, m, deterministic)
}
func (m *MesonBuilder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MesonBuilder.Merge(m, src)
}
func (m *MesonBuilder) XXX_Size() int {
	return xxx_messageInfo_MesonBuilder.Size(m)
}
func (m *MesonBuilder) XXX_DiscardUnknown() {
	xxx_messageInfo_MesonBuilder.DiscardUnknown(m)
}

var xxx_messageInfo_MesonBuilder proto.InternalMessageInfo

func (m *MesonBuilder) GetExtraMesonFlag() []string {
	if m != nil {
		return m.ExtraMesonFlag
	}
	return nil
}

type PerlBuilder struct {
	// Extra flags to be specified when running Makefile.PL, e.g.
	// EXPATLIBPATH=/ro/expat-2.2.6/buildoutput/lib
	ExtraMakefileFlag    []string `protobuf:"bytes,1,rep,name=extra_makefile_flag,json=extraMakefileFlag" json:"extra_makefile_flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PerlBuilder) Reset()         { *m = PerlBuilder{} }
func (m *PerlBuilder) String() string { return proto.CompactTextString(m) }
func (*PerlBuilder) ProtoMessage()    {}
func (*PerlBuilder) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{4}
}

func (m *PerlBuilder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerlBuilder.Unmarshal(m, b)
}
func (m *PerlBuilder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerlBuilder.Marshal(b, m, deterministic)
}
func (m *PerlBuilder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerlBuilder.Merge(m, src)
}
func (m *PerlBuilder) XXX_Size() int {
	return xxx_messageInfo_PerlBuilder.Size(m)
}
func (m *PerlBuilder) XXX_DiscardUnknown() {
	xxx_messageInfo_PerlBuilder.DiscardUnknown(m)
}

var xxx_messageInfo_PerlBuilder proto.InternalMessageInfo

func (m *PerlBuilder) GetExtraMakefileFlag() []string {
	if m != nil {
		return m.ExtraMakefileFlag
	}
	return nil
}

type PythonBuilder struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PythonBuilder) Reset()         { *m = PythonBuilder{} }
func (m *PythonBuilder) String() string { return proto.CompactTextString(m) }
func (*PythonBuilder) ProtoMessage()    {}
func (*PythonBuilder) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{5}
}

func (m *PythonBuilder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PythonBuilder.Unmarshal(m, b)
}
func (m *PythonBuilder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PythonBuilder.Marshal(b, m, deterministic)
}
func (m *PythonBuilder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PythonBuilder.Merge(m, src)
}
func (m *PythonBuilder) XXX_Size() int {
	return xxx_messageInfo_PythonBuilder.Size(m)
}
func (m *PythonBuilder) XXX_DiscardUnknown() {
	xxx_messageInfo_PythonBuilder.DiscardUnknown(m)
}

var xxx_messageInfo_PythonBuilder proto.InternalMessageInfo

type GomodBuilder struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GomodBuilder) Reset()         { *m = GomodBuilder{} }
func (m *GomodBuilder) String() string { return proto.CompactTextString(m) }
func (*GomodBuilder) ProtoMessage()    {}
func (*GomodBuilder) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{6}
}

func (m *GomodBuilder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GomodBuilder.Unmarshal(m, b)
}
func (m *GomodBuilder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GomodBuilder.Marshal(b, m, deterministic)
}
func (m *GomodBuilder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GomodBuilder.Merge(m, src)
}
func (m *GomodBuilder) XXX_Size() int {
	return xxx_messageInfo_GomodBuilder.Size(m)
}
func (m *GomodBuilder) XXX_DiscardUnknown() {
	xxx_messageInfo_GomodBuilder.DiscardUnknown(m)
}

var xxx_messageInfo_GomodBuilder proto.InternalMessageInfo

type Install struct {
	SystemdUnit          []string           `protobuf:"bytes,1,rep,name=systemd_unit,json=systemdUnit" json:"systemd_unit,omitempty"`
	Symlink              []*Install_Symlink `protobuf:"bytes,2,rep,name=symlink" json:"symlink,omitempty"`
	EmptyDir             []string           `protobuf:"bytes,3,rep,name=empty_dir,json=emptyDir" json:"empty_dir,omitempty"`
	Chmod                []*Install_Chmod   `protobuf:"bytes,4,rep,name=chmod" json:"chmod,omitempty"`
	Capability           []*Install_Cap     `protobuf:"bytes,5,rep,name=capability" json:"capability,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Install) Reset()         { *m = Install{} }
func (m *Install) String() string { return proto.CompactTextString(m) }
func (*Install) ProtoMessage()    {}
func (*Install) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{7}
}

func (m *Install) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Install.Unmarshal(m, b)
}
func (m *Install) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Install.Marshal(b, m, deterministic)
}
func (m *Install) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Install.Merge(m, src)
}
func (m *Install) XXX_Size() int {
	return xxx_messageInfo_Install.Size(m)
}
func (m *Install) XXX_DiscardUnknown() {
	xxx_messageInfo_Install.DiscardUnknown(m)
}

var xxx_messageInfo_Install proto.InternalMessageInfo

func (m *Install) GetSystemdUnit() []string {
	if m != nil {
		return m.SystemdUnit
	}
	return nil
}

func (m *Install) GetSymlink() []*Install_Symlink {
	if m != nil {
		return m.Symlink
	}
	return nil
}

func (m *Install) GetEmptyDir() []string {
	if m != nil {
		return m.EmptyDir
	}
	return nil
}

func (m *Install) GetChmod() []*Install_Chmod {
	if m != nil {
		return m.Chmod
	}
	return nil
}

func (m *Install) GetCapability() []*Install_Cap {
	if m != nil {
		return m.Capability
	}
	return nil
}

type Install_Symlink struct {
	Oldname              *string  `protobuf:"bytes,1,opt,name=oldname" json:"oldname,omitempty"`
	Newname              *string  `protobuf:"bytes,2,opt,name=newname" json:"newname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Install_Symlink) Reset()         { *m = Install_Symlink{} }
func (m *Install_Symlink) String() string { return proto.CompactTextString(m) }
func (*Install_Symlink) ProtoMessage()    {}
func (*Install_Symlink) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{7, 0}
}

func (m *Install_Symlink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Install_Symlink.Unmarshal(m, b)
}
func (m *Install_Symlink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Install_Symlink.Marshal(b, m, deterministic)
}
func (m *Install_Symlink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Install_Symlink.Merge(m, src)
}
func (m *Install_Symlink) XXX_Size() int {
	return xxx_messageInfo_Install_Symlink.Size(m)
}
func (m *Install_Symlink) XXX_DiscardUnknown() {
	xxx_messageInfo_Install_Symlink.DiscardUnknown(m)
}

var xxx_messageInfo_Install_Symlink proto.InternalMessageInfo

func (m *Install_Symlink) GetOldname() string {
	if m != nil && m.Oldname != nil {
		return *m.Oldname
	}
	return ""
}

func (m *Install_Symlink) GetNewname() string {
	if m != nil && m.Newname != nil {
		return *m.Newname
	}
	return ""
}

type Install_Chmod struct {
	Setuid               *bool    `protobuf:"varint,1,opt,name=setuid" json:"setuid,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Install_Chmod) Reset()         { *m = Install_Chmod{} }
func (m *Install_Chmod) String() string { return proto.CompactTextString(m) }
func (*Install_Chmod) ProtoMessage()    {}
func (*Install_Chmod) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{7, 1}
}

func (m *Install_Chmod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Install_Chmod.Unmarshal(m, b)
}
func (m *Install_Chmod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Install_Chmod.Marshal(b, m, deterministic)
}
func (m *Install_Chmod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Install_Chmod.Merge(m, src)
}
func (m *Install_Chmod) XXX_Size() int {
	return xxx_messageInfo_Install_Chmod.Size(m)
}
func (m *Install_Chmod) XXX_DiscardUnknown() {
	xxx_messageInfo_Install_Chmod.DiscardUnknown(m)
}

var xxx_messageInfo_Install_Chmod proto.InternalMessageInfo

func (m *Install_Chmod) GetSetuid() bool {
	if m != nil && m.Setuid != nil {
		return *m.Setuid
	}
	return false
}

func (m *Install_Chmod) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Install_Cap struct {
	Filename             *string  `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Capability           *string  `protobuf:"bytes,2,opt,name=capability" json:"capability,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Install_Cap) Reset()         { *m = Install_Cap{} }
func (m *Install_Cap) String() string { return proto.CompactTextString(m) }
func (*Install_Cap) ProtoMessage()    {}
func (*Install_Cap) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{7, 2}
}

func (m *Install_Cap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Install_Cap.Unmarshal(m, b)
}
func (m *Install_Cap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Install_Cap.Marshal(b, m, deterministic)
}
func (m *Install_Cap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Install_Cap.Merge(m, src)
}
func (m *Install_Cap) XXX_Size() int {
	return xxx_messageInfo_Install_Cap.Size(m)
}
func (m *Install_Cap) XXX_DiscardUnknown() {
	xxx_messageInfo_Install_Cap.DiscardUnknown(m)
}

var xxx_messageInfo_Install_Cap proto.InternalMessageInfo

func (m *Install_Cap) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *Install_Cap) GetCapability() string {
	if m != nil && m.Capability != nil {
		return *m.Capability
	}
	return ""
}

type Claim struct {
	Glob                 *string  `protobuf:"bytes,1,opt,name=glob" json:"glob,omitempty"`
	Dir                  *string  `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Claim) Reset()         { *m = Claim{} }
func (m *Claim) String() string { return proto.CompactTextString(m) }
func (*Claim) ProtoMessage()    {}
func (*Claim) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{8}
}

func (m *Claim) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Claim.Unmarshal(m, b)
}
func (m *Claim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Claim.Marshal(b, m, deterministic)
}
func (m *Claim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claim.Merge(m, src)
}
func (m *Claim) XXX_Size() int {
	return xxx_messageInfo_Claim.Size(m)
}
func (m *Claim) XXX_DiscardUnknown() {
	xxx_messageInfo_Claim.DiscardUnknown(m)
}

var xxx_messageInfo_Claim proto.InternalMessageInfo

func (m *Claim) GetGlob() string {
	if m != nil && m.Glob != nil {
		return *m.Glob
	}
	return ""
}

func (m *Claim) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

type SplitPackage struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	RuntimeDep           []string `protobuf:"bytes,2,rep,name=runtime_dep,json=runtimeDep" json:"runtime_dep,omitempty"`
	Claim                []*Claim `protobuf:"bytes,3,rep,name=claim" json:"claim,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SplitPackage) Reset()         { *m = SplitPackage{} }
func (m *SplitPackage) String() string { return proto.CompactTextString(m) }
func (*SplitPackage) ProtoMessage()    {}
func (*SplitPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{9}
}

func (m *SplitPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitPackage.Unmarshal(m, b)
}
func (m *SplitPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitPackage.Marshal(b, m, deterministic)
}
func (m *SplitPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitPackage.Merge(m, src)
}
func (m *SplitPackage) XXX_Size() int {
	return xxx_messageInfo_SplitPackage.Size(m)
}
func (m *SplitPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitPackage.DiscardUnknown(m)
}

var xxx_messageInfo_SplitPackage proto.InternalMessageInfo

func (m *SplitPackage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SplitPackage) GetRuntimeDep() []string {
	if m != nil {
		return m.RuntimeDep
	}
	return nil
}

func (m *SplitPackage) GetClaim() []*Claim {
	if m != nil {
		return m.Claim
	}
	return nil
}

type Union struct {
	// e.g. “out/lib/irssi/modules”
	Dir *string `protobuf:"bytes,1,opt,name=dir" json:"dir,omitempty"`
	// e.g. “irssi”
	Pkg                  *string  `protobuf:"bytes,2,opt,name=pkg" json:"pkg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Union) Reset()         { *m = Union{} }
func (m *Union) String() string { return proto.CompactTextString(m) }
func (*Union) ProtoMessage()    {}
func (*Union) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{10}
}

func (m *Union) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Union.Unmarshal(m, b)
}
func (m *Union) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Union.Marshal(b, m, deterministic)
}
func (m *Union) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Union.Merge(m, src)
}
func (m *Union) XXX_Size() int {
	return xxx_messageInfo_Union.Size(m)
}
func (m *Union) XXX_DiscardUnknown() {
	xxx_messageInfo_Union.DiscardUnknown(m)
}

var xxx_messageInfo_Union proto.InternalMessageInfo

func (m *Union) GetDir() string {
	if m != nil && m.Dir != nil {
		return *m.Dir
	}
	return ""
}

func (m *Union) GetPkg() string {
	if m != nil && m.Pkg != nil {
		return *m.Pkg
	}
	return ""
}

type Build struct {
	// URL to upstream source archive. Currently, only tar.gz archives are supported.
	Source *string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	// Hash (TODO: describe length, introduce prefixes?) of the upstream source archive.
	Hash *string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	// Version number, to be concatenated to the package name.
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Types that are valid to be assigned to Builder:
	//	*Build_Cbuilder
	//	*Build_Cmakebuilder
	//	*Build_Mesonbuilder
	//	*Build_Perlbuilder
	//	*Build_Pythonbuilder
	//	*Build_Gomodbuilder
	Builder isBuild_Builder `protobuf_oneof:"builder"`
	// TODO: move this field into a custom builder
	BuildStep []*BuildStep `protobuf:"bytes,4,rep,name=build_step,json=buildStep" json:"build_step,omitempty"`
	// TODO: rename to build_dep
	Dep        []string `protobuf:"bytes,5,rep,name=dep" json:"dep,omitempty"`
	RuntimeDep []string `protobuf:"bytes,9,rep,name=runtime_dep,json=runtimeDep" json:"runtime_dep,omitempty"`
	// URLs to patches to cherry-pick after extracting the source, e.g.:
	// https://git.savannah.gnu.org/cgit/make.git/patch/?id=48c8a116a914a325a0497721f5d8b58d5bba34d4
	CherryPick   []string        `protobuf:"bytes,6,rep,name=cherry_pick,json=cherryPick" json:"cherry_pick,omitempty"`
	Install      *Install        `protobuf:"bytes,8,opt,name=install" json:"install,omitempty"`
	SplitPackage []*SplitPackage `protobuf:"bytes,11,rep,name=split_package,json=splitPackage" json:"split_package,omitempty"`
	// TODO: document unions
	RuntimeUnion         []*Union `protobuf:"bytes,15,rep,name=runtime_union,json=runtimeUnion" json:"runtime_union,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{11}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *Build) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *Build) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type isBuild_Builder interface {
	isBuild_Builder()
}

type Build_Cbuilder struct {
	Cbuilder *CBuilder `protobuf:"bytes,7,opt,name=cbuilder,oneof"`
}

type Build_Cmakebuilder struct {
	Cmakebuilder *CMakeBuilder `protobuf:"bytes,14,opt,name=cmakebuilder,oneof"`
}

type Build_Mesonbuilder struct {
	Mesonbuilder *MesonBuilder `protobuf:"bytes,16,opt,name=mesonbuilder,oneof"`
}

type Build_Perlbuilder struct {
	Perlbuilder *PerlBuilder `protobuf:"bytes,10,opt,name=perlbuilder,oneof"`
}

type Build_Pythonbuilder struct {
	Pythonbuilder *PythonBuilder `protobuf:"bytes,12,opt,name=pythonbuilder,oneof"`
}

type Build_Gomodbuilder struct {
	Gomodbuilder *GomodBuilder `protobuf:"bytes,13,opt,name=gomodbuilder,oneof"`
}

func (*Build_Cbuilder) isBuild_Builder() {}

func (*Build_Cmakebuilder) isBuild_Builder() {}

func (*Build_Mesonbuilder) isBuild_Builder() {}

func (*Build_Perlbuilder) isBuild_Builder() {}

func (*Build_Pythonbuilder) isBuild_Builder() {}

func (*Build_Gomodbuilder) isBuild_Builder() {}

func (m *Build) GetBuilder() isBuild_Builder {
	if m != nil {
		return m.Builder
	}
	return nil
}

func (m *Build) GetCbuilder() *CBuilder {
	if x, ok := m.GetBuilder().(*Build_Cbuilder); ok {
		return x.Cbuilder
	}
	return nil
}

func (m *Build) GetCmakebuilder() *CMakeBuilder {
	if x, ok := m.GetBuilder().(*Build_Cmakebuilder); ok {
		return x.Cmakebuilder
	}
	return nil
}

func (m *Build) GetMesonbuilder() *MesonBuilder {
	if x, ok := m.GetBuilder().(*Build_Mesonbuilder); ok {
		return x.Mesonbuilder
	}
	return nil
}

func (m *Build) GetPerlbuilder() *PerlBuilder {
	if x, ok := m.GetBuilder().(*Build_Perlbuilder); ok {
		return x.Perlbuilder
	}
	return nil
}

func (m *Build) GetPythonbuilder() *PythonBuilder {
	if x, ok := m.GetBuilder().(*Build_Pythonbuilder); ok {
		return x.Pythonbuilder
	}
	return nil
}

func (m *Build) GetGomodbuilder() *GomodBuilder {
	if x, ok := m.GetBuilder().(*Build_Gomodbuilder); ok {
		return x.Gomodbuilder
	}
	return nil
}

func (m *Build) GetBuildStep() []*BuildStep {
	if m != nil {
		return m.BuildStep
	}
	return nil
}

func (m *Build) GetDep() []string {
	if m != nil {
		return m.Dep
	}
	return nil
}

func (m *Build) GetRuntimeDep() []string {
	if m != nil {
		return m.RuntimeDep
	}
	return nil
}

func (m *Build) GetCherryPick() []string {
	if m != nil {
		return m.CherryPick
	}
	return nil
}

func (m *Build) GetInstall() *Install {
	if m != nil {
		return m.Install
	}
	return nil
}

func (m *Build) GetSplitPackage() []*SplitPackage {
	if m != nil {
		return m.SplitPackage
	}
	return nil
}

func (m *Build) GetRuntimeUnion() []*Union {
	if m != nil {
		return m.RuntimeUnion
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Build) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Build_OneofMarshaler, _Build_OneofUnmarshaler, _Build_OneofSizer, []interface{}{
		(*Build_Cbuilder)(nil),
		(*Build_Cmakebuilder)(nil),
		(*Build_Mesonbuilder)(nil),
		(*Build_Perlbuilder)(nil),
		(*Build_Pythonbuilder)(nil),
		(*Build_Gomodbuilder)(nil),
	}
}

func _Build_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Build)
	// builder
	switch x := m.Builder.(type) {
	case *Build_Cbuilder:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Cbuilder); err != nil {
			return err
		}
	case *Build_Cmakebuilder:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Cmakebuilder); err != nil {
			return err
		}
	case *Build_Mesonbuilder:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Mesonbuilder); err != nil {
			return err
		}
	case *Build_Perlbuilder:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Perlbuilder); err != nil {
			return err
		}
	case *Build_Pythonbuilder:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Pythonbuilder); err != nil {
			return err
		}
	case *Build_Gomodbuilder:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Gomodbuilder); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Build.Builder has unexpected type %T", x)
	}
	return nil
}

func _Build_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Build)
	switch tag {
	case 7: // builder.cbuilder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CBuilder)
		err := b.DecodeMessage(msg)
		m.Builder = &Build_Cbuilder{msg}
		return true, err
	case 14: // builder.cmakebuilder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CMakeBuilder)
		err := b.DecodeMessage(msg)
		m.Builder = &Build_Cmakebuilder{msg}
		return true, err
	case 16: // builder.mesonbuilder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MesonBuilder)
		err := b.DecodeMessage(msg)
		m.Builder = &Build_Mesonbuilder{msg}
		return true, err
	case 10: // builder.perlbuilder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PerlBuilder)
		err := b.DecodeMessage(msg)
		m.Builder = &Build_Perlbuilder{msg}
		return true, err
	case 12: // builder.pythonbuilder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PythonBuilder)
		err := b.DecodeMessage(msg)
		m.Builder = &Build_Pythonbuilder{msg}
		return true, err
	case 13: // builder.gomodbuilder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GomodBuilder)
		err := b.DecodeMessage(msg)
		m.Builder = &Build_Gomodbuilder{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Build_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Build)
	// builder
	switch x := m.Builder.(type) {
	case *Build_Cbuilder:
		s := proto.Size(x.Cbuilder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Build_Cmakebuilder:
		s := proto.Size(x.Cmakebuilder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Build_Mesonbuilder:
		s := proto.Size(x.Mesonbuilder)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Build_Perlbuilder:
		s := proto.Size(x.Perlbuilder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Build_Pythonbuilder:
		s := proto.Size(x.Pythonbuilder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Build_Gomodbuilder:
		s := proto.Size(x.Gomodbuilder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*BuildStep)(nil), "pb.BuildStep")
	proto.RegisterType((*CBuilder)(nil), "pb.CBuilder")
	proto.RegisterType((*CMakeBuilder)(nil), "pb.CMakeBuilder")
	proto.RegisterType((*MesonBuilder)(nil), "pb.MesonBuilder")
	proto.RegisterType((*PerlBuilder)(nil), "pb.PerlBuilder")
	proto.RegisterType((*PythonBuilder)(nil), "pb.PythonBuilder")
	proto.RegisterType((*GomodBuilder)(nil), "pb.GomodBuilder")
	proto.RegisterType((*Install)(nil), "pb.Install")
	proto.RegisterType((*Install_Symlink)(nil), "pb.Install.Symlink")
	proto.RegisterType((*Install_Chmod)(nil), "pb.Install.Chmod")
	proto.RegisterType((*Install_Cap)(nil), "pb.Install.Cap")
	proto.RegisterType((*Claim)(nil), "pb.Claim")
	proto.RegisterType((*SplitPackage)(nil), "pb.SplitPackage")
	proto.RegisterType((*Union)(nil), "pb.Union")
	proto.RegisterType((*Build)(nil), "pb.Build")
}

func init() { proto.RegisterFile("build.proto", fileDescriptor_14ce178a580e4ede) }

var fileDescriptor_14ce178a580e4ede = []byte{
	// 826 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdb, 0x8e, 0xe3, 0x44,
	0x10, 0x9d, 0x4c, 0xd6, 0x9b, 0xb8, 0xec, 0xcc, 0x64, 0x7b, 0x11, 0xb2, 0x06, 0x89, 0x09, 0x96,
	0x80, 0x08, 0xd8, 0x80, 0x66, 0x05, 0x82, 0x87, 0x7d, 0x60, 0xb2, 0x82, 0x41, 0x62, 0xa5, 0xa8,
	0x87, 0x7d, 0xb6, 0x3a, 0x76, 0x8f, 0xd3, 0x8a, 0x2f, 0x2d, 0xdb, 0x59, 0xc8, 0x27, 0xf0, 0x2f,
	0xfc, 0x0c, 0x7f, 0x84, 0xaa, 0xdc, 0xed, 0x74, 0x24, 0xde, 0xba, 0xab, 0xce, 0xa9, 0x3a, 0xae,
	0x3e, 0x65, 0x08, 0xb6, 0x07, 0x55, 0x64, 0x2b, 0xdd, 0xd4, 0x5d, 0xcd, 0x2e, 0xf5, 0x36, 0xbe,
	0x05, 0xff, 0x1e, 0x43, 0x8f, 0x9d, 0xd4, 0x8c, 0xc1, 0x33, 0xd1, 0xe4, 0x1f, 0xa2, 0xd1, 0x62,
	0xbc, 0xf4, 0x39, 0x9d, 0xe3, 0x7f, 0x47, 0x30, 0x5d, 0x13, 0x44, 0x36, 0xec, 0x3b, 0xf8, 0x48,
	0xfe, 0xd5, 0x35, 0x22, 0x49, 0xeb, 0xea, 0x49, 0xe5, 0x87, 0x46, 0x26, 0x4f, 0x85, 0xc8, 0x0d,
	0x81, 0x51, 0x6e, 0x6d, 0x53, 0xbf, 0x14, 0x22, 0x67, 0x9f, 0x41, 0xd8, 0x33, 0x8a, 0x8c, 0x90,
	0x63, 0x42, 0x06, 0x14, 0xfb, 0x9d, 0x42, 0x6c, 0x09, 0xf3, 0xb4, 0xd6, 0xc7, 0xa4, 0xab, 0x13,
	0x52, 0x97, 0xa9, 0x26, 0xba, 0x5c, 0x8c, 0x96, 0x53, 0x7e, 0x85, 0xf1, 0x3f, 0xea, 0x7b, 0x13,
	0x65, 0x5f, 0xc0, 0x75, 0x5f, 0xac, 0x14, 0x7b, 0xd3, 0xf9, 0x19, 0xd5, 0x9b, 0x51, 0xf8, 0x9d,
	0xd8, 0xf7, 0x4d, 0x3f, 0x05, 0x10, 0x87, 0xae, 0x6e, 0x24, 0xca, 0x8c, 0x3c, 0xaa, 0xe5, 0x44,
	0xe2, 0x2b, 0x08, 0xd7, 0x08, 0x36, 0x9f, 0x15, 0xff, 0x08, 0xe1, 0x3b, 0xd9, 0xd6, 0x95, 0xfd,
	0xcc, 0x25, 0xcc, 0x4d, 0x1f, 0x8c, 0xba, 0x9f, 0x78, 0xd5, 0x37, 0xc2, 0x30, 0x76, 0x8a, 0xdf,
	0x40, 0xb0, 0x91, 0x4d, 0x61, 0x89, 0x2b, 0x78, 0x79, 0x12, 0xf8, 0xa4, 0x8a, 0xb3, 0xf1, 0xbc,
	0x18, 0x44, 0x62, 0x86, 0xe8, 0xd7, 0x30, 0xdb, 0x1c, 0xbb, 0xdd, 0xd0, 0x19, 0x95, 0xfd, 0x5a,
	0x97, 0x75, 0x66, 0xef, 0x7f, 0x8f, 0x61, 0xf2, 0x5b, 0xd5, 0x76, 0xa2, 0x28, 0x70, 0x94, 0xed,
	0xb1, 0xed, 0x64, 0x99, 0x25, 0x87, 0x4a, 0x75, 0xa6, 0x6a, 0x60, 0x62, 0xef, 0x2b, 0xd5, 0xb1,
	0x57, 0x30, 0x69, 0x8f, 0x65, 0xa1, 0xaa, 0x7d, 0x74, 0xb9, 0x18, 0x2f, 0x83, 0xbb, 0x97, 0x2b,
	0xbd, 0x5d, 0x99, 0x02, 0xab, 0xc7, 0x3e, 0xc5, 0x2d, 0x86, 0x7d, 0x02, 0xbe, 0x2c, 0x75, 0x77,
	0x4c, 0x70, 0xe4, 0xfd, 0xcb, 0x4c, 0x29, 0xf0, 0x56, 0x35, 0xec, 0x4b, 0xf0, 0xd2, 0x5d, 0x59,
	0x67, 0x34, 0xe2, 0xe0, 0xee, 0x85, 0x5b, 0x69, 0x8d, 0x09, 0xde, 0xe7, 0xd9, 0xb7, 0x00, 0xa9,
	0xd0, 0x62, 0xab, 0x0a, 0xd5, 0x1d, 0x23, 0x8f, 0xd0, 0xd7, 0x67, 0x68, 0xa1, 0xb9, 0x03, 0xb9,
	0x79, 0x03, 0x13, 0x23, 0x85, 0x45, 0x30, 0xa9, 0x8b, 0xac, 0x12, 0xa5, 0x8c, 0x46, 0x8b, 0xd1,
	0xd2, 0xe7, 0xf6, 0x8a, 0x99, 0x4a, 0xfe, 0x49, 0x99, 0xcb, 0x3e, 0x63, 0xae, 0x37, 0xaf, 0xc1,
	0xa3, 0xfe, 0xec, 0x63, 0x78, 0xde, 0xca, 0xee, 0xa0, 0x32, 0xe2, 0x4e, 0xb9, 0xb9, 0xa1, 0x8d,
	0x1d, 0x1e, 0x9d, 0x6f, 0x7e, 0x86, 0xf1, 0x5a, 0x68, 0x76, 0x03, 0x53, 0x1c, 0xbe, 0xd3, 0x70,
	0xb8, 0xa3, 0x6b, 0x9c, 0xef, 0xe8, 0xc9, 0x4e, 0x24, 0x7e, 0x05, 0xde, 0xba, 0x10, 0xaa, 0xc4,
	0xfa, 0x79, 0x51, 0x6f, 0x4d, 0x01, 0x3a, 0xb3, 0x39, 0x8c, 0xad, 0x6f, 0x7d, 0x8e, 0xc7, 0x38,
	0x83, 0xf0, 0x51, 0x17, 0xaa, 0xdb, 0x88, 0x74, 0x2f, 0x72, 0x39, 0xa8, 0x1a, 0x9d, 0x54, 0xb1,
	0x5b, 0x08, 0x9a, 0x43, 0xd5, 0xa9, 0x52, 0x26, 0x99, 0xd4, 0xf4, 0x66, 0x3e, 0x07, 0x13, 0x7a,
	0x2b, 0x35, 0xbb, 0x05, 0x2f, 0xc5, 0x9e, 0xf4, 0x3a, 0xc1, 0x9d, 0x8f, 0x63, 0x25, 0x11, 0xbc,
	0x8f, 0xc7, 0x5f, 0x83, 0xf7, 0xbe, 0x52, 0x75, 0x65, 0x05, 0x8c, 0x06, 0x01, 0x18, 0xd1, 0xfb,
	0xdc, 0x4a, 0xd2, 0xfb, 0x3c, 0xfe, 0xc7, 0x03, 0x8f, 0x9c, 0x45, 0xa3, 0xab, 0x0f, 0x4d, 0x6a,
	0xe5, 0x98, 0x1b, 0x8a, 0xdc, 0x89, 0x76, 0x67, 0x47, 0x87, 0x67, 0x7c, 0x89, 0x0f, 0xb2, 0x69,
	0x55, 0x5d, 0x45, 0xe3, 0xfe, 0x25, 0xcc, 0x95, 0x7d, 0x05, 0xd3, 0x74, 0xdb, 0x3b, 0x35, 0x9a,
	0x2c, 0x46, 0xcb, 0xe0, 0x2e, 0x24, 0x81, 0xc6, 0xbd, 0x0f, 0x17, 0x7c, 0xc8, 0xb3, 0x1f, 0x20,
	0x4c, 0x71, 0x2b, 0x2c, 0xfe, 0x8a, 0xf0, 0x73, 0xc2, 0x3b, 0xbb, 0xf8, 0x70, 0xc1, 0xcf, 0x70,
	0xc8, 0xa3, 0x2d, 0xb4, 0xbc, 0xf9, 0x89, 0xe7, 0xee, 0x2c, 0xf2, 0x5c, 0x1c, 0x7b, 0x0d, 0x81,
	0x96, 0x4d, 0x61, 0x69, 0x40, 0x34, 0xb2, 0xa5, 0xb3, 0xb0, 0x0f, 0x17, 0xdc, 0x45, 0xb1, 0x9f,
	0x60, 0xa6, 0x69, 0x1f, 0x2d, 0x2d, 0x24, 0x1a, 0x79, 0xff, 0x6c, 0x51, 0x1f, 0x2e, 0xf8, 0x39,
	0x12, 0x75, 0xe6, 0xb8, 0xb9, 0x96, 0x39, 0x3b, 0xe9, 0x74, 0x37, 0x1a, 0x75, 0xba, 0x38, 0xf6,
	0x0d, 0x00, 0x1d, 0x93, 0xb6, 0x93, 0xda, 0xec, 0xda, 0x0c, 0x59, 0xc3, 0x6f, 0x99, 0xfb, 0xdb,
	0xe1, 0x0f, 0x8d, 0xaf, 0x2c, 0x35, 0x2d, 0x19, 0xbe, 0x32, 0x39, 0xe4, 0xcc, 0x42, 0xfe, 0xff,
	0x58, 0x28, 0x48, 0x77, 0xb2, 0x69, 0x8e, 0x89, 0x56, 0xe9, 0x3e, 0x7a, 0xde, 0x03, 0xfa, 0xd0,
	0x46, 0xa5, 0x7b, 0xf6, 0x39, 0x4c, 0x54, 0xbf, 0xa9, 0xd1, 0x94, 0x44, 0x07, 0xce, 0xf2, 0x72,
	0x9b, 0x63, 0xdf, 0xc3, 0xac, 0x45, 0x3f, 0x27, 0xba, 0x37, 0x74, 0x14, 0x90, 0x56, 0xfa, 0x42,
	0xd7, 0xe8, 0x3c, 0x6c, 0x5d, 0xdb, 0xaf, 0x60, 0x66, 0xf5, 0x1d, 0xd0, 0xa8, 0xd1, 0xf5, 0xc9,
	0xc9, 0xe4, 0x5c, 0x1e, 0x9a, 0x3c, 0xdd, 0xee, 0x7d, 0x98, 0x98, 0xd1, 0xfc, 0x17, 0x00, 0x00,
	0xff, 0xff, 0xa0, 0xd4, 0x26, 0xd4, 0xad, 0x06, 0x00, 0x00,
}
