// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Meta struct {
	// Transitive closure of runtime dependency package names. E.g.:
	// ["glibc-2.27", "pam-1.3.1"]
	RuntimeDep           []string `protobuf:"bytes,1,rep,name=runtime_dep,json=runtimeDep" json:"runtime_dep,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_b31782cce01baf61, []int{0}
}
func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (dst *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(dst, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetRuntimeDep() []string {
	if m != nil {
		return m.RuntimeDep
	}
	return nil
}

func init() {
	proto.RegisterType((*Meta)(nil), "pb.Meta")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_meta_b31782cce01baf61) }

var fileDescriptor_meta_b31782cce01baf61 = []byte{
	// 76 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0x2d, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe7, 0x62, 0xf1, 0x4d,
	0x2d, 0x49, 0x14, 0x92, 0xe7, 0xe2, 0x2e, 0x2a, 0xcd, 0x2b, 0xc9, 0xcc, 0x4d, 0x8d, 0x4f, 0x49,
	0x2d, 0x90, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0c, 0xe2, 0x82, 0x0a, 0xb9, 0xa4, 0x16, 0x00, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xb0, 0x88, 0x45, 0x9f, 0x39, 0x00, 0x00, 0x00,
}
