// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Meta struct {
	// Transitive closure of runtime dependency package names. E.g.:
	// ["glibc-amd64-2.27-3", "pam-amd64-1.3.1-3"]
	RuntimeDep []string `protobuf:"bytes,1,rep,name=runtime_dep,json=runtimeDep" json:"runtime_dep,omitempty"`
	// The source package from which this package was built. Useful to tie
	// split packages back to their source, and for globbing versions.
	SourcePkg *string `protobuf:"bytes,2,opt,name=source_pkg,json=sourcePkg" json:"source_pkg,omitempty"`
	// The version of the package. In some contexts, the version is already
	// included in the filename, but not when e.g. “distri install” is obtaining
	// meta.textproto files by accessing a symbolic link.
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Runtime union directories are used to implement per-package exchange
	// directories (as opposed to global exchange directories). This is to be used
	// for tight coupling situations, e.g. when a plugin mechanism does not
	// guarantee ABI compatibility across versions.
	RuntimeUnion         []*Union `protobuf:"bytes,4,rep,name=runtime_union,json=runtimeUnion" json:"runtime_union,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetRuntimeDep() []string {
	if m != nil {
		return m.RuntimeDep
	}
	return nil
}

func (m *Meta) GetSourcePkg() string {
	if m != nil && m.SourcePkg != nil {
		return *m.SourcePkg
	}
	return ""
}

func (m *Meta) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *Meta) GetRuntimeUnion() []*Union {
	if m != nil {
		return m.RuntimeUnion
	}
	return nil
}

func init() {
	proto.RegisterType((*Meta)(nil), "pb.Meta")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_3b5ea8fe65782bcc) }

var fileDescriptor_3b5ea8fe65782bcc = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0x2d, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0xe2, 0x4e, 0x2a, 0xcd, 0xcc,
	0x49, 0x81, 0x08, 0x28, 0x4d, 0x60, 0xe4, 0x62, 0xf1, 0x4d, 0x2d, 0x49, 0x14, 0x92, 0xe7, 0xe2,
	0x2e, 0x2a, 0xcd, 0x2b, 0xc9, 0xcc, 0x4d, 0x8d, 0x4f, 0x49, 0x2d, 0x90, 0x60, 0x54, 0x60, 0xd6,
	0xe0, 0x0c, 0xe2, 0x82, 0x0a, 0xb9, 0xa4, 0x16, 0x08, 0xc9, 0x72, 0x71, 0x15, 0xe7, 0x97, 0x16,
	0x25, 0xa7, 0xc6, 0x17, 0x64, 0xa7, 0x4b, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x71, 0x42, 0x44,
	0x02, 0xb2, 0xd3, 0x85, 0x24, 0xb8, 0xd8, 0xcb, 0x52, 0x8b, 0x8a, 0x33, 0xf3, 0xf3, 0x24, 0x98,
	0xc1, 0x72, 0x30, 0xae, 0x90, 0x1e, 0x17, 0x2f, 0xcc, 0xe4, 0xd2, 0x3c, 0x90, 0x3c, 0x8b, 0x02,
	0xb3, 0x06, 0xb7, 0x11, 0xa7, 0x5e, 0x41, 0x92, 0x5e, 0x28, 0x48, 0x20, 0x88, 0x07, 0x2a, 0x0f,
	0xe6, 0x01, 0x02, 0x00, 0x00, 0xff, 0xff, 0x80, 0x35, 0x18, 0xa3, 0xb0, 0x00, 0x00, 0x00,
}
