// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.11.4
// source: mirrormeta.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MirrorMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Package []*MirrorMeta_Package `protobuf:"bytes,1,rep,name=package" json:"package,omitempty"`
}

func (x *MirrorMeta) Reset() {
	*x = MirrorMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirrormeta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MirrorMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorMeta) ProtoMessage() {}

func (x *MirrorMeta) ProtoReflect() protoreflect.Message {
	mi := &file_mirrormeta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorMeta.ProtoReflect.Descriptor instead.
func (*MirrorMeta) Descriptor() ([]byte, []int) {
	return file_mirrormeta_proto_rawDescGZIP(), []int{0}
}

func (x *MirrorMeta) GetPackage() []*MirrorMeta_Package {
	if x != nil {
		return x.Package
	}
	return nil
}

type MirrorMeta_Package struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	WellKnownPath []string `protobuf:"bytes,2,rep,name=well_known_path,json=wellKnownPath" json:"well_known_path,omitempty"`
}

func (x *MirrorMeta_Package) Reset() {
	*x = MirrorMeta_Package{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mirrormeta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MirrorMeta_Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorMeta_Package) ProtoMessage() {}

func (x *MirrorMeta_Package) ProtoReflect() protoreflect.Message {
	mi := &file_mirrormeta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorMeta_Package.ProtoReflect.Descriptor instead.
func (*MirrorMeta_Package) Descriptor() ([]byte, []int) {
	return file_mirrormeta_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MirrorMeta_Package) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MirrorMeta_Package) GetWellKnownPath() []string {
	if x != nil {
		return x.WellKnownPath
	}
	return nil
}

var File_mirrormeta_proto protoreflect.FileDescriptor

var file_mirrormeta_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x85, 0x01, 0x0a, 0x0a, 0x4d, 0x69, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x30, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x69, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x07,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x1a, 0x45, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x77, 0x65, 0x6c, 0x6c, 0x5f, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0d, 0x77, 0x65, 0x6c, 0x6c, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62,
}

var (
	file_mirrormeta_proto_rawDescOnce sync.Once
	file_mirrormeta_proto_rawDescData = file_mirrormeta_proto_rawDesc
)

func file_mirrormeta_proto_rawDescGZIP() []byte {
	file_mirrormeta_proto_rawDescOnce.Do(func() {
		file_mirrormeta_proto_rawDescData = protoimpl.X.CompressGZIP(file_mirrormeta_proto_rawDescData)
	})
	return file_mirrormeta_proto_rawDescData
}

var file_mirrormeta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mirrormeta_proto_goTypes = []interface{}{
	(*MirrorMeta)(nil),         // 0: pb.MirrorMeta
	(*MirrorMeta_Package)(nil), // 1: pb.MirrorMeta.Package
}
var file_mirrormeta_proto_depIdxs = []int32{
	1, // 0: pb.MirrorMeta.package:type_name -> pb.MirrorMeta.Package
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mirrormeta_proto_init() }
func file_mirrormeta_proto_init() {
	if File_mirrormeta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mirrormeta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MirrorMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mirrormeta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MirrorMeta_Package); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mirrormeta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mirrormeta_proto_goTypes,
		DependencyIndexes: file_mirrormeta_proto_depIdxs,
		MessageInfos:      file_mirrormeta_proto_msgTypes,
	}.Build()
	File_mirrormeta_proto = out.File
	file_mirrormeta_proto_rawDesc = nil
	file_mirrormeta_proto_goTypes = nil
	file_mirrormeta_proto_depIdxs = nil
}
