source: "https://github.com/docker/cli/archive/v18.06.1-ce.tar.gz"
hash: "47eda354afc199693aa338f5b2bb87e4511354c02561ddc6520a06d169921bdf"
version: "18.06.1-ce"

cbuilder: <> # TODO: remove once the Go builder takes care of pulling in the C deps

# Go build environment:
dep: "golang-1.11"

# build dependencies:

# TODO: map GOCACHE into the build environment

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "export GOPATH=$PWD/go && d=go/src/github.com/docker/cli && mkdir -p $d && cd $d && cp -T -ar ${ZI_SOURCEDIR}/ . && DISABLE_WARN_OUTSIDE_CONTAINER=1 LDFLAGS= make && d=${ZI_DESTDIR}/${ZI_PREFIX}/bin; mkdir -p $d; cp -H build/docker $d/"
>

