source: "https://github.com/docker/cli/archive/v19.03.8.tar.gz"
hash: "36dd85273c95f4755e08b37ea9660a1bf5c315570b679a0ce268750ca1ed3801"
version: "19.03.8-10"

cbuilder: {}  # TODO: remove once the Go builder takes care of pulling in the C deps

# Go build environment:
dep: "golang"

# build dependencies:

runtime_dep: "procps-ng"
runtime_dep: "iptables"
runtime_dep: "xzutils"
runtime_dep: "e2fsprogs"
runtime_dep: "kmod"

# TODO: map GOCACHE into the build environment

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "export GOPATH=$PWD/go HOME=$PWD && d=go/src/github.com/docker/cli && mkdir -p $d && cd $d && cp -T -ar ${DISTRI_SOURCEDIR}/ . && DISABLE_WARN_OUTSIDE_CONTAINER=1 LDFLAGS= make && d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/bin; mkdir -p $d; cp -H build/docker $d/"
}

