source: "https://i3wm.org/i3lock/i3lock-2.12.tar.bz2"
hash: "d0b2a1a96ce80649958b27b8d54a6069b3aec9e7ffe07d378f9c51763b56bc09"
version: "2.12-12"

cbuilder: {}

# build dependencies:
dep: "libev"
dep: "libxcb"
dep: "xcb-util-image"
dep: "xcb-util-xrm"
dep: "libxkbcommon"
dep: "cairo"
