source: "https://i3wm.org/i3lock/i3lock-2.11.1.tar.bz2"
hash: "f2a8c3d8827529e1dbb2ca870b0b27592c741356fb32dbf0969d9d4a46b1ad04"
version: "2.11.1-10"

cbuilder: {}

# build dependencies:
dep: "libev"
dep: "libxcb"
dep: "xcb-util-image"
dep: "xcb-util-xrm"
dep: "libxkbcommon"
dep: "cairo"
