source: "https://download.gnome.org/sources/glib/2.58/glib-2.58.0.tar.xz"
hash: "c0f4ce0730b4f95c47b711613b5406a887c2ee13ea6d25930d72a4fa7fdb77f6"
version: "2.58.0"

cbuilder: <>

# build dependencies:
dep: "meson"
dep: "ninja"
dep: "python3"
dep: "libffi"
dep: "zlib"
dep: "util-linux"

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "PYTHONPATH=/ro/meson-0.47.1/buildoutput//lib/python3.7/site-packages/ meson --prefix=${ZI_PREFIX} . ${ZI_SOURCEDIR} -Dselinux=false"
>

# kludge: the LD_LIBRARY_PATH change is required because we patched rpath handling out of meson.
build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "PYTHONPATH=/ro/meson-0.47.1/buildoutput//lib/python3.7/site-packages/ LD_LIBRARY_PATH=$PWD/gio:$PWD/gobject:$PWD/glib:$LD_LIBRARY_PATH ninja -v"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "DESTDIR=${ZI_DESTDIR} PYTHONPATH=/ro/meson-0.47.1/buildoutput//lib/python3.7/site-packages/ ninja -v install"
>
