source: "https://mirrors.edge.kernel.org/pub/linux/utils/net/iproute2/iproute2-5.6.0.tar.xz"
hash: "1b5b0e25ce6e23da7526ea1da044e814ad85ba761b10dd29c2b027c056b04692"
version: "5.6.0-7"

writable_sourcedir: true
in_tree_build: true

cbuilder: {
  # TODO: switch to cbuilder once we decide how custom make install arguments should be passed
}

# build dependencies:
dep: "libmnl"
dep: "findutils"
dep: "bison"
dep: "flex"
dep: "m4"  # TODO: remove (runtime-dep of flex)

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "./configure --prefix=${DISTRI_PREFIX}"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "make -j${DISTRI_JOBS} V=1"
}
build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "make install DESTDIR=${DISTRI_DESTDIR} PREFIX=${DISTRI_PREFIX} SBINDIR=${DISTRI_PREFIX}/sbin"
}
