source: "https://mirrors.edge.kernel.org/pub/linux/utils/net/iproute2/iproute2-4.18.0.tar.xz"
hash: "a9e6c70c95f513871c5e1f4e452c04fcb3c4d8a05be651bd794cd994a52daa45"
version: "4.18.0"

# TODO: switch to cbuilder once we decide how custom make install arguments should be passed
# cbuilder: <
#   copy_to_builddir: true
# >

# configure runtime requirements:
dep: "bash-4.4.18"
dep: "coreutils-8.30"
dep: "sed-4.5"
dep: "grep-3.1"
dep: "gawk-4.2.1"

# C build environment:
dep: "gcc-8.2.0"
dep: "binutils-2.31"
dep: "make-4.2.1"
dep: "glibc-2.27"
dep: "linux-libc-dev-4.15.4"

dep: "diffutils-3.6"
dep: "findutils-4.6.0"

# build dependencies:
dep: "pkg-config-0.29.2"
dep: "libmnl-1.0.4"
dep: "findutils-4.6.0"
dep: "bison-3.0.5"
dep: "flex-2.6.4"
dep: "m4-1.4.18" # TODO: remove (runtime-dep of flex)

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "cp -T -ar ${ZI_SOURCEDIR}/ ."
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "./configure --prefix=${ZI_PREFIX}"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "make -j8 V=1"
>
build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "make install DESTDIR=${ZI_DESTDIR} PREFIX=${ZI_PREFIX} SBINDIR=${ZI_PREFIX}/sbin"
>
