source: "https://archive.xfce.org/src/xfce/libxfce4util/4.13/libxfce4util-4.13.3.tar.bz2"
hash: "724b523a4a9ec8cada727950ab2173be30f256fa332a891ccd28b46f4b91b67e"
version: "4.13.3-4"

cbuilder: {}

# build dependencies:
dep: "intltool"
dep: "glib"
