source: "https://archive.xfce.org/src/xfce/libxfce4util/4.13/libxfce4util-4.13.5.tar.bz2"
hash: "9bbb095252775a6457e927aa2580b84efd1288446fcb54a046b5112ac7849035"
version: "4.13.5-7"

cbuilder: {}

# build dependencies:
dep: "intltool"
dep: "glib"
