source: "https://ftp.gnu.org/gnu/gzip/gzip-1.10.tar.xz"
hash: "8425ccac99872d544d4310305f915f5ea81e04d0f437ef1a230dc9d1c819d7c0"
version: "1.10-4"

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

cbuilder: {}
