source: "http://ftp.gnome.org/pub/gnome/sources/json-glib/1.4/json-glib-1.4.4.tar.xz"
hash: "720c5f4379513dc11fd97dc75336eb0c0d3338c53128044d9fabec4374f4bc47"
version: "1.4.4-3"

mesonbuilder: {}

# build dependencies:
dep: "gobject-introspection"
dep: "gettext"
