source: "https://linuxtv.org/downloads/v4l-utils/v4l-utils-1.20.0.tar.bz2"
hash: "956118713f7ccb405c55c7088a6a2490c32d54300dd9a30d8d5008c28d3726f7"
version: "1.20.0-1"

cbuilder: {
  extra_configure_flag: "--with-udevdir=${DISTRI_PREFIX}/lib/udev"
}

# build dependencies:
dep: "perl"
