source: "https://www.kernel.org/pub/linux/utils/cryptsetup/v2.0/cryptsetup-2.0.6.tar.xz"
hash: "7c51fae0f0e7ea9af0f515b2ac77009fb2969a6619ebab47d097dca38b083d30"
version: "2.0.6-8"

cbuilder: {}

# build dependencies:
dep: "lvm2"
dep: "popt"
dep: "json-c"
dep: "libgcrypt"
dep: "lvm2"
dep: "libudev"
dep: "systemd"  # to pick up new version
