source: "empty://"
version: "1-1"

# configure runtime requirements:
dep: "bash"
dep: "coreutils"
dep: "sed"
dep: "grep"
dep: "gawk"

# C build environment:
dep: "gcc"
dep: "binutils"
dep: "make"
dep: "glibc"
dep: "linux"

dep: "strace"
dep: "m4"

dep: "libmnl"

dep: "findutils"

# pre-warming for squashfs performance measurements:
# build_step: <
#   argv: "find"
#   argv: "/ro/gcc-8.2.0/out/bin"
#   argv: "-exec"
#   argv: "md5sum"
#   argv: "{}"
#   argv: ";"
# >
# 
# build_step: <
#   argv: "/bin/sh"
#   argv: "-c"
#   argv: "gcc -o foo ${DISTRI_SOURCEDIR}/foo.c -lmnl $LDFLAGS"
# >

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: ""
>

# build_step: <
#   argv: "/bin/sh"
#   argv: "-c"
#   argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/bin/foo; mkdir -p $(dirname $d); cp foo $d"
# >
# 
