source: "https://xorg.freedesktop.org/releases/individual/xserver/xorg-server-1.20.8.tar.bz2"
hash: "d17b646bee4ba0fb7850c1cc55b18e3e8513ed5c02bdf38da7e107f84e2d0146"
version: "1.20.8-15"

pull: {
  # xorg-server-1.14.5.901.tar.bz2 is not valid semver, but newer releases are
  # TODO: ask upstream for a commitment to semver
  force_semver: true
}

writable_sourcedir: true  # generate files in /usr/src (included in src squashfs)

mesonbuilder: {
  extra_meson_flag: "-Dxdmcp=false"
  extra_meson_flag: "-Dsecure-rpc=false"
  extra_meson_flag: "-Dxwayland=false"
}

cherry_pick: "moduledir.patch"
cherry_pick: "dridir.patch"

# build dependencies:
dep: "pixman"
dep: "libdrm"
dep: "libx11"
dep: "mesa"
dep: "openssl"
dep: "xorgproto"
dep: "xtrans"
dep: "libxkbfile"
dep: "libxfont2"
dep: "libpciaccess"
dep: "libepoxy"
dep: "zlib"  # TODO: configure doesn’t check for it
dep: "xkbcomp"
dep: "systemd"  # for udev
dep: "nettle"
dep: "font-util"

dep: "meson"

runtime_dep: "xkbcomp"
