source: "http://busybox.net/downloads/busybox-1.29.2.tar.bz2"
hash: "67d2fa6e147a45875fe972de62d907ef866fe784c495c363bf34756c444a5d61"
version: "1.29.2-4"

cbuilder: {}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "cd ${DISTRI_SOURCEDIR} && make O=${DISTRI_BUILDDIR} V=1 defconfig HOSTCFLAGS=-static HOSTLDFLAGS=-static"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "echo CONFIG_STATIC=y >> .config"
}

build_step: {
  argv: "make"
  argv: "-j${DISTRI_JOBS}"
  argv: "V=1"
  argv: "HOSTCFLAGS=-static"
  argv: "HOSTLDFLAGS=-static"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}/bin; mkdir -p $d && cp busybox $d"
}
