source: "https://ftp.gnu.org/gnu/libidn/libidn2-2.3.0.tar.lz"
hash: "6b222435016e2d9fce34af0b21057ebc85704c27e41a781466d9287f0627dc93"
version: "2.3.0-7"

# build dependencies:
dep: "iconv"
dep: "libunistring"

cbuilder: {}
