source: "https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.46.tar.gz"
hash: "d331332491c51cccfb4cb94ffc44f9cd73378e618498d4a37df9e043661c515d"
version: "2.46-7"

perlbuilder: {
  extra_makefile_flag: "EXPATLIBPATH=/ro/${DISTRI_RESOLVE:expat}/out/lib"
}

# build dependencies:
dep: "expat"
dep: "perl-libwww-perl"
