source: "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.6.5.tar.xz"
hash: "f79bd3dbcbe1e7afba256d59b4ca21da12d2c5b4189804dffb2a49fd2b9b52e6"
version: "5.6.5-7"

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

cherry_pick: "config.patch"
cherry_pick: "linux-werror.patch"

# build dependencies:
dep: "bison"
dep: "flex"
dep: "m4"  # TODO: make m4 a runtime dep of flex
dep: "elfutils"
dep: "bc"
dep: "openssl"
dep: "perl"
dep: "gzip"
dep: "kmod"
dep: "rsync"

build_step: {
  argv: "make"
  argv: "olddefconfig"
  argv: "ARCH=i386"
}

build_step: {
  argv: "make"
  argv: "headers_install"
  argv: "INSTALL_HDR_PATH=${DISTRI_DESTDIR}/${DISTRI_PREFIX}"
  argv: "ARCH=i386"
}
