source: "https://www.nano-editor.org/dist/v4/nano-4.9.2.tar.gz"
hash: "31186eab2c266575a049d73216d422f3ad035304e071a82a9f34560b1cfee320"
version: "4.9.2-5"

cbuilder: {}

# build dependencies:
dep: "ncurses"
dep: "pkg-config"

