source: "https://xorg.freedesktop.org/releases/individual/app/setxkbmap-1.3.1.tar.bz2"
hash: "a9ddb3963f263ba13f0ea105d8c45a531832140530217cc559587bb94f02d3e1"
version: "1.3.1"

cbuilder: <
  extra_configure_flag: "--with-xkb-config-root=/ro/xkeyboard-config-2.25/buildoutput/share/X11/xkb"
>

# build dependencies:
dep: "libx11"
dep: "libxkbfile"

runtime_dep: "xkeyboard-config-2.25"
