source: "https://xorg.freedesktop.org/releases/individual/lib/libXrender-0.9.10.tar.bz2"
hash: "c06d5979f86e64cabbde57c223938db0b939dff49fdb5a793a1d3d0396650949"
version: "0.9.10-7"

cbuilder: {}

# build dependencies:
dep: "libx11"
