source: "https://github.com/lloyd/yajl/archive/2.1.0.tar.gz"
hash: "3fb73364a5a30efe615046d07e6db9d09fd2b41c763c5f7d3bfb121cd5c5ac5a"
version: "2.1.0-1"

cmakebuilder: <>

# build dependencies:

install: <
  # xtrans is the only package which installs to share/pkgconfig
  symlink: < oldname: "../../share/pkgconfig/yajl.pc" newname: "lib/pkgconfig/yajl.pc" >
>
