source: "https://github.com/Airblader/xcb-util-xrm/releases/download/v1.3/xcb-util-xrm-1.3.tar.bz2"
hash: "301cf33701207ea8782d49f4cb6404abd8f2d64e16f242017fd720be7c900c85"
version: "1.3-2"

cbuilder: <>

# build dependencies:
dep: "m4"
dep: "libxcb"
dep: "xorgproto"
dep: "xcb-util"
dep: "libx11"
