source: "https://github.com/dstat-real/dstat/archive/v0.7.4.tar.gz"
hash: "4fbd58f3461c86d09a3ab97472aa204de37aa33d31a0493a3e5ed86a2045abea"
version: "0.7.4-1"

# https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/dstat#n30
# sed -i "s/import collections/import collections.abc/g" dstat
# sed -i "s/collections.Sequence/collections.abc.Sequence/g" dstat
cherry_pick: "deprecation.patch"

cbuilder: {}

# build dependencies:
dep: "python3"
dep: "python-six"

runtime_dep: "python-six"

build_step: {
  argv: "make"
  argv: "-C"
  argv: "${DISTRI_SOURCEDIR}"
  argv: "-j${DISTRI_JOBS}"
  argv: "V=1"
}

build_step: {
  argv: "make"
  argv: "-C"
  argv: "${DISTRI_SOURCEDIR}"
  argv: "install"
  argv: "V=1"
  argv: "prefix=${DISTRI_PREFIX}"
  argv: "DESTDIR=${DISTRI_DESTDIR}"
}
