source: "http://download.savannah.nongnu.org/releases/man-db/man-db-2.9.1.tar.xz"
hash: "ba3d8afc5c09a7265a8dabfa0e7c1f4b3ab97df9abf1f6810faa8f301056c74f"
version: "2.9.1-7"

cbuilder: {
  extra_configure_flag: "--disable-cache-owner"  # don’t try to chown to man
  extra_configure_flag: "--with-systemdsystemunitdir=${prefix}/lib/systemd/system"
  extra_configure_flag: "--with-pager=less"
}

# build dependencies:
dep: "libpipeline"
dep: "gdbm"
dep: "groff"  # NOTE: man-db doesn’t compile without groff
dep: "gzip"  # NOTE: man-db doesn’t compile if no compressors are found
dep: "flex"

runtime_dep: "groff"
