source: "http://download.savannah.nongnu.org/releases/man-db/man-db-2.8.4.tar.xz"
hash: "103c185f9d8269b9ee3b8a4cb27912b3aa393e952731ef96fedc880723472bc3"
version: "2.8.4"

cbuilder: <
  extra_configure_flag: "--disable-cache-owner" # don’t try to chown to man
>

# build dependencies:
dep: "libpipeline-1.5.0"
dep: "gdbm-1.18"
dep: "groff-1.22.3" # NOTE: man-db doesn’t compile without groff
dep: "gzip-1.9" # NOTE: man-db doesn’t compile if no compressors are found
