source: "https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz"
hash: "6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591"
version: "0.29.2"

# configure runtime requirements:
dep: "bash-4.4.18"
dep: "coreutils-8.30"
dep: "sed-4.5"
dep: "grep-3.1"
dep: "gawk-4.2.1"

# C build environment:
dep: "gcc-8.2.0"
dep: "binutils-2.31"
dep: "make-4.2.1"
dep: "glibc-2.27"
dep: "linux-4.18.7"

# build dependencies:

build_step: <
  argv: "${ZI_SOURCEDIR}/configure"
  argv: "--prefix=${ZI_PREFIX}"
  argv: "--disable-silent-rules"
  argv: "LDFLAGS=-static" # TODO: remove once pkg-config can be built with -hermetic=true
  argv: "PKG_CONFIG=pkg-config --static" # TODO: remove once pkg-config can be built with -hermetic=true
>

build_step: <
  argv: "make"
  argv: "-j8"
  argv: "LDFLAGS=-all-static" # TODO: remove once pkg-config can be built with -hermetic=true
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "DESTDIR=${ZI_DESTDIR} make install"
>

