source: "https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz"
hash: "6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591"
version: "0.29.2"

cbuilder: <>

# build dependencies:
dep: "glib"
