source: "https://dl.google.com/go/go1.14.2.src.tar.gz"
hash: "98de84e69726a66da7b4e58eac41b99cbe274d7e8906eeb8a5b7eb0aadee7f7c"
version: "1.14.2-8"
pull: {
  releases_url: "https://golang.org/dl/"
}

writable_sourcedir: true
in_tree_build: true

cbuilder: {}

# build dependencies:
dep: "golang14"

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "cd src && TMPDIR=/tmp GOROOT_FINAL=${DISTRI_PREFIX} ./make.bash"
}

build_step: {
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${DISTRI_DESTDIR}/${DISTRI_PREFIX}; mkdir -p $d/bin; cp -r bin src pkg $d/"
}
