source: "https://dl.google.com/go/go1.11.src.tar.gz"
hash: "afc1e12f5fe49a471e3aae7d906c73e9d5b1fdd36d52d72652dde8f6250152fb"
version: "1.11"

# configure runtime requirements:
dep: "bash-4.4.18"
dep: "coreutils-8.30"
dep: "sed-4.5"
dep: "grep-3.1"
dep: "gawk-4.2.1"

# C build environment:
dep: "gcc-8.2.0"
dep: "binutils-2.31"
dep: "make-4.2.1"
dep: "glibc-2.27"
dep: "linux-4.18.7"

# build dependencies:
dep: "diffutils-3.6"
dep: "golang14-1.4.3"

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "cp -T -ar ${ZI_SOURCEDIR}/ ."
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "cd src && TMPDIR=/tmp GOROOT_FINAL=${ZI_PREFIX} ./make.bash"
>

build_step: <
  argv: "/bin/sh"
  argv: "-c"
  argv: "d=${ZI_DESTDIR}/${ZI_PREFIX}; mkdir -p $d/bin; cp -r bin src pkg $d/"  
>
